/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FlagCommentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FlagCommentResponse{}

// FlagCommentResponse struct for FlagCommentResponse
type FlagCommentResponse struct {
	StatusCode *int32 `json:"statusCode,omitempty"`
	Status APIStatus `json:"status"`
	Code *string `json:"code,omitempty"`
	Reason *string `json:"reason,omitempty"`
	WasUnapproved *bool `json:"wasUnapproved,omitempty"`
}

type _FlagCommentResponse FlagCommentResponse

// NewFlagCommentResponse instantiates a new FlagCommentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlagCommentResponse(status APIStatus) *FlagCommentResponse {
	this := FlagCommentResponse{}
	this.Status = status
	return &this
}

// NewFlagCommentResponseWithDefaults instantiates a new FlagCommentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlagCommentResponseWithDefaults() *FlagCommentResponse {
	this := FlagCommentResponse{}
	return &this
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *FlagCommentResponse) GetStatusCode() int32 {
	if o == nil || IsNil(o.StatusCode) {
		var ret int32
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlagCommentResponse) GetStatusCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *FlagCommentResponse) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given int32 and assigns it to the StatusCode field.
func (o *FlagCommentResponse) SetStatusCode(v int32) {
	o.StatusCode = &v
}

// GetStatus returns the Status field value
func (o *FlagCommentResponse) GetStatus() APIStatus {
	if o == nil {
		var ret APIStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *FlagCommentResponse) GetStatusOk() (*APIStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *FlagCommentResponse) SetStatus(v APIStatus) {
	o.Status = v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *FlagCommentResponse) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlagCommentResponse) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *FlagCommentResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *FlagCommentResponse) SetCode(v string) {
	o.Code = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *FlagCommentResponse) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlagCommentResponse) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *FlagCommentResponse) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *FlagCommentResponse) SetReason(v string) {
	o.Reason = &v
}

// GetWasUnapproved returns the WasUnapproved field value if set, zero value otherwise.
func (o *FlagCommentResponse) GetWasUnapproved() bool {
	if o == nil || IsNil(o.WasUnapproved) {
		var ret bool
		return ret
	}
	return *o.WasUnapproved
}

// GetWasUnapprovedOk returns a tuple with the WasUnapproved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlagCommentResponse) GetWasUnapprovedOk() (*bool, bool) {
	if o == nil || IsNil(o.WasUnapproved) {
		return nil, false
	}
	return o.WasUnapproved, true
}

// HasWasUnapproved returns a boolean if a field has been set.
func (o *FlagCommentResponse) HasWasUnapproved() bool {
	if o != nil && !IsNil(o.WasUnapproved) {
		return true
	}

	return false
}

// SetWasUnapproved gets a reference to the given bool and assigns it to the WasUnapproved field.
func (o *FlagCommentResponse) SetWasUnapproved(v bool) {
	o.WasUnapproved = &v
}

func (o FlagCommentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlagCommentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StatusCode) {
		toSerialize["statusCode"] = o.StatusCode
	}
	toSerialize["status"] = o.Status
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	if !IsNil(o.WasUnapproved) {
		toSerialize["wasUnapproved"] = o.WasUnapproved
	}
	return toSerialize, nil
}

func (o *FlagCommentResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFlagCommentResponse := _FlagCommentResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFlagCommentResponse)

	if err != nil {
		return err
	}

	*o = FlagCommentResponse(varFlagCommentResponse)

	return err
}

type NullableFlagCommentResponse struct {
	value *FlagCommentResponse
	isSet bool
}

func (v NullableFlagCommentResponse) Get() *FlagCommentResponse {
	return v.value
}

func (v *NullableFlagCommentResponse) Set(val *FlagCommentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFlagCommentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFlagCommentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlagCommentResponse(val *FlagCommentResponse) *NullableFlagCommentResponse {
	return &NullableFlagCommentResponse{value: val, isSet: true}
}

func (v NullableFlagCommentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlagCommentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


