/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// SizePreset the model 'SizePreset'
type SizePreset string

// List of SizePreset
const (
	SIZEPRESET_DEFAULT SizePreset = "Default"
	SIZEPRESET_CROSS_PLATFORM SizePreset = "CrossPlatform"
)

// All allowed values of SizePreset enum
var AllowedSizePresetEnumValues = []SizePreset{
	"Default",
	"CrossPlatform",
}

func (v *SizePreset) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SizePreset(value)
	for _, existing := range AllowedSizePresetEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SizePreset", value)
}

// NewSizePresetFromValue returns a pointer to a valid SizePreset
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSizePresetFromValue(v string) (*SizePreset, error) {
	ev := SizePreset(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SizePreset: valid values are %v", v, AllowedSizePresetEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SizePreset) IsValid() bool {
	for _, existing := range AllowedSizePresetEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SizePreset value
func (v SizePreset) Ptr() *SizePreset {
	return &v
}

type NullableSizePreset struct {
	value *SizePreset
	isSet bool
}

func (v NullableSizePreset) Get() *SizePreset {
	return v.value
}

func (v *NullableSizePreset) Set(val *SizePreset) {
	v.value = val
	v.isSet = true
}

func (v NullableSizePreset) IsSet() bool {
	return v.isSet
}

func (v *NullableSizePreset) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSizePreset(val *SizePreset) *NullableSizePreset {
	return &NullableSizePreset{value: val, isSet: true}
}

func (v NullableSizePreset) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSizePreset) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

