/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AdjustVotesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdjustVotesResponse{}

// AdjustVotesResponse struct for AdjustVotesResponse
type AdjustVotesResponse struct {
	Status string `json:"status"`
	NewCommentVotes int32 `json:"newCommentVotes"`
}

type _AdjustVotesResponse AdjustVotesResponse

// NewAdjustVotesResponse instantiates a new AdjustVotesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdjustVotesResponse(status string, newCommentVotes int32) *AdjustVotesResponse {
	this := AdjustVotesResponse{}
	this.Status = status
	this.NewCommentVotes = newCommentVotes
	return &this
}

// NewAdjustVotesResponseWithDefaults instantiates a new AdjustVotesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdjustVotesResponseWithDefaults() *AdjustVotesResponse {
	this := AdjustVotesResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *AdjustVotesResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AdjustVotesResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AdjustVotesResponse) SetStatus(v string) {
	o.Status = v
}

// GetNewCommentVotes returns the NewCommentVotes field value
func (o *AdjustVotesResponse) GetNewCommentVotes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NewCommentVotes
}

// GetNewCommentVotesOk returns a tuple with the NewCommentVotes field value
// and a boolean to check if the value has been set.
func (o *AdjustVotesResponse) GetNewCommentVotesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewCommentVotes, true
}

// SetNewCommentVotes sets field value
func (o *AdjustVotesResponse) SetNewCommentVotes(v int32) {
	o.NewCommentVotes = v
}

func (o AdjustVotesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdjustVotesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["newCommentVotes"] = o.NewCommentVotes
	return toSerialize, nil
}

func (o *AdjustVotesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"newCommentVotes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdjustVotesResponse := _AdjustVotesResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdjustVotesResponse)

	if err != nil {
		return err
	}

	*o = AdjustVotesResponse(varAdjustVotesResponse)

	return err
}

type NullableAdjustVotesResponse struct {
	value *AdjustVotesResponse
	isSet bool
}

func (v NullableAdjustVotesResponse) Get() *AdjustVotesResponse {
	return v.value
}

func (v *NullableAdjustVotesResponse) Set(val *AdjustVotesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAdjustVotesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAdjustVotesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdjustVotesResponse(val *AdjustVotesResponse) *NullableAdjustVotesResponse {
	return &NullableAdjustVotesResponse{value: val, isSet: true}
}

func (v NullableAdjustVotesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdjustVotesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


