/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// UserSearchSection the model 'UserSearchSection'
type UserSearchSection string

// List of UserSearchSection
const (
	USERSEARCHSECTION_MODERATORS UserSearchSection = "moderators"
	USERSEARCHSECTION_ON_THIS_PAGE UserSearchSection = "onThisPage"
	USERSEARCHSECTION_ON_THIS_SITE UserSearchSection = "onThisSite"
)

// All allowed values of UserSearchSection enum
var AllowedUserSearchSectionEnumValues = []UserSearchSection{
	"moderators",
	"onThisPage",
	"onThisSite",
}

func (v *UserSearchSection) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := UserSearchSection(value)
	for _, existing := range AllowedUserSearchSectionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid UserSearchSection", value)
}

// NewUserSearchSectionFromValue returns a pointer to a valid UserSearchSection
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewUserSearchSectionFromValue(v string) (*UserSearchSection, error) {
	ev := UserSearchSection(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for UserSearchSection: valid values are %v", v, AllowedUserSearchSectionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v UserSearchSection) IsValid() bool {
	for _, existing := range AllowedUserSearchSectionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to UserSearchSection value
func (v UserSearchSection) Ptr() *UserSearchSection {
	return &v
}

type NullableUserSearchSection struct {
	value *UserSearchSection
	isSet bool
}

func (v NullableUserSearchSection) Get() *UserSearchSection {
	return v.value
}

func (v *NullableUserSearchSection) Set(val *UserSearchSection) {
	v.value = val
	v.isSet = true
}

func (v NullableUserSearchSection) IsSet() bool {
	return v.isSet
}

func (v *NullableUserSearchSection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserSearchSection(val *UserSearchSection) *NullableUserSearchSection {
	return &NullableUserSearchSection{value: val, isSet: true}
}

func (v NullableUserSearchSection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserSearchSection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

