/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// GetTranslationsResponse1 struct for GetTranslationsResponse1
type GetTranslationsResponse1 struct {
	APIError *APIError
	GetTranslationsResponse *GetTranslationsResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetTranslationsResponse1) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal JSON data into GetTranslationsResponse
	err = json.Unmarshal(data, &dst.GetTranslationsResponse);
	if err == nil {
		jsonGetTranslationsResponse, _ := json.Marshal(dst.GetTranslationsResponse)
		if string(jsonGetTranslationsResponse) == "{}" { // empty struct
			dst.GetTranslationsResponse = nil
		} else {
			return nil // data stored in dst.GetTranslationsResponse, return on the first match
		}
	} else {
		dst.GetTranslationsResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetTranslationsResponse1)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetTranslationsResponse1) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.GetTranslationsResponse != nil {
		return json.Marshal(&src.GetTranslationsResponse)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableGetTranslationsResponse1 struct {
	value *GetTranslationsResponse1
	isSet bool
}

func (v NullableGetTranslationsResponse1) Get() *GetTranslationsResponse1 {
	return v.value
}

func (v *NullableGetTranslationsResponse1) Set(val *GetTranslationsResponse1) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTranslationsResponse1) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTranslationsResponse1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTranslationsResponse1(val *GetTranslationsResponse1) *NullableGetTranslationsResponse1 {
	return &NullableGetTranslationsResponse1{value: val, isSet: true}
}

func (v NullableGetTranslationsResponse1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTranslationsResponse1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


