/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// GetTenantsResponse1 struct for GetTenantsResponse1
type GetTenantsResponse1 struct {
	APIError *APIError
	GetTenantsResponse *GetTenantsResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetTenantsResponse1) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal JSON data into GetTenantsResponse
	err = json.Unmarshal(data, &dst.GetTenantsResponse);
	if err == nil {
		jsonGetTenantsResponse, _ := json.Marshal(dst.GetTenantsResponse)
		if string(jsonGetTenantsResponse) == "{}" { // empty struct
			dst.GetTenantsResponse = nil
		} else {
			return nil // data stored in dst.GetTenantsResponse, return on the first match
		}
	} else {
		dst.GetTenantsResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetTenantsResponse1)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetTenantsResponse1) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.GetTenantsResponse != nil {
		return json.Marshal(&src.GetTenantsResponse)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableGetTenantsResponse1 struct {
	value *GetTenantsResponse1
	isSet bool
}

func (v NullableGetTenantsResponse1) Get() *GetTenantsResponse1 {
	return v.value
}

func (v *NullableGetTenantsResponse1) Set(val *GetTenantsResponse1) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTenantsResponse1) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTenantsResponse1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTenantsResponse1(val *GetTenantsResponse1) *NullableGetTenantsResponse1 {
	return &NullableGetTenantsResponse1{value: val, isSet: true}
}

func (v NullableGetTenantsResponse1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTenantsResponse1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


