/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChangeCommentPinStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChangeCommentPinStatusResponse{}

// ChangeCommentPinStatusResponse struct for ChangeCommentPinStatusResponse
type ChangeCommentPinStatusResponse struct {
	// Construct a type with a set of properties K of type T
	CommentPositions map[string]RecordStringBeforeStringOrNullAfterStringOrNullValue `json:"commentPositions"`
	Status ImportedAPIStatusSUCCESS `json:"status"`
}

type _ChangeCommentPinStatusResponse ChangeCommentPinStatusResponse

// NewChangeCommentPinStatusResponse instantiates a new ChangeCommentPinStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChangeCommentPinStatusResponse(commentPositions map[string]RecordStringBeforeStringOrNullAfterStringOrNullValue, status ImportedAPIStatusSUCCESS) *ChangeCommentPinStatusResponse {
	this := ChangeCommentPinStatusResponse{}
	this.CommentPositions = commentPositions
	this.Status = status
	return &this
}

// NewChangeCommentPinStatusResponseWithDefaults instantiates a new ChangeCommentPinStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangeCommentPinStatusResponseWithDefaults() *ChangeCommentPinStatusResponse {
	this := ChangeCommentPinStatusResponse{}
	return &this
}

// GetCommentPositions returns the CommentPositions field value
func (o *ChangeCommentPinStatusResponse) GetCommentPositions() map[string]RecordStringBeforeStringOrNullAfterStringOrNullValue {
	if o == nil {
		var ret map[string]RecordStringBeforeStringOrNullAfterStringOrNullValue
		return ret
	}

	return o.CommentPositions
}

// GetCommentPositionsOk returns a tuple with the CommentPositions field value
// and a boolean to check if the value has been set.
func (o *ChangeCommentPinStatusResponse) GetCommentPositionsOk() (*map[string]RecordStringBeforeStringOrNullAfterStringOrNullValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CommentPositions, true
}

// SetCommentPositions sets field value
func (o *ChangeCommentPinStatusResponse) SetCommentPositions(v map[string]RecordStringBeforeStringOrNullAfterStringOrNullValue) {
	o.CommentPositions = v
}

// GetStatus returns the Status field value
func (o *ChangeCommentPinStatusResponse) GetStatus() ImportedAPIStatusSUCCESS {
	if o == nil {
		var ret ImportedAPIStatusSUCCESS
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ChangeCommentPinStatusResponse) GetStatusOk() (*ImportedAPIStatusSUCCESS, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ChangeCommentPinStatusResponse) SetStatus(v ImportedAPIStatusSUCCESS) {
	o.Status = v
}

func (o ChangeCommentPinStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChangeCommentPinStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["commentPositions"] = o.CommentPositions
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *ChangeCommentPinStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"commentPositions",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChangeCommentPinStatusResponse := _ChangeCommentPinStatusResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChangeCommentPinStatusResponse)

	if err != nil {
		return err
	}

	*o = ChangeCommentPinStatusResponse(varChangeCommentPinStatusResponse)

	return err
}

type NullableChangeCommentPinStatusResponse struct {
	value *ChangeCommentPinStatusResponse
	isSet bool
}

func (v NullableChangeCommentPinStatusResponse) Get() *ChangeCommentPinStatusResponse {
	return v.value
}

func (v *NullableChangeCommentPinStatusResponse) Set(val *ChangeCommentPinStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableChangeCommentPinStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableChangeCommentPinStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangeCommentPinStatusResponse(val *ChangeCommentPinStatusResponse) *NullableChangeCommentPinStatusResponse {
	return &NullableChangeCommentPinStatusResponse{value: val, isSet: true}
}

func (v NullableChangeCommentPinStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangeCommentPinStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


