/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetEmailTemplatesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEmailTemplatesResponse{}

// GetEmailTemplatesResponse struct for GetEmailTemplatesResponse
type GetEmailTemplatesResponse struct {
	Status APIStatus `json:"status"`
	EmailTemplates []CustomEmailTemplate `json:"emailTemplates"`
}

type _GetEmailTemplatesResponse GetEmailTemplatesResponse

// NewGetEmailTemplatesResponse instantiates a new GetEmailTemplatesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEmailTemplatesResponse(status APIStatus, emailTemplates []CustomEmailTemplate) *GetEmailTemplatesResponse {
	this := GetEmailTemplatesResponse{}
	this.Status = status
	this.EmailTemplates = emailTemplates
	return &this
}

// NewGetEmailTemplatesResponseWithDefaults instantiates a new GetEmailTemplatesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEmailTemplatesResponseWithDefaults() *GetEmailTemplatesResponse {
	this := GetEmailTemplatesResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *GetEmailTemplatesResponse) GetStatus() APIStatus {
	if o == nil {
		var ret APIStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetEmailTemplatesResponse) GetStatusOk() (*APIStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetEmailTemplatesResponse) SetStatus(v APIStatus) {
	o.Status = v
}

// GetEmailTemplates returns the EmailTemplates field value
func (o *GetEmailTemplatesResponse) GetEmailTemplates() []CustomEmailTemplate {
	if o == nil {
		var ret []CustomEmailTemplate
		return ret
	}

	return o.EmailTemplates
}

// GetEmailTemplatesOk returns a tuple with the EmailTemplates field value
// and a boolean to check if the value has been set.
func (o *GetEmailTemplatesResponse) GetEmailTemplatesOk() ([]CustomEmailTemplate, bool) {
	if o == nil {
		return nil, false
	}
	return o.EmailTemplates, true
}

// SetEmailTemplates sets field value
func (o *GetEmailTemplatesResponse) SetEmailTemplates(v []CustomEmailTemplate) {
	o.EmailTemplates = v
}

func (o GetEmailTemplatesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEmailTemplatesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["emailTemplates"] = o.EmailTemplates
	return toSerialize, nil
}

func (o *GetEmailTemplatesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"emailTemplates",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetEmailTemplatesResponse := _GetEmailTemplatesResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetEmailTemplatesResponse)

	if err != nil {
		return err
	}

	*o = GetEmailTemplatesResponse(varGetEmailTemplatesResponse)

	return err
}

type NullableGetEmailTemplatesResponse struct {
	value *GetEmailTemplatesResponse
	isSet bool
}

func (v NullableGetEmailTemplatesResponse) Get() *GetEmailTemplatesResponse {
	return v.value
}

func (v *NullableGetEmailTemplatesResponse) Set(val *GetEmailTemplatesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEmailTemplatesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEmailTemplatesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEmailTemplatesResponse(val *GetEmailTemplatesResponse) *NullableGetEmailTemplatesResponse {
	return &NullableGetEmailTemplatesResponse{value: val, isSet: true}
}

func (v NullableGetEmailTemplatesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEmailTemplatesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


