/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CustomEmailTemplate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomEmailTemplate{}

// CustomEmailTemplate struct for CustomEmailTemplate
type CustomEmailTemplate struct {
	Id string `json:"_id"`
	TenantId string `json:"tenantId"`
	EmailTemplateId string `json:"emailTemplateId"`
	DisplayName string `json:"displayName"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt NullableTime `json:"updatedAt"`
	UpdatedByUserId NullableString `json:"updatedByUserId"`
	Domain NullableString `json:"domain,omitempty"`
	Ejs string `json:"ejs"`
	// Construct a type with a set of properties K of type T
	TranslationOverridesByLocale map[string]map[string]string `json:"translationOverridesByLocale"`
	TestData interface{} `json:"testData"`
}

type _CustomEmailTemplate CustomEmailTemplate

// NewCustomEmailTemplate instantiates a new CustomEmailTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomEmailTemplate(id string, tenantId string, emailTemplateId string, displayName string, createdAt time.Time, updatedAt NullableTime, updatedByUserId NullableString, ejs string, translationOverridesByLocale map[string]map[string]string, testData interface{}) *CustomEmailTemplate {
	this := CustomEmailTemplate{}
	this.Id = id
	this.TenantId = tenantId
	this.EmailTemplateId = emailTemplateId
	this.DisplayName = displayName
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.UpdatedByUserId = updatedByUserId
	this.Ejs = ejs
	this.TranslationOverridesByLocale = translationOverridesByLocale
	this.TestData = testData
	return &this
}

// NewCustomEmailTemplateWithDefaults instantiates a new CustomEmailTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomEmailTemplateWithDefaults() *CustomEmailTemplate {
	this := CustomEmailTemplate{}
	return &this
}

// GetId returns the Id field value
func (o *CustomEmailTemplate) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CustomEmailTemplate) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CustomEmailTemplate) SetId(v string) {
	o.Id = v
}

// GetTenantId returns the TenantId field value
func (o *CustomEmailTemplate) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *CustomEmailTemplate) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *CustomEmailTemplate) SetTenantId(v string) {
	o.TenantId = v
}

// GetEmailTemplateId returns the EmailTemplateId field value
func (o *CustomEmailTemplate) GetEmailTemplateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EmailTemplateId
}

// GetEmailTemplateIdOk returns a tuple with the EmailTemplateId field value
// and a boolean to check if the value has been set.
func (o *CustomEmailTemplate) GetEmailTemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmailTemplateId, true
}

// SetEmailTemplateId sets field value
func (o *CustomEmailTemplate) SetEmailTemplateId(v string) {
	o.EmailTemplateId = v
}

// GetDisplayName returns the DisplayName field value
func (o *CustomEmailTemplate) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *CustomEmailTemplate) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *CustomEmailTemplate) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CustomEmailTemplate) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CustomEmailTemplate) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CustomEmailTemplate) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *CustomEmailTemplate) GetUpdatedAt() time.Time {
	if o == nil || o.UpdatedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomEmailTemplate) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// SetUpdatedAt sets field value
func (o *CustomEmailTemplate) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}

// GetUpdatedByUserId returns the UpdatedByUserId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CustomEmailTemplate) GetUpdatedByUserId() string {
	if o == nil || o.UpdatedByUserId.Get() == nil {
		var ret string
		return ret
	}

	return *o.UpdatedByUserId.Get()
}

// GetUpdatedByUserIdOk returns a tuple with the UpdatedByUserId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomEmailTemplate) GetUpdatedByUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedByUserId.Get(), o.UpdatedByUserId.IsSet()
}

// SetUpdatedByUserId sets field value
func (o *CustomEmailTemplate) SetUpdatedByUserId(v string) {
	o.UpdatedByUserId.Set(&v)
}

// GetDomain returns the Domain field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomEmailTemplate) GetDomain() string {
	if o == nil || IsNil(o.Domain.Get()) {
		var ret string
		return ret
	}
	return *o.Domain.Get()
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomEmailTemplate) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Domain.Get(), o.Domain.IsSet()
}

// HasDomain returns a boolean if a field has been set.
func (o *CustomEmailTemplate) HasDomain() bool {
	if o != nil && o.Domain.IsSet() {
		return true
	}

	return false
}

// SetDomain gets a reference to the given NullableString and assigns it to the Domain field.
func (o *CustomEmailTemplate) SetDomain(v string) {
	o.Domain.Set(&v)
}
// SetDomainNil sets the value for Domain to be an explicit nil
func (o *CustomEmailTemplate) SetDomainNil() {
	o.Domain.Set(nil)
}

// UnsetDomain ensures that no value is present for Domain, not even an explicit nil
func (o *CustomEmailTemplate) UnsetDomain() {
	o.Domain.Unset()
}

// GetEjs returns the Ejs field value
func (o *CustomEmailTemplate) GetEjs() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ejs
}

// GetEjsOk returns a tuple with the Ejs field value
// and a boolean to check if the value has been set.
func (o *CustomEmailTemplate) GetEjsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ejs, true
}

// SetEjs sets field value
func (o *CustomEmailTemplate) SetEjs(v string) {
	o.Ejs = v
}

// GetTranslationOverridesByLocale returns the TranslationOverridesByLocale field value
func (o *CustomEmailTemplate) GetTranslationOverridesByLocale() map[string]map[string]string {
	if o == nil {
		var ret map[string]map[string]string
		return ret
	}

	return o.TranslationOverridesByLocale
}

// GetTranslationOverridesByLocaleOk returns a tuple with the TranslationOverridesByLocale field value
// and a boolean to check if the value has been set.
func (o *CustomEmailTemplate) GetTranslationOverridesByLocaleOk() (*map[string]map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TranslationOverridesByLocale, true
}

// SetTranslationOverridesByLocale sets field value
func (o *CustomEmailTemplate) SetTranslationOverridesByLocale(v map[string]map[string]string) {
	o.TranslationOverridesByLocale = v
}

// GetTestData returns the TestData field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *CustomEmailTemplate) GetTestData() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.TestData
}

// GetTestDataOk returns a tuple with the TestData field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomEmailTemplate) GetTestDataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.TestData) {
		return nil, false
	}
	return &o.TestData, true
}

// SetTestData sets field value
func (o *CustomEmailTemplate) SetTestData(v interface{}) {
	o.TestData = v
}

func (o CustomEmailTemplate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomEmailTemplate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["_id"] = o.Id
	toSerialize["tenantId"] = o.TenantId
	toSerialize["emailTemplateId"] = o.EmailTemplateId
	toSerialize["displayName"] = o.DisplayName
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt.Get()
	toSerialize["updatedByUserId"] = o.UpdatedByUserId.Get()
	if o.Domain.IsSet() {
		toSerialize["domain"] = o.Domain.Get()
	}
	toSerialize["ejs"] = o.Ejs
	toSerialize["translationOverridesByLocale"] = o.TranslationOverridesByLocale
	if o.TestData != nil {
		toSerialize["testData"] = o.TestData
	}
	return toSerialize, nil
}

func (o *CustomEmailTemplate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"_id",
		"tenantId",
		"emailTemplateId",
		"displayName",
		"createdAt",
		"updatedAt",
		"updatedByUserId",
		"ejs",
		"translationOverridesByLocale",
		"testData",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomEmailTemplate := _CustomEmailTemplate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCustomEmailTemplate)

	if err != nil {
		return err
	}

	*o = CustomEmailTemplate(varCustomEmailTemplate)

	return err
}

type NullableCustomEmailTemplate struct {
	value *CustomEmailTemplate
	isSet bool
}

func (v NullableCustomEmailTemplate) Get() *CustomEmailTemplate {
	return v.value
}

func (v *NullableCustomEmailTemplate) Set(val *CustomEmailTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomEmailTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomEmailTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomEmailTemplate(val *CustomEmailTemplate) *NullableCustomEmailTemplate {
	return &NullableCustomEmailTemplate{value: val, isSet: true}
}

func (v NullableCustomEmailTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomEmailTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


