/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CommentTextUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommentTextUpdateRequest{}

// CommentTextUpdateRequest struct for CommentTextUpdateRequest
type CommentTextUpdateRequest struct {
	Comment string `json:"comment"`
	Mentions []CommentUserMentionInfo `json:"mentions,omitempty"`
	HashTags []CommentUserHashTagInfo `json:"hashTags,omitempty"`
}

type _CommentTextUpdateRequest CommentTextUpdateRequest

// NewCommentTextUpdateRequest instantiates a new CommentTextUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommentTextUpdateRequest(comment string) *CommentTextUpdateRequest {
	this := CommentTextUpdateRequest{}
	this.Comment = comment
	return &this
}

// NewCommentTextUpdateRequestWithDefaults instantiates a new CommentTextUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommentTextUpdateRequestWithDefaults() *CommentTextUpdateRequest {
	this := CommentTextUpdateRequest{}
	return &this
}

// GetComment returns the Comment field value
func (o *CommentTextUpdateRequest) GetComment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Comment
}

// GetCommentOk returns a tuple with the Comment field value
// and a boolean to check if the value has been set.
func (o *CommentTextUpdateRequest) GetCommentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Comment, true
}

// SetComment sets field value
func (o *CommentTextUpdateRequest) SetComment(v string) {
	o.Comment = v
}

// GetMentions returns the Mentions field value if set, zero value otherwise.
func (o *CommentTextUpdateRequest) GetMentions() []CommentUserMentionInfo {
	if o == nil || IsNil(o.Mentions) {
		var ret []CommentUserMentionInfo
		return ret
	}
	return o.Mentions
}

// GetMentionsOk returns a tuple with the Mentions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentTextUpdateRequest) GetMentionsOk() ([]CommentUserMentionInfo, bool) {
	if o == nil || IsNil(o.Mentions) {
		return nil, false
	}
	return o.Mentions, true
}

// HasMentions returns a boolean if a field has been set.
func (o *CommentTextUpdateRequest) HasMentions() bool {
	if o != nil && !IsNil(o.Mentions) {
		return true
	}

	return false
}

// SetMentions gets a reference to the given []CommentUserMentionInfo and assigns it to the Mentions field.
func (o *CommentTextUpdateRequest) SetMentions(v []CommentUserMentionInfo) {
	o.Mentions = v
}

// GetHashTags returns the HashTags field value if set, zero value otherwise.
func (o *CommentTextUpdateRequest) GetHashTags() []CommentUserHashTagInfo {
	if o == nil || IsNil(o.HashTags) {
		var ret []CommentUserHashTagInfo
		return ret
	}
	return o.HashTags
}

// GetHashTagsOk returns a tuple with the HashTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentTextUpdateRequest) GetHashTagsOk() ([]CommentUserHashTagInfo, bool) {
	if o == nil || IsNil(o.HashTags) {
		return nil, false
	}
	return o.HashTags, true
}

// HasHashTags returns a boolean if a field has been set.
func (o *CommentTextUpdateRequest) HasHashTags() bool {
	if o != nil && !IsNil(o.HashTags) {
		return true
	}

	return false
}

// SetHashTags gets a reference to the given []CommentUserHashTagInfo and assigns it to the HashTags field.
func (o *CommentTextUpdateRequest) SetHashTags(v []CommentUserHashTagInfo) {
	o.HashTags = v
}

func (o CommentTextUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommentTextUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["comment"] = o.Comment
	if !IsNil(o.Mentions) {
		toSerialize["mentions"] = o.Mentions
	}
	if !IsNil(o.HashTags) {
		toSerialize["hashTags"] = o.HashTags
	}
	return toSerialize, nil
}

func (o *CommentTextUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"comment",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommentTextUpdateRequest := _CommentTextUpdateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCommentTextUpdateRequest)

	if err != nil {
		return err
	}

	*o = CommentTextUpdateRequest(varCommentTextUpdateRequest)

	return err
}

type NullableCommentTextUpdateRequest struct {
	value *CommentTextUpdateRequest
	isSet bool
}

func (v NullableCommentTextUpdateRequest) Get() *CommentTextUpdateRequest {
	return v.value
}

func (v *NullableCommentTextUpdateRequest) Set(val *CommentTextUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCommentTextUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCommentTextUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommentTextUpdateRequest(val *CommentTextUpdateRequest) *NullableCommentTextUpdateRequest {
	return &NullableCommentTextUpdateRequest{value: val, isSet: true}
}

func (v NullableCommentTextUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommentTextUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


