/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// ImportedAPIStatusFAILED the model 'ImportedAPIStatusFAILED'
type ImportedAPIStatusFAILED string

// List of ImportedAPIStatus.FAILED
const (
	IMPORTEDAPISTATUSFAILED_FAILED ImportedAPIStatusFAILED = "failed"
)

// All allowed values of ImportedAPIStatusFAILED enum
var AllowedImportedAPIStatusFAILEDEnumValues = []ImportedAPIStatusFAILED{
	"failed",
}

func (v *ImportedAPIStatusFAILED) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ImportedAPIStatusFAILED(value)
	for _, existing := range AllowedImportedAPIStatusFAILEDEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ImportedAPIStatusFAILED", value)
}

// NewImportedAPIStatusFAILEDFromValue returns a pointer to a valid ImportedAPIStatusFAILED
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewImportedAPIStatusFAILEDFromValue(v string) (*ImportedAPIStatusFAILED, error) {
	ev := ImportedAPIStatusFAILED(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ImportedAPIStatusFAILED: valid values are %v", v, AllowedImportedAPIStatusFAILEDEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ImportedAPIStatusFAILED) IsValid() bool {
	for _, existing := range AllowedImportedAPIStatusFAILEDEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ImportedAPIStatus.FAILED value
func (v ImportedAPIStatusFAILED) Ptr() *ImportedAPIStatusFAILED {
	return &v
}

type NullableImportedAPIStatusFAILED struct {
	value *ImportedAPIStatusFAILED
	isSet bool
}

func (v NullableImportedAPIStatusFAILED) Get() *ImportedAPIStatusFAILED {
	return v.value
}

func (v *NullableImportedAPIStatusFAILED) Set(val *ImportedAPIStatusFAILED) {
	v.value = val
	v.isSet = true
}

func (v NullableImportedAPIStatusFAILED) IsSet() bool {
	return v.isSet
}

func (v *NullableImportedAPIStatusFAILED) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImportedAPIStatusFAILED(val *ImportedAPIStatusFAILED) *NullableImportedAPIStatusFAILED {
	return &NullableImportedAPIStatusFAILED{value: val, isSet: true}
}

func (v NullableImportedAPIStatusFAILED) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImportedAPIStatusFAILED) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

