/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the PubSubCommentBase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PubSubCommentBase{}

// PubSubCommentBase struct for PubSubCommentBase
type PubSubCommentBase struct {
	Id string `json:"_id"`
	TenantId string `json:"tenantId"`
	UserId NullableString `json:"userId,omitempty"`
	UrlId string `json:"urlId"`
	CommenterName string `json:"commenterName"`
	CommenterLink NullableString `json:"commenterLink,omitempty"`
	CommentHTML string `json:"commentHTML"`
	Comment string `json:"comment"`
	ParentId NullableString `json:"parentId,omitempty"`
	Votes NullableInt32 `json:"votes,omitempty"`
	VotesUp NullableInt32 `json:"votesUp,omitempty"`
	VotesDown NullableInt32 `json:"votesDown,omitempty"`
	Verified bool `json:"verified"`
	AvatarSrc NullableString `json:"avatarSrc,omitempty"`
	HasImages *bool `json:"hasImages,omitempty"`
	HasLinks *bool `json:"hasLinks,omitempty"`
	IsByAdmin *bool `json:"isByAdmin,omitempty"`
	IsByModerator *bool `json:"isByModerator,omitempty"`
	IsPinned NullableBool `json:"isPinned,omitempty"`
	IsLocked NullableBool `json:"isLocked,omitempty"`
	DisplayLabel NullableString `json:"displayLabel,omitempty"`
	Rating NullableFloat64 `json:"rating,omitempty"`
	Badges []CommentUserBadgeInfo `json:"badges,omitempty"`
	ViewCount NullableInt64 `json:"viewCount,omitempty"`
	IsDeleted *bool `json:"isDeleted,omitempty"`
	IsDeletedUser *bool `json:"isDeletedUser,omitempty"`
	IsSpam *bool `json:"isSpam,omitempty"`
	AnonUserId NullableString `json:"anonUserId,omitempty"`
	FeedbackIds []string `json:"feedbackIds,omitempty"`
	FlagCount NullableInt32 `json:"flagCount,omitempty"`
	Domain NullableString `json:"domain,omitempty"`
	Url string `json:"url"`
	PageTitle NullableString `json:"pageTitle,omitempty"`
	ExpireAt NullableTime `json:"expireAt,omitempty"`
	Reviewed *bool `json:"reviewed,omitempty"`
	HasCode *bool `json:"hasCode,omitempty"`
	Approved bool `json:"approved"`
	Locale NullableString `json:"locale"`
	IsBannedUser *bool `json:"isBannedUser,omitempty"`
	GroupIds []string `json:"groupIds,omitempty"`
}

type _PubSubCommentBase PubSubCommentBase

// NewPubSubCommentBase instantiates a new PubSubCommentBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPubSubCommentBase(id string, tenantId string, urlId string, commenterName string, commentHTML string, comment string, verified bool, url string, approved bool, locale NullableString) *PubSubCommentBase {
	this := PubSubCommentBase{}
	this.Id = id
	this.TenantId = tenantId
	this.UrlId = urlId
	this.CommenterName = commenterName
	this.CommentHTML = commentHTML
	this.Comment = comment
	this.Verified = verified
	this.Url = url
	this.Approved = approved
	this.Locale = locale
	return &this
}

// NewPubSubCommentBaseWithDefaults instantiates a new PubSubCommentBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPubSubCommentBaseWithDefaults() *PubSubCommentBase {
	this := PubSubCommentBase{}
	return &this
}

// GetId returns the Id field value
func (o *PubSubCommentBase) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PubSubCommentBase) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PubSubCommentBase) SetId(v string) {
	o.Id = v
}

// GetTenantId returns the TenantId field value
func (o *PubSubCommentBase) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *PubSubCommentBase) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *PubSubCommentBase) SetTenantId(v string) {
	o.TenantId = v
}

// GetUserId returns the UserId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PubSubCommentBase) GetUserId() string {
	if o == nil || IsNil(o.UserId.Get()) {
		var ret string
		return ret
	}
	return *o.UserId.Get()
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PubSubCommentBase) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserId.Get(), o.UserId.IsSet()
}

// HasUserId returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasUserId() bool {
	if o != nil && o.UserId.IsSet() {
		return true
	}

	return false
}

// SetUserId gets a reference to the given NullableString and assigns it to the UserId field.
func (o *PubSubCommentBase) SetUserId(v string) {
	o.UserId.Set(&v)
}
// SetUserIdNil sets the value for UserId to be an explicit nil
func (o *PubSubCommentBase) SetUserIdNil() {
	o.UserId.Set(nil)
}

// UnsetUserId ensures that no value is present for UserId, not even an explicit nil
func (o *PubSubCommentBase) UnsetUserId() {
	o.UserId.Unset()
}

// GetUrlId returns the UrlId field value
func (o *PubSubCommentBase) GetUrlId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UrlId
}

// GetUrlIdOk returns a tuple with the UrlId field value
// and a boolean to check if the value has been set.
func (o *PubSubCommentBase) GetUrlIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UrlId, true
}

// SetUrlId sets field value
func (o *PubSubCommentBase) SetUrlId(v string) {
	o.UrlId = v
}

// GetCommenterName returns the CommenterName field value
func (o *PubSubCommentBase) GetCommenterName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CommenterName
}

// GetCommenterNameOk returns a tuple with the CommenterName field value
// and a boolean to check if the value has been set.
func (o *PubSubCommentBase) GetCommenterNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CommenterName, true
}

// SetCommenterName sets field value
func (o *PubSubCommentBase) SetCommenterName(v string) {
	o.CommenterName = v
}

// GetCommenterLink returns the CommenterLink field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PubSubCommentBase) GetCommenterLink() string {
	if o == nil || IsNil(o.CommenterLink.Get()) {
		var ret string
		return ret
	}
	return *o.CommenterLink.Get()
}

// GetCommenterLinkOk returns a tuple with the CommenterLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PubSubCommentBase) GetCommenterLinkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CommenterLink.Get(), o.CommenterLink.IsSet()
}

// HasCommenterLink returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasCommenterLink() bool {
	if o != nil && o.CommenterLink.IsSet() {
		return true
	}

	return false
}

// SetCommenterLink gets a reference to the given NullableString and assigns it to the CommenterLink field.
func (o *PubSubCommentBase) SetCommenterLink(v string) {
	o.CommenterLink.Set(&v)
}
// SetCommenterLinkNil sets the value for CommenterLink to be an explicit nil
func (o *PubSubCommentBase) SetCommenterLinkNil() {
	o.CommenterLink.Set(nil)
}

// UnsetCommenterLink ensures that no value is present for CommenterLink, not even an explicit nil
func (o *PubSubCommentBase) UnsetCommenterLink() {
	o.CommenterLink.Unset()
}

// GetCommentHTML returns the CommentHTML field value
func (o *PubSubCommentBase) GetCommentHTML() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CommentHTML
}

// GetCommentHTMLOk returns a tuple with the CommentHTML field value
// and a boolean to check if the value has been set.
func (o *PubSubCommentBase) GetCommentHTMLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CommentHTML, true
}

// SetCommentHTML sets field value
func (o *PubSubCommentBase) SetCommentHTML(v string) {
	o.CommentHTML = v
}

// GetComment returns the Comment field value
func (o *PubSubCommentBase) GetComment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Comment
}

// GetCommentOk returns a tuple with the Comment field value
// and a boolean to check if the value has been set.
func (o *PubSubCommentBase) GetCommentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Comment, true
}

// SetComment sets field value
func (o *PubSubCommentBase) SetComment(v string) {
	o.Comment = v
}

// GetParentId returns the ParentId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PubSubCommentBase) GetParentId() string {
	if o == nil || IsNil(o.ParentId.Get()) {
		var ret string
		return ret
	}
	return *o.ParentId.Get()
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PubSubCommentBase) GetParentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentId.Get(), o.ParentId.IsSet()
}

// HasParentId returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasParentId() bool {
	if o != nil && o.ParentId.IsSet() {
		return true
	}

	return false
}

// SetParentId gets a reference to the given NullableString and assigns it to the ParentId field.
func (o *PubSubCommentBase) SetParentId(v string) {
	o.ParentId.Set(&v)
}
// SetParentIdNil sets the value for ParentId to be an explicit nil
func (o *PubSubCommentBase) SetParentIdNil() {
	o.ParentId.Set(nil)
}

// UnsetParentId ensures that no value is present for ParentId, not even an explicit nil
func (o *PubSubCommentBase) UnsetParentId() {
	o.ParentId.Unset()
}

// GetVotes returns the Votes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PubSubCommentBase) GetVotes() int32 {
	if o == nil || IsNil(o.Votes.Get()) {
		var ret int32
		return ret
	}
	return *o.Votes.Get()
}

// GetVotesOk returns a tuple with the Votes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PubSubCommentBase) GetVotesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Votes.Get(), o.Votes.IsSet()
}

// HasVotes returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasVotes() bool {
	if o != nil && o.Votes.IsSet() {
		return true
	}

	return false
}

// SetVotes gets a reference to the given NullableInt32 and assigns it to the Votes field.
func (o *PubSubCommentBase) SetVotes(v int32) {
	o.Votes.Set(&v)
}
// SetVotesNil sets the value for Votes to be an explicit nil
func (o *PubSubCommentBase) SetVotesNil() {
	o.Votes.Set(nil)
}

// UnsetVotes ensures that no value is present for Votes, not even an explicit nil
func (o *PubSubCommentBase) UnsetVotes() {
	o.Votes.Unset()
}

// GetVotesUp returns the VotesUp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PubSubCommentBase) GetVotesUp() int32 {
	if o == nil || IsNil(o.VotesUp.Get()) {
		var ret int32
		return ret
	}
	return *o.VotesUp.Get()
}

// GetVotesUpOk returns a tuple with the VotesUp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PubSubCommentBase) GetVotesUpOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.VotesUp.Get(), o.VotesUp.IsSet()
}

// HasVotesUp returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasVotesUp() bool {
	if o != nil && o.VotesUp.IsSet() {
		return true
	}

	return false
}

// SetVotesUp gets a reference to the given NullableInt32 and assigns it to the VotesUp field.
func (o *PubSubCommentBase) SetVotesUp(v int32) {
	o.VotesUp.Set(&v)
}
// SetVotesUpNil sets the value for VotesUp to be an explicit nil
func (o *PubSubCommentBase) SetVotesUpNil() {
	o.VotesUp.Set(nil)
}

// UnsetVotesUp ensures that no value is present for VotesUp, not even an explicit nil
func (o *PubSubCommentBase) UnsetVotesUp() {
	o.VotesUp.Unset()
}

// GetVotesDown returns the VotesDown field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PubSubCommentBase) GetVotesDown() int32 {
	if o == nil || IsNil(o.VotesDown.Get()) {
		var ret int32
		return ret
	}
	return *o.VotesDown.Get()
}

// GetVotesDownOk returns a tuple with the VotesDown field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PubSubCommentBase) GetVotesDownOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.VotesDown.Get(), o.VotesDown.IsSet()
}

// HasVotesDown returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasVotesDown() bool {
	if o != nil && o.VotesDown.IsSet() {
		return true
	}

	return false
}

// SetVotesDown gets a reference to the given NullableInt32 and assigns it to the VotesDown field.
func (o *PubSubCommentBase) SetVotesDown(v int32) {
	o.VotesDown.Set(&v)
}
// SetVotesDownNil sets the value for VotesDown to be an explicit nil
func (o *PubSubCommentBase) SetVotesDownNil() {
	o.VotesDown.Set(nil)
}

// UnsetVotesDown ensures that no value is present for VotesDown, not even an explicit nil
func (o *PubSubCommentBase) UnsetVotesDown() {
	o.VotesDown.Unset()
}

// GetVerified returns the Verified field value
func (o *PubSubCommentBase) GetVerified() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Verified
}

// GetVerifiedOk returns a tuple with the Verified field value
// and a boolean to check if the value has been set.
func (o *PubSubCommentBase) GetVerifiedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Verified, true
}

// SetVerified sets field value
func (o *PubSubCommentBase) SetVerified(v bool) {
	o.Verified = v
}

// GetAvatarSrc returns the AvatarSrc field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PubSubCommentBase) GetAvatarSrc() string {
	if o == nil || IsNil(o.AvatarSrc.Get()) {
		var ret string
		return ret
	}
	return *o.AvatarSrc.Get()
}

// GetAvatarSrcOk returns a tuple with the AvatarSrc field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PubSubCommentBase) GetAvatarSrcOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AvatarSrc.Get(), o.AvatarSrc.IsSet()
}

// HasAvatarSrc returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasAvatarSrc() bool {
	if o != nil && o.AvatarSrc.IsSet() {
		return true
	}

	return false
}

// SetAvatarSrc gets a reference to the given NullableString and assigns it to the AvatarSrc field.
func (o *PubSubCommentBase) SetAvatarSrc(v string) {
	o.AvatarSrc.Set(&v)
}
// SetAvatarSrcNil sets the value for AvatarSrc to be an explicit nil
func (o *PubSubCommentBase) SetAvatarSrcNil() {
	o.AvatarSrc.Set(nil)
}

// UnsetAvatarSrc ensures that no value is present for AvatarSrc, not even an explicit nil
func (o *PubSubCommentBase) UnsetAvatarSrc() {
	o.AvatarSrc.Unset()
}

// GetHasImages returns the HasImages field value if set, zero value otherwise.
func (o *PubSubCommentBase) GetHasImages() bool {
	if o == nil || IsNil(o.HasImages) {
		var ret bool
		return ret
	}
	return *o.HasImages
}

// GetHasImagesOk returns a tuple with the HasImages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PubSubCommentBase) GetHasImagesOk() (*bool, bool) {
	if o == nil || IsNil(o.HasImages) {
		return nil, false
	}
	return o.HasImages, true
}

// HasHasImages returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasHasImages() bool {
	if o != nil && !IsNil(o.HasImages) {
		return true
	}

	return false
}

// SetHasImages gets a reference to the given bool and assigns it to the HasImages field.
func (o *PubSubCommentBase) SetHasImages(v bool) {
	o.HasImages = &v
}

// GetHasLinks returns the HasLinks field value if set, zero value otherwise.
func (o *PubSubCommentBase) GetHasLinks() bool {
	if o == nil || IsNil(o.HasLinks) {
		var ret bool
		return ret
	}
	return *o.HasLinks
}

// GetHasLinksOk returns a tuple with the HasLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PubSubCommentBase) GetHasLinksOk() (*bool, bool) {
	if o == nil || IsNil(o.HasLinks) {
		return nil, false
	}
	return o.HasLinks, true
}

// HasHasLinks returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasHasLinks() bool {
	if o != nil && !IsNil(o.HasLinks) {
		return true
	}

	return false
}

// SetHasLinks gets a reference to the given bool and assigns it to the HasLinks field.
func (o *PubSubCommentBase) SetHasLinks(v bool) {
	o.HasLinks = &v
}

// GetIsByAdmin returns the IsByAdmin field value if set, zero value otherwise.
func (o *PubSubCommentBase) GetIsByAdmin() bool {
	if o == nil || IsNil(o.IsByAdmin) {
		var ret bool
		return ret
	}
	return *o.IsByAdmin
}

// GetIsByAdminOk returns a tuple with the IsByAdmin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PubSubCommentBase) GetIsByAdminOk() (*bool, bool) {
	if o == nil || IsNil(o.IsByAdmin) {
		return nil, false
	}
	return o.IsByAdmin, true
}

// HasIsByAdmin returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasIsByAdmin() bool {
	if o != nil && !IsNil(o.IsByAdmin) {
		return true
	}

	return false
}

// SetIsByAdmin gets a reference to the given bool and assigns it to the IsByAdmin field.
func (o *PubSubCommentBase) SetIsByAdmin(v bool) {
	o.IsByAdmin = &v
}

// GetIsByModerator returns the IsByModerator field value if set, zero value otherwise.
func (o *PubSubCommentBase) GetIsByModerator() bool {
	if o == nil || IsNil(o.IsByModerator) {
		var ret bool
		return ret
	}
	return *o.IsByModerator
}

// GetIsByModeratorOk returns a tuple with the IsByModerator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PubSubCommentBase) GetIsByModeratorOk() (*bool, bool) {
	if o == nil || IsNil(o.IsByModerator) {
		return nil, false
	}
	return o.IsByModerator, true
}

// HasIsByModerator returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasIsByModerator() bool {
	if o != nil && !IsNil(o.IsByModerator) {
		return true
	}

	return false
}

// SetIsByModerator gets a reference to the given bool and assigns it to the IsByModerator field.
func (o *PubSubCommentBase) SetIsByModerator(v bool) {
	o.IsByModerator = &v
}

// GetIsPinned returns the IsPinned field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PubSubCommentBase) GetIsPinned() bool {
	if o == nil || IsNil(o.IsPinned.Get()) {
		var ret bool
		return ret
	}
	return *o.IsPinned.Get()
}

// GetIsPinnedOk returns a tuple with the IsPinned field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PubSubCommentBase) GetIsPinnedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsPinned.Get(), o.IsPinned.IsSet()
}

// HasIsPinned returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasIsPinned() bool {
	if o != nil && o.IsPinned.IsSet() {
		return true
	}

	return false
}

// SetIsPinned gets a reference to the given NullableBool and assigns it to the IsPinned field.
func (o *PubSubCommentBase) SetIsPinned(v bool) {
	o.IsPinned.Set(&v)
}
// SetIsPinnedNil sets the value for IsPinned to be an explicit nil
func (o *PubSubCommentBase) SetIsPinnedNil() {
	o.IsPinned.Set(nil)
}

// UnsetIsPinned ensures that no value is present for IsPinned, not even an explicit nil
func (o *PubSubCommentBase) UnsetIsPinned() {
	o.IsPinned.Unset()
}

// GetIsLocked returns the IsLocked field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PubSubCommentBase) GetIsLocked() bool {
	if o == nil || IsNil(o.IsLocked.Get()) {
		var ret bool
		return ret
	}
	return *o.IsLocked.Get()
}

// GetIsLockedOk returns a tuple with the IsLocked field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PubSubCommentBase) GetIsLockedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsLocked.Get(), o.IsLocked.IsSet()
}

// HasIsLocked returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasIsLocked() bool {
	if o != nil && o.IsLocked.IsSet() {
		return true
	}

	return false
}

// SetIsLocked gets a reference to the given NullableBool and assigns it to the IsLocked field.
func (o *PubSubCommentBase) SetIsLocked(v bool) {
	o.IsLocked.Set(&v)
}
// SetIsLockedNil sets the value for IsLocked to be an explicit nil
func (o *PubSubCommentBase) SetIsLockedNil() {
	o.IsLocked.Set(nil)
}

// UnsetIsLocked ensures that no value is present for IsLocked, not even an explicit nil
func (o *PubSubCommentBase) UnsetIsLocked() {
	o.IsLocked.Unset()
}

// GetDisplayLabel returns the DisplayLabel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PubSubCommentBase) GetDisplayLabel() string {
	if o == nil || IsNil(o.DisplayLabel.Get()) {
		var ret string
		return ret
	}
	return *o.DisplayLabel.Get()
}

// GetDisplayLabelOk returns a tuple with the DisplayLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PubSubCommentBase) GetDisplayLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DisplayLabel.Get(), o.DisplayLabel.IsSet()
}

// HasDisplayLabel returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasDisplayLabel() bool {
	if o != nil && o.DisplayLabel.IsSet() {
		return true
	}

	return false
}

// SetDisplayLabel gets a reference to the given NullableString and assigns it to the DisplayLabel field.
func (o *PubSubCommentBase) SetDisplayLabel(v string) {
	o.DisplayLabel.Set(&v)
}
// SetDisplayLabelNil sets the value for DisplayLabel to be an explicit nil
func (o *PubSubCommentBase) SetDisplayLabelNil() {
	o.DisplayLabel.Set(nil)
}

// UnsetDisplayLabel ensures that no value is present for DisplayLabel, not even an explicit nil
func (o *PubSubCommentBase) UnsetDisplayLabel() {
	o.DisplayLabel.Unset()
}

// GetRating returns the Rating field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PubSubCommentBase) GetRating() float64 {
	if o == nil || IsNil(o.Rating.Get()) {
		var ret float64
		return ret
	}
	return *o.Rating.Get()
}

// GetRatingOk returns a tuple with the Rating field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PubSubCommentBase) GetRatingOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rating.Get(), o.Rating.IsSet()
}

// HasRating returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasRating() bool {
	if o != nil && o.Rating.IsSet() {
		return true
	}

	return false
}

// SetRating gets a reference to the given NullableFloat64 and assigns it to the Rating field.
func (o *PubSubCommentBase) SetRating(v float64) {
	o.Rating.Set(&v)
}
// SetRatingNil sets the value for Rating to be an explicit nil
func (o *PubSubCommentBase) SetRatingNil() {
	o.Rating.Set(nil)
}

// UnsetRating ensures that no value is present for Rating, not even an explicit nil
func (o *PubSubCommentBase) UnsetRating() {
	o.Rating.Unset()
}

// GetBadges returns the Badges field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PubSubCommentBase) GetBadges() []CommentUserBadgeInfo {
	if o == nil {
		var ret []CommentUserBadgeInfo
		return ret
	}
	return o.Badges
}

// GetBadgesOk returns a tuple with the Badges field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PubSubCommentBase) GetBadgesOk() ([]CommentUserBadgeInfo, bool) {
	if o == nil || IsNil(o.Badges) {
		return nil, false
	}
	return o.Badges, true
}

// HasBadges returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasBadges() bool {
	if o != nil && !IsNil(o.Badges) {
		return true
	}

	return false
}

// SetBadges gets a reference to the given []CommentUserBadgeInfo and assigns it to the Badges field.
func (o *PubSubCommentBase) SetBadges(v []CommentUserBadgeInfo) {
	o.Badges = v
}

// GetViewCount returns the ViewCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PubSubCommentBase) GetViewCount() int64 {
	if o == nil || IsNil(o.ViewCount.Get()) {
		var ret int64
		return ret
	}
	return *o.ViewCount.Get()
}

// GetViewCountOk returns a tuple with the ViewCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PubSubCommentBase) GetViewCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ViewCount.Get(), o.ViewCount.IsSet()
}

// HasViewCount returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasViewCount() bool {
	if o != nil && o.ViewCount.IsSet() {
		return true
	}

	return false
}

// SetViewCount gets a reference to the given NullableInt64 and assigns it to the ViewCount field.
func (o *PubSubCommentBase) SetViewCount(v int64) {
	o.ViewCount.Set(&v)
}
// SetViewCountNil sets the value for ViewCount to be an explicit nil
func (o *PubSubCommentBase) SetViewCountNil() {
	o.ViewCount.Set(nil)
}

// UnsetViewCount ensures that no value is present for ViewCount, not even an explicit nil
func (o *PubSubCommentBase) UnsetViewCount() {
	o.ViewCount.Unset()
}

// GetIsDeleted returns the IsDeleted field value if set, zero value otherwise.
func (o *PubSubCommentBase) GetIsDeleted() bool {
	if o == nil || IsNil(o.IsDeleted) {
		var ret bool
		return ret
	}
	return *o.IsDeleted
}

// GetIsDeletedOk returns a tuple with the IsDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PubSubCommentBase) GetIsDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDeleted) {
		return nil, false
	}
	return o.IsDeleted, true
}

// HasIsDeleted returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasIsDeleted() bool {
	if o != nil && !IsNil(o.IsDeleted) {
		return true
	}

	return false
}

// SetIsDeleted gets a reference to the given bool and assigns it to the IsDeleted field.
func (o *PubSubCommentBase) SetIsDeleted(v bool) {
	o.IsDeleted = &v
}

// GetIsDeletedUser returns the IsDeletedUser field value if set, zero value otherwise.
func (o *PubSubCommentBase) GetIsDeletedUser() bool {
	if o == nil || IsNil(o.IsDeletedUser) {
		var ret bool
		return ret
	}
	return *o.IsDeletedUser
}

// GetIsDeletedUserOk returns a tuple with the IsDeletedUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PubSubCommentBase) GetIsDeletedUserOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDeletedUser) {
		return nil, false
	}
	return o.IsDeletedUser, true
}

// HasIsDeletedUser returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasIsDeletedUser() bool {
	if o != nil && !IsNil(o.IsDeletedUser) {
		return true
	}

	return false
}

// SetIsDeletedUser gets a reference to the given bool and assigns it to the IsDeletedUser field.
func (o *PubSubCommentBase) SetIsDeletedUser(v bool) {
	o.IsDeletedUser = &v
}

// GetIsSpam returns the IsSpam field value if set, zero value otherwise.
func (o *PubSubCommentBase) GetIsSpam() bool {
	if o == nil || IsNil(o.IsSpam) {
		var ret bool
		return ret
	}
	return *o.IsSpam
}

// GetIsSpamOk returns a tuple with the IsSpam field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PubSubCommentBase) GetIsSpamOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSpam) {
		return nil, false
	}
	return o.IsSpam, true
}

// HasIsSpam returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasIsSpam() bool {
	if o != nil && !IsNil(o.IsSpam) {
		return true
	}

	return false
}

// SetIsSpam gets a reference to the given bool and assigns it to the IsSpam field.
func (o *PubSubCommentBase) SetIsSpam(v bool) {
	o.IsSpam = &v
}

// GetAnonUserId returns the AnonUserId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PubSubCommentBase) GetAnonUserId() string {
	if o == nil || IsNil(o.AnonUserId.Get()) {
		var ret string
		return ret
	}
	return *o.AnonUserId.Get()
}

// GetAnonUserIdOk returns a tuple with the AnonUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PubSubCommentBase) GetAnonUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AnonUserId.Get(), o.AnonUserId.IsSet()
}

// HasAnonUserId returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasAnonUserId() bool {
	if o != nil && o.AnonUserId.IsSet() {
		return true
	}

	return false
}

// SetAnonUserId gets a reference to the given NullableString and assigns it to the AnonUserId field.
func (o *PubSubCommentBase) SetAnonUserId(v string) {
	o.AnonUserId.Set(&v)
}
// SetAnonUserIdNil sets the value for AnonUserId to be an explicit nil
func (o *PubSubCommentBase) SetAnonUserIdNil() {
	o.AnonUserId.Set(nil)
}

// UnsetAnonUserId ensures that no value is present for AnonUserId, not even an explicit nil
func (o *PubSubCommentBase) UnsetAnonUserId() {
	o.AnonUserId.Unset()
}

// GetFeedbackIds returns the FeedbackIds field value if set, zero value otherwise.
func (o *PubSubCommentBase) GetFeedbackIds() []string {
	if o == nil || IsNil(o.FeedbackIds) {
		var ret []string
		return ret
	}
	return o.FeedbackIds
}

// GetFeedbackIdsOk returns a tuple with the FeedbackIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PubSubCommentBase) GetFeedbackIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.FeedbackIds) {
		return nil, false
	}
	return o.FeedbackIds, true
}

// HasFeedbackIds returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasFeedbackIds() bool {
	if o != nil && !IsNil(o.FeedbackIds) {
		return true
	}

	return false
}

// SetFeedbackIds gets a reference to the given []string and assigns it to the FeedbackIds field.
func (o *PubSubCommentBase) SetFeedbackIds(v []string) {
	o.FeedbackIds = v
}

// GetFlagCount returns the FlagCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PubSubCommentBase) GetFlagCount() int32 {
	if o == nil || IsNil(o.FlagCount.Get()) {
		var ret int32
		return ret
	}
	return *o.FlagCount.Get()
}

// GetFlagCountOk returns a tuple with the FlagCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PubSubCommentBase) GetFlagCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.FlagCount.Get(), o.FlagCount.IsSet()
}

// HasFlagCount returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasFlagCount() bool {
	if o != nil && o.FlagCount.IsSet() {
		return true
	}

	return false
}

// SetFlagCount gets a reference to the given NullableInt32 and assigns it to the FlagCount field.
func (o *PubSubCommentBase) SetFlagCount(v int32) {
	o.FlagCount.Set(&v)
}
// SetFlagCountNil sets the value for FlagCount to be an explicit nil
func (o *PubSubCommentBase) SetFlagCountNil() {
	o.FlagCount.Set(nil)
}

// UnsetFlagCount ensures that no value is present for FlagCount, not even an explicit nil
func (o *PubSubCommentBase) UnsetFlagCount() {
	o.FlagCount.Unset()
}

// GetDomain returns the Domain field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PubSubCommentBase) GetDomain() string {
	if o == nil || IsNil(o.Domain.Get()) {
		var ret string
		return ret
	}
	return *o.Domain.Get()
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PubSubCommentBase) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Domain.Get(), o.Domain.IsSet()
}

// HasDomain returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasDomain() bool {
	if o != nil && o.Domain.IsSet() {
		return true
	}

	return false
}

// SetDomain gets a reference to the given NullableString and assigns it to the Domain field.
func (o *PubSubCommentBase) SetDomain(v string) {
	o.Domain.Set(&v)
}
// SetDomainNil sets the value for Domain to be an explicit nil
func (o *PubSubCommentBase) SetDomainNil() {
	o.Domain.Set(nil)
}

// UnsetDomain ensures that no value is present for Domain, not even an explicit nil
func (o *PubSubCommentBase) UnsetDomain() {
	o.Domain.Unset()
}

// GetUrl returns the Url field value
func (o *PubSubCommentBase) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *PubSubCommentBase) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *PubSubCommentBase) SetUrl(v string) {
	o.Url = v
}

// GetPageTitle returns the PageTitle field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PubSubCommentBase) GetPageTitle() string {
	if o == nil || IsNil(o.PageTitle.Get()) {
		var ret string
		return ret
	}
	return *o.PageTitle.Get()
}

// GetPageTitleOk returns a tuple with the PageTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PubSubCommentBase) GetPageTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PageTitle.Get(), o.PageTitle.IsSet()
}

// HasPageTitle returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasPageTitle() bool {
	if o != nil && o.PageTitle.IsSet() {
		return true
	}

	return false
}

// SetPageTitle gets a reference to the given NullableString and assigns it to the PageTitle field.
func (o *PubSubCommentBase) SetPageTitle(v string) {
	o.PageTitle.Set(&v)
}
// SetPageTitleNil sets the value for PageTitle to be an explicit nil
func (o *PubSubCommentBase) SetPageTitleNil() {
	o.PageTitle.Set(nil)
}

// UnsetPageTitle ensures that no value is present for PageTitle, not even an explicit nil
func (o *PubSubCommentBase) UnsetPageTitle() {
	o.PageTitle.Unset()
}

// GetExpireAt returns the ExpireAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PubSubCommentBase) GetExpireAt() time.Time {
	if o == nil || IsNil(o.ExpireAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ExpireAt.Get()
}

// GetExpireAtOk returns a tuple with the ExpireAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PubSubCommentBase) GetExpireAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpireAt.Get(), o.ExpireAt.IsSet()
}

// HasExpireAt returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasExpireAt() bool {
	if o != nil && o.ExpireAt.IsSet() {
		return true
	}

	return false
}

// SetExpireAt gets a reference to the given NullableTime and assigns it to the ExpireAt field.
func (o *PubSubCommentBase) SetExpireAt(v time.Time) {
	o.ExpireAt.Set(&v)
}
// SetExpireAtNil sets the value for ExpireAt to be an explicit nil
func (o *PubSubCommentBase) SetExpireAtNil() {
	o.ExpireAt.Set(nil)
}

// UnsetExpireAt ensures that no value is present for ExpireAt, not even an explicit nil
func (o *PubSubCommentBase) UnsetExpireAt() {
	o.ExpireAt.Unset()
}

// GetReviewed returns the Reviewed field value if set, zero value otherwise.
func (o *PubSubCommentBase) GetReviewed() bool {
	if o == nil || IsNil(o.Reviewed) {
		var ret bool
		return ret
	}
	return *o.Reviewed
}

// GetReviewedOk returns a tuple with the Reviewed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PubSubCommentBase) GetReviewedOk() (*bool, bool) {
	if o == nil || IsNil(o.Reviewed) {
		return nil, false
	}
	return o.Reviewed, true
}

// HasReviewed returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasReviewed() bool {
	if o != nil && !IsNil(o.Reviewed) {
		return true
	}

	return false
}

// SetReviewed gets a reference to the given bool and assigns it to the Reviewed field.
func (o *PubSubCommentBase) SetReviewed(v bool) {
	o.Reviewed = &v
}

// GetHasCode returns the HasCode field value if set, zero value otherwise.
func (o *PubSubCommentBase) GetHasCode() bool {
	if o == nil || IsNil(o.HasCode) {
		var ret bool
		return ret
	}
	return *o.HasCode
}

// GetHasCodeOk returns a tuple with the HasCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PubSubCommentBase) GetHasCodeOk() (*bool, bool) {
	if o == nil || IsNil(o.HasCode) {
		return nil, false
	}
	return o.HasCode, true
}

// HasHasCode returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasHasCode() bool {
	if o != nil && !IsNil(o.HasCode) {
		return true
	}

	return false
}

// SetHasCode gets a reference to the given bool and assigns it to the HasCode field.
func (o *PubSubCommentBase) SetHasCode(v bool) {
	o.HasCode = &v
}

// GetApproved returns the Approved field value
func (o *PubSubCommentBase) GetApproved() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Approved
}

// GetApprovedOk returns a tuple with the Approved field value
// and a boolean to check if the value has been set.
func (o *PubSubCommentBase) GetApprovedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Approved, true
}

// SetApproved sets field value
func (o *PubSubCommentBase) SetApproved(v bool) {
	o.Approved = v
}

// GetLocale returns the Locale field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PubSubCommentBase) GetLocale() string {
	if o == nil || o.Locale.Get() == nil {
		var ret string
		return ret
	}

	return *o.Locale.Get()
}

// GetLocaleOk returns a tuple with the Locale field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PubSubCommentBase) GetLocaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Locale.Get(), o.Locale.IsSet()
}

// SetLocale sets field value
func (o *PubSubCommentBase) SetLocale(v string) {
	o.Locale.Set(&v)
}

// GetIsBannedUser returns the IsBannedUser field value if set, zero value otherwise.
func (o *PubSubCommentBase) GetIsBannedUser() bool {
	if o == nil || IsNil(o.IsBannedUser) {
		var ret bool
		return ret
	}
	return *o.IsBannedUser
}

// GetIsBannedUserOk returns a tuple with the IsBannedUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PubSubCommentBase) GetIsBannedUserOk() (*bool, bool) {
	if o == nil || IsNil(o.IsBannedUser) {
		return nil, false
	}
	return o.IsBannedUser, true
}

// HasIsBannedUser returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasIsBannedUser() bool {
	if o != nil && !IsNil(o.IsBannedUser) {
		return true
	}

	return false
}

// SetIsBannedUser gets a reference to the given bool and assigns it to the IsBannedUser field.
func (o *PubSubCommentBase) SetIsBannedUser(v bool) {
	o.IsBannedUser = &v
}

// GetGroupIds returns the GroupIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PubSubCommentBase) GetGroupIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.GroupIds
}

// GetGroupIdsOk returns a tuple with the GroupIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PubSubCommentBase) GetGroupIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.GroupIds) {
		return nil, false
	}
	return o.GroupIds, true
}

// HasGroupIds returns a boolean if a field has been set.
func (o *PubSubCommentBase) HasGroupIds() bool {
	if o != nil && !IsNil(o.GroupIds) {
		return true
	}

	return false
}

// SetGroupIds gets a reference to the given []string and assigns it to the GroupIds field.
func (o *PubSubCommentBase) SetGroupIds(v []string) {
	o.GroupIds = v
}

func (o PubSubCommentBase) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PubSubCommentBase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["_id"] = o.Id
	toSerialize["tenantId"] = o.TenantId
	if o.UserId.IsSet() {
		toSerialize["userId"] = o.UserId.Get()
	}
	toSerialize["urlId"] = o.UrlId
	toSerialize["commenterName"] = o.CommenterName
	if o.CommenterLink.IsSet() {
		toSerialize["commenterLink"] = o.CommenterLink.Get()
	}
	toSerialize["commentHTML"] = o.CommentHTML
	toSerialize["comment"] = o.Comment
	if o.ParentId.IsSet() {
		toSerialize["parentId"] = o.ParentId.Get()
	}
	if o.Votes.IsSet() {
		toSerialize["votes"] = o.Votes.Get()
	}
	if o.VotesUp.IsSet() {
		toSerialize["votesUp"] = o.VotesUp.Get()
	}
	if o.VotesDown.IsSet() {
		toSerialize["votesDown"] = o.VotesDown.Get()
	}
	toSerialize["verified"] = o.Verified
	if o.AvatarSrc.IsSet() {
		toSerialize["avatarSrc"] = o.AvatarSrc.Get()
	}
	if !IsNil(o.HasImages) {
		toSerialize["hasImages"] = o.HasImages
	}
	if !IsNil(o.HasLinks) {
		toSerialize["hasLinks"] = o.HasLinks
	}
	if !IsNil(o.IsByAdmin) {
		toSerialize["isByAdmin"] = o.IsByAdmin
	}
	if !IsNil(o.IsByModerator) {
		toSerialize["isByModerator"] = o.IsByModerator
	}
	if o.IsPinned.IsSet() {
		toSerialize["isPinned"] = o.IsPinned.Get()
	}
	if o.IsLocked.IsSet() {
		toSerialize["isLocked"] = o.IsLocked.Get()
	}
	if o.DisplayLabel.IsSet() {
		toSerialize["displayLabel"] = o.DisplayLabel.Get()
	}
	if o.Rating.IsSet() {
		toSerialize["rating"] = o.Rating.Get()
	}
	if o.Badges != nil {
		toSerialize["badges"] = o.Badges
	}
	if o.ViewCount.IsSet() {
		toSerialize["viewCount"] = o.ViewCount.Get()
	}
	if !IsNil(o.IsDeleted) {
		toSerialize["isDeleted"] = o.IsDeleted
	}
	if !IsNil(o.IsDeletedUser) {
		toSerialize["isDeletedUser"] = o.IsDeletedUser
	}
	if !IsNil(o.IsSpam) {
		toSerialize["isSpam"] = o.IsSpam
	}
	if o.AnonUserId.IsSet() {
		toSerialize["anonUserId"] = o.AnonUserId.Get()
	}
	if !IsNil(o.FeedbackIds) {
		toSerialize["feedbackIds"] = o.FeedbackIds
	}
	if o.FlagCount.IsSet() {
		toSerialize["flagCount"] = o.FlagCount.Get()
	}
	if o.Domain.IsSet() {
		toSerialize["domain"] = o.Domain.Get()
	}
	toSerialize["url"] = o.Url
	if o.PageTitle.IsSet() {
		toSerialize["pageTitle"] = o.PageTitle.Get()
	}
	if o.ExpireAt.IsSet() {
		toSerialize["expireAt"] = o.ExpireAt.Get()
	}
	if !IsNil(o.Reviewed) {
		toSerialize["reviewed"] = o.Reviewed
	}
	if !IsNil(o.HasCode) {
		toSerialize["hasCode"] = o.HasCode
	}
	toSerialize["approved"] = o.Approved
	toSerialize["locale"] = o.Locale.Get()
	if !IsNil(o.IsBannedUser) {
		toSerialize["isBannedUser"] = o.IsBannedUser
	}
	if o.GroupIds != nil {
		toSerialize["groupIds"] = o.GroupIds
	}
	return toSerialize, nil
}

func (o *PubSubCommentBase) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"_id",
		"tenantId",
		"urlId",
		"commenterName",
		"commentHTML",
		"comment",
		"verified",
		"url",
		"approved",
		"locale",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPubSubCommentBase := _PubSubCommentBase{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPubSubCommentBase)

	if err != nil {
		return err
	}

	*o = PubSubCommentBase(varPubSubCommentBase)

	return err
}

type NullablePubSubCommentBase struct {
	value *PubSubCommentBase
	isSet bool
}

func (v NullablePubSubCommentBase) Get() *PubSubCommentBase {
	return v.value
}

func (v *NullablePubSubCommentBase) Set(val *PubSubCommentBase) {
	v.value = val
	v.isSet = true
}

func (v NullablePubSubCommentBase) IsSet() bool {
	return v.isSet
}

func (v *NullablePubSubCommentBase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePubSubCommentBase(val *PubSubCommentBase) *NullablePubSubCommentBase {
	return &NullablePubSubCommentBase{value: val, isSet: true}
}

func (v NullablePubSubCommentBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePubSubCommentBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


