/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// ChangeTicketState200Response struct for ChangeTicketState200Response
type ChangeTicketState200Response struct {
	APIError *APIError
	ChangeTicketStateResponse *ChangeTicketStateResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ChangeTicketState200Response) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal JSON data into ChangeTicketStateResponse
	err = json.Unmarshal(data, &dst.ChangeTicketStateResponse);
	if err == nil {
		jsonChangeTicketStateResponse, _ := json.Marshal(dst.ChangeTicketStateResponse)
		if string(jsonChangeTicketStateResponse) == "{}" { // empty struct
			dst.ChangeTicketStateResponse = nil
		} else {
			return nil // data stored in dst.ChangeTicketStateResponse, return on the first match
		}
	} else {
		dst.ChangeTicketStateResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ChangeTicketState200Response)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ChangeTicketState200Response) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.ChangeTicketStateResponse != nil {
		return json.Marshal(&src.ChangeTicketStateResponse)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableChangeTicketState200Response struct {
	value *ChangeTicketState200Response
	isSet bool
}

func (v NullableChangeTicketState200Response) Get() *ChangeTicketState200Response {
	return v.value
}

func (v *NullableChangeTicketState200Response) Set(val *ChangeTicketState200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableChangeTicketState200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableChangeTicketState200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangeTicketState200Response(val *ChangeTicketState200Response) *NullableChangeTicketState200Response {
	return &NullableChangeTicketState200Response{value: val, isSet: true}
}

func (v NullableChangeTicketState200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangeTicketState200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


