/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetDomainConfigs200ResponseAnyOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDomainConfigs200ResponseAnyOf1{}

// GetDomainConfigs200ResponseAnyOf1 struct for GetDomainConfigs200ResponseAnyOf1
type GetDomainConfigs200ResponseAnyOf1 struct {
	Reason string `json:"reason"`
	Code string `json:"code"`
	Status interface{} `json:"status"`
}

type _GetDomainConfigs200ResponseAnyOf1 GetDomainConfigs200ResponseAnyOf1

// NewGetDomainConfigs200ResponseAnyOf1 instantiates a new GetDomainConfigs200ResponseAnyOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDomainConfigs200ResponseAnyOf1(reason string, code string, status interface{}) *GetDomainConfigs200ResponseAnyOf1 {
	this := GetDomainConfigs200ResponseAnyOf1{}
	this.Reason = reason
	this.Code = code
	this.Status = status
	return &this
}

// NewGetDomainConfigs200ResponseAnyOf1WithDefaults instantiates a new GetDomainConfigs200ResponseAnyOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDomainConfigs200ResponseAnyOf1WithDefaults() *GetDomainConfigs200ResponseAnyOf1 {
	this := GetDomainConfigs200ResponseAnyOf1{}
	return &this
}

// GetReason returns the Reason field value
func (o *GetDomainConfigs200ResponseAnyOf1) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *GetDomainConfigs200ResponseAnyOf1) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *GetDomainConfigs200ResponseAnyOf1) SetReason(v string) {
	o.Reason = v
}

// GetCode returns the Code field value
func (o *GetDomainConfigs200ResponseAnyOf1) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *GetDomainConfigs200ResponseAnyOf1) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *GetDomainConfigs200ResponseAnyOf1) SetCode(v string) {
	o.Code = v
}

// GetStatus returns the Status field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *GetDomainConfigs200ResponseAnyOf1) GetStatus() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDomainConfigs200ResponseAnyOf1) GetStatusOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetDomainConfigs200ResponseAnyOf1) SetStatus(v interface{}) {
	o.Status = v
}

func (o GetDomainConfigs200ResponseAnyOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDomainConfigs200ResponseAnyOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["reason"] = o.Reason
	toSerialize["code"] = o.Code
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

func (o *GetDomainConfigs200ResponseAnyOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"reason",
		"code",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetDomainConfigs200ResponseAnyOf1 := _GetDomainConfigs200ResponseAnyOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetDomainConfigs200ResponseAnyOf1)

	if err != nil {
		return err
	}

	*o = GetDomainConfigs200ResponseAnyOf1(varGetDomainConfigs200ResponseAnyOf1)

	return err
}

type NullableGetDomainConfigs200ResponseAnyOf1 struct {
	value *GetDomainConfigs200ResponseAnyOf1
	isSet bool
}

func (v NullableGetDomainConfigs200ResponseAnyOf1) Get() *GetDomainConfigs200ResponseAnyOf1 {
	return v.value
}

func (v *NullableGetDomainConfigs200ResponseAnyOf1) Set(val *GetDomainConfigs200ResponseAnyOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDomainConfigs200ResponseAnyOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDomainConfigs200ResponseAnyOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDomainConfigs200ResponseAnyOf1(val *GetDomainConfigs200ResponseAnyOf1) *NullableGetDomainConfigs200ResponseAnyOf1 {
	return &NullableGetDomainConfigs200ResponseAnyOf1{value: val, isSet: true}
}

func (v NullableGetDomainConfigs200ResponseAnyOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDomainConfigs200ResponseAnyOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


