/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// PostAdjustCommentVotesResponse struct for PostAdjustCommentVotesResponse
type PostAdjustCommentVotesResponse struct {
	APIError *APIError
	AdjustVotesResponse *AdjustVotesResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *PostAdjustCommentVotesResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal JSON data into AdjustVotesResponse
	err = json.Unmarshal(data, &dst.AdjustVotesResponse);
	if err == nil {
		jsonAdjustVotesResponse, _ := json.Marshal(dst.AdjustVotesResponse)
		if string(jsonAdjustVotesResponse) == "{}" { // empty struct
			dst.AdjustVotesResponse = nil
		} else {
			return nil // data stored in dst.AdjustVotesResponse, return on the first match
		}
	} else {
		dst.AdjustVotesResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(PostAdjustCommentVotesResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PostAdjustCommentVotesResponse) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.AdjustVotesResponse != nil {
		return json.Marshal(&src.AdjustVotesResponse)
	}

	return nil, nil // no data in anyOf schemas
}


type NullablePostAdjustCommentVotesResponse struct {
	value *PostAdjustCommentVotesResponse
	isSet bool
}

func (v NullablePostAdjustCommentVotesResponse) Get() *PostAdjustCommentVotesResponse {
	return v.value
}

func (v *NullablePostAdjustCommentVotesResponse) Set(val *PostAdjustCommentVotesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePostAdjustCommentVotesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePostAdjustCommentVotesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostAdjustCommentVotesResponse(val *PostAdjustCommentVotesResponse) *NullablePostAdjustCommentVotesResponse {
	return &NullablePostAdjustCommentVotesResponse{value: val, isSet: true}
}

func (v NullablePostAdjustCommentVotesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostAdjustCommentVotesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


