/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetTenantsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTenantsResponse{}

// GetTenantsResponse struct for GetTenantsResponse
type GetTenantsResponse struct {
	Status APIStatus `json:"status"`
	Tenants []APITenant `json:"tenants"`
}

type _GetTenantsResponse GetTenantsResponse

// NewGetTenantsResponse instantiates a new GetTenantsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTenantsResponse(status APIStatus, tenants []APITenant) *GetTenantsResponse {
	this := GetTenantsResponse{}
	this.Status = status
	this.Tenants = tenants
	return &this
}

// NewGetTenantsResponseWithDefaults instantiates a new GetTenantsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTenantsResponseWithDefaults() *GetTenantsResponse {
	this := GetTenantsResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *GetTenantsResponse) GetStatus() APIStatus {
	if o == nil {
		var ret APIStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetTenantsResponse) GetStatusOk() (*APIStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetTenantsResponse) SetStatus(v APIStatus) {
	o.Status = v
}

// GetTenants returns the Tenants field value
func (o *GetTenantsResponse) GetTenants() []APITenant {
	if o == nil {
		var ret []APITenant
		return ret
	}

	return o.Tenants
}

// GetTenantsOk returns a tuple with the Tenants field value
// and a boolean to check if the value has been set.
func (o *GetTenantsResponse) GetTenantsOk() ([]APITenant, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tenants, true
}

// SetTenants sets field value
func (o *GetTenantsResponse) SetTenants(v []APITenant) {
	o.Tenants = v
}

func (o GetTenantsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTenantsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["tenants"] = o.Tenants
	return toSerialize, nil
}

func (o *GetTenantsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"tenants",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetTenantsResponse := _GetTenantsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetTenantsResponse)

	if err != nil {
		return err
	}

	*o = GetTenantsResponse(varGetTenantsResponse)

	return err
}

type NullableGetTenantsResponse struct {
	value *GetTenantsResponse
	isSet bool
}

func (v NullableGetTenantsResponse) Get() *GetTenantsResponse {
	return v.value
}

func (v *NullableGetTenantsResponse) Set(val *GetTenantsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTenantsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTenantsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTenantsResponse(val *GetTenantsResponse) *NullableGetTenantsResponse {
	return &NullableGetTenantsResponse{value: val, isSet: true}
}

func (v NullableGetTenantsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTenantsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


