/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetFeedPostsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetFeedPostsResponse{}

// GetFeedPostsResponse struct for GetFeedPostsResponse
type GetFeedPostsResponse struct {
	Status APIStatus `json:"status"`
	FeedPosts []FeedPost `json:"feedPosts"`
}

type _GetFeedPostsResponse GetFeedPostsResponse

// NewGetFeedPostsResponse instantiates a new GetFeedPostsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetFeedPostsResponse(status APIStatus, feedPosts []FeedPost) *GetFeedPostsResponse {
	this := GetFeedPostsResponse{}
	this.Status = status
	this.FeedPosts = feedPosts
	return &this
}

// NewGetFeedPostsResponseWithDefaults instantiates a new GetFeedPostsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetFeedPostsResponseWithDefaults() *GetFeedPostsResponse {
	this := GetFeedPostsResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *GetFeedPostsResponse) GetStatus() APIStatus {
	if o == nil {
		var ret APIStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetFeedPostsResponse) GetStatusOk() (*APIStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetFeedPostsResponse) SetStatus(v APIStatus) {
	o.Status = v
}

// GetFeedPosts returns the FeedPosts field value
func (o *GetFeedPostsResponse) GetFeedPosts() []FeedPost {
	if o == nil {
		var ret []FeedPost
		return ret
	}

	return o.FeedPosts
}

// GetFeedPostsOk returns a tuple with the FeedPosts field value
// and a boolean to check if the value has been set.
func (o *GetFeedPostsResponse) GetFeedPostsOk() ([]FeedPost, bool) {
	if o == nil {
		return nil, false
	}
	return o.FeedPosts, true
}

// SetFeedPosts sets field value
func (o *GetFeedPostsResponse) SetFeedPosts(v []FeedPost) {
	o.FeedPosts = v
}

func (o GetFeedPostsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetFeedPostsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["feedPosts"] = o.FeedPosts
	return toSerialize, nil
}

func (o *GetFeedPostsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"feedPosts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetFeedPostsResponse := _GetFeedPostsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetFeedPostsResponse)

	if err != nil {
		return err
	}

	*o = GetFeedPostsResponse(varGetFeedPostsResponse)

	return err
}

type NullableGetFeedPostsResponse struct {
	value *GetFeedPostsResponse
	isSet bool
}

func (v NullableGetFeedPostsResponse) Get() *GetFeedPostsResponse {
	return v.value
}

func (v *NullableGetFeedPostsResponse) Set(val *GetFeedPostsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFeedPostsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFeedPostsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFeedPostsResponse(val *GetFeedPostsResponse) *NullableGetFeedPostsResponse {
	return &NullableGetFeedPostsResponse{value: val, isSet: true}
}

func (v NullableGetFeedPostsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFeedPostsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


