/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// GetEmailTemplatesResponse1 struct for GetEmailTemplatesResponse1
type GetEmailTemplatesResponse1 struct {
	APIError *APIError
	GetEmailTemplatesResponse *GetEmailTemplatesResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetEmailTemplatesResponse1) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal JSON data into GetEmailTemplatesResponse
	err = json.Unmarshal(data, &dst.GetEmailTemplatesResponse);
	if err == nil {
		jsonGetEmailTemplatesResponse, _ := json.Marshal(dst.GetEmailTemplatesResponse)
		if string(jsonGetEmailTemplatesResponse) == "{}" { // empty struct
			dst.GetEmailTemplatesResponse = nil
		} else {
			return nil // data stored in dst.GetEmailTemplatesResponse, return on the first match
		}
	} else {
		dst.GetEmailTemplatesResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetEmailTemplatesResponse1)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetEmailTemplatesResponse1) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.GetEmailTemplatesResponse != nil {
		return json.Marshal(&src.GetEmailTemplatesResponse)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableGetEmailTemplatesResponse1 struct {
	value *GetEmailTemplatesResponse1
	isSet bool
}

func (v NullableGetEmailTemplatesResponse1) Get() *GetEmailTemplatesResponse1 {
	return v.value
}

func (v *NullableGetEmailTemplatesResponse1) Set(val *GetEmailTemplatesResponse1) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEmailTemplatesResponse1) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEmailTemplatesResponse1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEmailTemplatesResponse1(val *GetEmailTemplatesResponse1) *NullableGetEmailTemplatesResponse1 {
	return &NullableGetEmailTemplatesResponse1{value: val, isSet: true}
}

func (v NullableGetEmailTemplatesResponse1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEmailTemplatesResponse1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


