/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the UpdateTenantPackageBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTenantPackageBody{}

// UpdateTenantPackageBody struct for UpdateTenantPackageBody
type UpdateTenantPackageBody struct {
	Name *string `json:"name,omitempty"`
	MonthlyCostUSD *float64 `json:"monthlyCostUSD,omitempty"`
	YearlyCostUSD *float64 `json:"yearlyCostUSD,omitempty"`
	MaxMonthlyPageLoads *float64 `json:"maxMonthlyPageLoads,omitempty"`
	MaxMonthlyAPICredits *float64 `json:"maxMonthlyAPICredits,omitempty"`
	MaxMonthlyComments *float64 `json:"maxMonthlyComments,omitempty"`
	MaxConcurrentUsers *float64 `json:"maxConcurrentUsers,omitempty"`
	MaxTenantUsers *float64 `json:"maxTenantUsers,omitempty"`
	MaxSSOUsers *float64 `json:"maxSSOUsers,omitempty"`
	MaxModerators *float64 `json:"maxModerators,omitempty"`
	MaxDomains *float64 `json:"maxDomains,omitempty"`
	HasDebranding *bool `json:"hasDebranding,omitempty"`
	HasWhiteLabeling *bool `json:"hasWhiteLabeling,omitempty"`
	ForWhoText *string `json:"forWhoText,omitempty"`
	FeatureTaglines []string `json:"featureTaglines,omitempty"`
	HasFlexPricing *bool `json:"hasFlexPricing,omitempty"`
	FlexPageLoadCostCents *float64 `json:"flexPageLoadCostCents,omitempty"`
	FlexPageLoadUnit *float64 `json:"flexPageLoadUnit,omitempty"`
	FlexCommentCostCents *float64 `json:"flexCommentCostCents,omitempty"`
	FlexCommentUnit *float64 `json:"flexCommentUnit,omitempty"`
	FlexSSOUserCostCents *float64 `json:"flexSSOUserCostCents,omitempty"`
	FlexSSOUserUnit *float64 `json:"flexSSOUserUnit,omitempty"`
	FlexAPICreditCostCents *float64 `json:"flexAPICreditCostCents,omitempty"`
	FlexAPICreditUnit *float64 `json:"flexAPICreditUnit,omitempty"`
	FlexModeratorCostCents *float64 `json:"flexModeratorCostCents,omitempty"`
	FlexModeratorUnit *float64 `json:"flexModeratorUnit,omitempty"`
	FlexAdminCostCents *float64 `json:"flexAdminCostCents,omitempty"`
	FlexAdminUnit *float64 `json:"flexAdminUnit,omitempty"`
	FlexDomainCostCents *float64 `json:"flexDomainCostCents,omitempty"`
	FlexDomainUnit *float64 `json:"flexDomainUnit,omitempty"`
	FlexMinimumCostCents *float64 `json:"flexMinimumCostCents,omitempty"`
}

// NewUpdateTenantPackageBody instantiates a new UpdateTenantPackageBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTenantPackageBody() *UpdateTenantPackageBody {
	this := UpdateTenantPackageBody{}
	return &this
}

// NewUpdateTenantPackageBodyWithDefaults instantiates a new UpdateTenantPackageBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTenantPackageBodyWithDefaults() *UpdateTenantPackageBody {
	this := UpdateTenantPackageBody{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateTenantPackageBody) SetName(v string) {
	o.Name = &v
}

// GetMonthlyCostUSD returns the MonthlyCostUSD field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetMonthlyCostUSD() float64 {
	if o == nil || IsNil(o.MonthlyCostUSD) {
		var ret float64
		return ret
	}
	return *o.MonthlyCostUSD
}

// GetMonthlyCostUSDOk returns a tuple with the MonthlyCostUSD field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetMonthlyCostUSDOk() (*float64, bool) {
	if o == nil || IsNil(o.MonthlyCostUSD) {
		return nil, false
	}
	return o.MonthlyCostUSD, true
}

// HasMonthlyCostUSD returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasMonthlyCostUSD() bool {
	if o != nil && !IsNil(o.MonthlyCostUSD) {
		return true
	}

	return false
}

// SetMonthlyCostUSD gets a reference to the given float64 and assigns it to the MonthlyCostUSD field.
func (o *UpdateTenantPackageBody) SetMonthlyCostUSD(v float64) {
	o.MonthlyCostUSD = &v
}

// GetYearlyCostUSD returns the YearlyCostUSD field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetYearlyCostUSD() float64 {
	if o == nil || IsNil(o.YearlyCostUSD) {
		var ret float64
		return ret
	}
	return *o.YearlyCostUSD
}

// GetYearlyCostUSDOk returns a tuple with the YearlyCostUSD field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetYearlyCostUSDOk() (*float64, bool) {
	if o == nil || IsNil(o.YearlyCostUSD) {
		return nil, false
	}
	return o.YearlyCostUSD, true
}

// HasYearlyCostUSD returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasYearlyCostUSD() bool {
	if o != nil && !IsNil(o.YearlyCostUSD) {
		return true
	}

	return false
}

// SetYearlyCostUSD gets a reference to the given float64 and assigns it to the YearlyCostUSD field.
func (o *UpdateTenantPackageBody) SetYearlyCostUSD(v float64) {
	o.YearlyCostUSD = &v
}

// GetMaxMonthlyPageLoads returns the MaxMonthlyPageLoads field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetMaxMonthlyPageLoads() float64 {
	if o == nil || IsNil(o.MaxMonthlyPageLoads) {
		var ret float64
		return ret
	}
	return *o.MaxMonthlyPageLoads
}

// GetMaxMonthlyPageLoadsOk returns a tuple with the MaxMonthlyPageLoads field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetMaxMonthlyPageLoadsOk() (*float64, bool) {
	if o == nil || IsNil(o.MaxMonthlyPageLoads) {
		return nil, false
	}
	return o.MaxMonthlyPageLoads, true
}

// HasMaxMonthlyPageLoads returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasMaxMonthlyPageLoads() bool {
	if o != nil && !IsNil(o.MaxMonthlyPageLoads) {
		return true
	}

	return false
}

// SetMaxMonthlyPageLoads gets a reference to the given float64 and assigns it to the MaxMonthlyPageLoads field.
func (o *UpdateTenantPackageBody) SetMaxMonthlyPageLoads(v float64) {
	o.MaxMonthlyPageLoads = &v
}

// GetMaxMonthlyAPICredits returns the MaxMonthlyAPICredits field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetMaxMonthlyAPICredits() float64 {
	if o == nil || IsNil(o.MaxMonthlyAPICredits) {
		var ret float64
		return ret
	}
	return *o.MaxMonthlyAPICredits
}

// GetMaxMonthlyAPICreditsOk returns a tuple with the MaxMonthlyAPICredits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetMaxMonthlyAPICreditsOk() (*float64, bool) {
	if o == nil || IsNil(o.MaxMonthlyAPICredits) {
		return nil, false
	}
	return o.MaxMonthlyAPICredits, true
}

// HasMaxMonthlyAPICredits returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasMaxMonthlyAPICredits() bool {
	if o != nil && !IsNil(o.MaxMonthlyAPICredits) {
		return true
	}

	return false
}

// SetMaxMonthlyAPICredits gets a reference to the given float64 and assigns it to the MaxMonthlyAPICredits field.
func (o *UpdateTenantPackageBody) SetMaxMonthlyAPICredits(v float64) {
	o.MaxMonthlyAPICredits = &v
}

// GetMaxMonthlyComments returns the MaxMonthlyComments field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetMaxMonthlyComments() float64 {
	if o == nil || IsNil(o.MaxMonthlyComments) {
		var ret float64
		return ret
	}
	return *o.MaxMonthlyComments
}

// GetMaxMonthlyCommentsOk returns a tuple with the MaxMonthlyComments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetMaxMonthlyCommentsOk() (*float64, bool) {
	if o == nil || IsNil(o.MaxMonthlyComments) {
		return nil, false
	}
	return o.MaxMonthlyComments, true
}

// HasMaxMonthlyComments returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasMaxMonthlyComments() bool {
	if o != nil && !IsNil(o.MaxMonthlyComments) {
		return true
	}

	return false
}

// SetMaxMonthlyComments gets a reference to the given float64 and assigns it to the MaxMonthlyComments field.
func (o *UpdateTenantPackageBody) SetMaxMonthlyComments(v float64) {
	o.MaxMonthlyComments = &v
}

// GetMaxConcurrentUsers returns the MaxConcurrentUsers field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetMaxConcurrentUsers() float64 {
	if o == nil || IsNil(o.MaxConcurrentUsers) {
		var ret float64
		return ret
	}
	return *o.MaxConcurrentUsers
}

// GetMaxConcurrentUsersOk returns a tuple with the MaxConcurrentUsers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetMaxConcurrentUsersOk() (*float64, bool) {
	if o == nil || IsNil(o.MaxConcurrentUsers) {
		return nil, false
	}
	return o.MaxConcurrentUsers, true
}

// HasMaxConcurrentUsers returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasMaxConcurrentUsers() bool {
	if o != nil && !IsNil(o.MaxConcurrentUsers) {
		return true
	}

	return false
}

// SetMaxConcurrentUsers gets a reference to the given float64 and assigns it to the MaxConcurrentUsers field.
func (o *UpdateTenantPackageBody) SetMaxConcurrentUsers(v float64) {
	o.MaxConcurrentUsers = &v
}

// GetMaxTenantUsers returns the MaxTenantUsers field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetMaxTenantUsers() float64 {
	if o == nil || IsNil(o.MaxTenantUsers) {
		var ret float64
		return ret
	}
	return *o.MaxTenantUsers
}

// GetMaxTenantUsersOk returns a tuple with the MaxTenantUsers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetMaxTenantUsersOk() (*float64, bool) {
	if o == nil || IsNil(o.MaxTenantUsers) {
		return nil, false
	}
	return o.MaxTenantUsers, true
}

// HasMaxTenantUsers returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasMaxTenantUsers() bool {
	if o != nil && !IsNil(o.MaxTenantUsers) {
		return true
	}

	return false
}

// SetMaxTenantUsers gets a reference to the given float64 and assigns it to the MaxTenantUsers field.
func (o *UpdateTenantPackageBody) SetMaxTenantUsers(v float64) {
	o.MaxTenantUsers = &v
}

// GetMaxSSOUsers returns the MaxSSOUsers field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetMaxSSOUsers() float64 {
	if o == nil || IsNil(o.MaxSSOUsers) {
		var ret float64
		return ret
	}
	return *o.MaxSSOUsers
}

// GetMaxSSOUsersOk returns a tuple with the MaxSSOUsers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetMaxSSOUsersOk() (*float64, bool) {
	if o == nil || IsNil(o.MaxSSOUsers) {
		return nil, false
	}
	return o.MaxSSOUsers, true
}

// HasMaxSSOUsers returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasMaxSSOUsers() bool {
	if o != nil && !IsNil(o.MaxSSOUsers) {
		return true
	}

	return false
}

// SetMaxSSOUsers gets a reference to the given float64 and assigns it to the MaxSSOUsers field.
func (o *UpdateTenantPackageBody) SetMaxSSOUsers(v float64) {
	o.MaxSSOUsers = &v
}

// GetMaxModerators returns the MaxModerators field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetMaxModerators() float64 {
	if o == nil || IsNil(o.MaxModerators) {
		var ret float64
		return ret
	}
	return *o.MaxModerators
}

// GetMaxModeratorsOk returns a tuple with the MaxModerators field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetMaxModeratorsOk() (*float64, bool) {
	if o == nil || IsNil(o.MaxModerators) {
		return nil, false
	}
	return o.MaxModerators, true
}

// HasMaxModerators returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasMaxModerators() bool {
	if o != nil && !IsNil(o.MaxModerators) {
		return true
	}

	return false
}

// SetMaxModerators gets a reference to the given float64 and assigns it to the MaxModerators field.
func (o *UpdateTenantPackageBody) SetMaxModerators(v float64) {
	o.MaxModerators = &v
}

// GetMaxDomains returns the MaxDomains field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetMaxDomains() float64 {
	if o == nil || IsNil(o.MaxDomains) {
		var ret float64
		return ret
	}
	return *o.MaxDomains
}

// GetMaxDomainsOk returns a tuple with the MaxDomains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetMaxDomainsOk() (*float64, bool) {
	if o == nil || IsNil(o.MaxDomains) {
		return nil, false
	}
	return o.MaxDomains, true
}

// HasMaxDomains returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasMaxDomains() bool {
	if o != nil && !IsNil(o.MaxDomains) {
		return true
	}

	return false
}

// SetMaxDomains gets a reference to the given float64 and assigns it to the MaxDomains field.
func (o *UpdateTenantPackageBody) SetMaxDomains(v float64) {
	o.MaxDomains = &v
}

// GetHasDebranding returns the HasDebranding field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetHasDebranding() bool {
	if o == nil || IsNil(o.HasDebranding) {
		var ret bool
		return ret
	}
	return *o.HasDebranding
}

// GetHasDebrandingOk returns a tuple with the HasDebranding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetHasDebrandingOk() (*bool, bool) {
	if o == nil || IsNil(o.HasDebranding) {
		return nil, false
	}
	return o.HasDebranding, true
}

// HasHasDebranding returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasHasDebranding() bool {
	if o != nil && !IsNil(o.HasDebranding) {
		return true
	}

	return false
}

// SetHasDebranding gets a reference to the given bool and assigns it to the HasDebranding field.
func (o *UpdateTenantPackageBody) SetHasDebranding(v bool) {
	o.HasDebranding = &v
}

// GetHasWhiteLabeling returns the HasWhiteLabeling field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetHasWhiteLabeling() bool {
	if o == nil || IsNil(o.HasWhiteLabeling) {
		var ret bool
		return ret
	}
	return *o.HasWhiteLabeling
}

// GetHasWhiteLabelingOk returns a tuple with the HasWhiteLabeling field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetHasWhiteLabelingOk() (*bool, bool) {
	if o == nil || IsNil(o.HasWhiteLabeling) {
		return nil, false
	}
	return o.HasWhiteLabeling, true
}

// HasHasWhiteLabeling returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasHasWhiteLabeling() bool {
	if o != nil && !IsNil(o.HasWhiteLabeling) {
		return true
	}

	return false
}

// SetHasWhiteLabeling gets a reference to the given bool and assigns it to the HasWhiteLabeling field.
func (o *UpdateTenantPackageBody) SetHasWhiteLabeling(v bool) {
	o.HasWhiteLabeling = &v
}

// GetForWhoText returns the ForWhoText field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetForWhoText() string {
	if o == nil || IsNil(o.ForWhoText) {
		var ret string
		return ret
	}
	return *o.ForWhoText
}

// GetForWhoTextOk returns a tuple with the ForWhoText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetForWhoTextOk() (*string, bool) {
	if o == nil || IsNil(o.ForWhoText) {
		return nil, false
	}
	return o.ForWhoText, true
}

// HasForWhoText returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasForWhoText() bool {
	if o != nil && !IsNil(o.ForWhoText) {
		return true
	}

	return false
}

// SetForWhoText gets a reference to the given string and assigns it to the ForWhoText field.
func (o *UpdateTenantPackageBody) SetForWhoText(v string) {
	o.ForWhoText = &v
}

// GetFeatureTaglines returns the FeatureTaglines field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetFeatureTaglines() []string {
	if o == nil || IsNil(o.FeatureTaglines) {
		var ret []string
		return ret
	}
	return o.FeatureTaglines
}

// GetFeatureTaglinesOk returns a tuple with the FeatureTaglines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetFeatureTaglinesOk() ([]string, bool) {
	if o == nil || IsNil(o.FeatureTaglines) {
		return nil, false
	}
	return o.FeatureTaglines, true
}

// HasFeatureTaglines returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasFeatureTaglines() bool {
	if o != nil && !IsNil(o.FeatureTaglines) {
		return true
	}

	return false
}

// SetFeatureTaglines gets a reference to the given []string and assigns it to the FeatureTaglines field.
func (o *UpdateTenantPackageBody) SetFeatureTaglines(v []string) {
	o.FeatureTaglines = v
}

// GetHasFlexPricing returns the HasFlexPricing field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetHasFlexPricing() bool {
	if o == nil || IsNil(o.HasFlexPricing) {
		var ret bool
		return ret
	}
	return *o.HasFlexPricing
}

// GetHasFlexPricingOk returns a tuple with the HasFlexPricing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetHasFlexPricingOk() (*bool, bool) {
	if o == nil || IsNil(o.HasFlexPricing) {
		return nil, false
	}
	return o.HasFlexPricing, true
}

// HasHasFlexPricing returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasHasFlexPricing() bool {
	if o != nil && !IsNil(o.HasFlexPricing) {
		return true
	}

	return false
}

// SetHasFlexPricing gets a reference to the given bool and assigns it to the HasFlexPricing field.
func (o *UpdateTenantPackageBody) SetHasFlexPricing(v bool) {
	o.HasFlexPricing = &v
}

// GetFlexPageLoadCostCents returns the FlexPageLoadCostCents field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetFlexPageLoadCostCents() float64 {
	if o == nil || IsNil(o.FlexPageLoadCostCents) {
		var ret float64
		return ret
	}
	return *o.FlexPageLoadCostCents
}

// GetFlexPageLoadCostCentsOk returns a tuple with the FlexPageLoadCostCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetFlexPageLoadCostCentsOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexPageLoadCostCents) {
		return nil, false
	}
	return o.FlexPageLoadCostCents, true
}

// HasFlexPageLoadCostCents returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasFlexPageLoadCostCents() bool {
	if o != nil && !IsNil(o.FlexPageLoadCostCents) {
		return true
	}

	return false
}

// SetFlexPageLoadCostCents gets a reference to the given float64 and assigns it to the FlexPageLoadCostCents field.
func (o *UpdateTenantPackageBody) SetFlexPageLoadCostCents(v float64) {
	o.FlexPageLoadCostCents = &v
}

// GetFlexPageLoadUnit returns the FlexPageLoadUnit field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetFlexPageLoadUnit() float64 {
	if o == nil || IsNil(o.FlexPageLoadUnit) {
		var ret float64
		return ret
	}
	return *o.FlexPageLoadUnit
}

// GetFlexPageLoadUnitOk returns a tuple with the FlexPageLoadUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetFlexPageLoadUnitOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexPageLoadUnit) {
		return nil, false
	}
	return o.FlexPageLoadUnit, true
}

// HasFlexPageLoadUnit returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasFlexPageLoadUnit() bool {
	if o != nil && !IsNil(o.FlexPageLoadUnit) {
		return true
	}

	return false
}

// SetFlexPageLoadUnit gets a reference to the given float64 and assigns it to the FlexPageLoadUnit field.
func (o *UpdateTenantPackageBody) SetFlexPageLoadUnit(v float64) {
	o.FlexPageLoadUnit = &v
}

// GetFlexCommentCostCents returns the FlexCommentCostCents field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetFlexCommentCostCents() float64 {
	if o == nil || IsNil(o.FlexCommentCostCents) {
		var ret float64
		return ret
	}
	return *o.FlexCommentCostCents
}

// GetFlexCommentCostCentsOk returns a tuple with the FlexCommentCostCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetFlexCommentCostCentsOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexCommentCostCents) {
		return nil, false
	}
	return o.FlexCommentCostCents, true
}

// HasFlexCommentCostCents returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasFlexCommentCostCents() bool {
	if o != nil && !IsNil(o.FlexCommentCostCents) {
		return true
	}

	return false
}

// SetFlexCommentCostCents gets a reference to the given float64 and assigns it to the FlexCommentCostCents field.
func (o *UpdateTenantPackageBody) SetFlexCommentCostCents(v float64) {
	o.FlexCommentCostCents = &v
}

// GetFlexCommentUnit returns the FlexCommentUnit field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetFlexCommentUnit() float64 {
	if o == nil || IsNil(o.FlexCommentUnit) {
		var ret float64
		return ret
	}
	return *o.FlexCommentUnit
}

// GetFlexCommentUnitOk returns a tuple with the FlexCommentUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetFlexCommentUnitOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexCommentUnit) {
		return nil, false
	}
	return o.FlexCommentUnit, true
}

// HasFlexCommentUnit returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasFlexCommentUnit() bool {
	if o != nil && !IsNil(o.FlexCommentUnit) {
		return true
	}

	return false
}

// SetFlexCommentUnit gets a reference to the given float64 and assigns it to the FlexCommentUnit field.
func (o *UpdateTenantPackageBody) SetFlexCommentUnit(v float64) {
	o.FlexCommentUnit = &v
}

// GetFlexSSOUserCostCents returns the FlexSSOUserCostCents field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetFlexSSOUserCostCents() float64 {
	if o == nil || IsNil(o.FlexSSOUserCostCents) {
		var ret float64
		return ret
	}
	return *o.FlexSSOUserCostCents
}

// GetFlexSSOUserCostCentsOk returns a tuple with the FlexSSOUserCostCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetFlexSSOUserCostCentsOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexSSOUserCostCents) {
		return nil, false
	}
	return o.FlexSSOUserCostCents, true
}

// HasFlexSSOUserCostCents returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasFlexSSOUserCostCents() bool {
	if o != nil && !IsNil(o.FlexSSOUserCostCents) {
		return true
	}

	return false
}

// SetFlexSSOUserCostCents gets a reference to the given float64 and assigns it to the FlexSSOUserCostCents field.
func (o *UpdateTenantPackageBody) SetFlexSSOUserCostCents(v float64) {
	o.FlexSSOUserCostCents = &v
}

// GetFlexSSOUserUnit returns the FlexSSOUserUnit field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetFlexSSOUserUnit() float64 {
	if o == nil || IsNil(o.FlexSSOUserUnit) {
		var ret float64
		return ret
	}
	return *o.FlexSSOUserUnit
}

// GetFlexSSOUserUnitOk returns a tuple with the FlexSSOUserUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetFlexSSOUserUnitOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexSSOUserUnit) {
		return nil, false
	}
	return o.FlexSSOUserUnit, true
}

// HasFlexSSOUserUnit returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasFlexSSOUserUnit() bool {
	if o != nil && !IsNil(o.FlexSSOUserUnit) {
		return true
	}

	return false
}

// SetFlexSSOUserUnit gets a reference to the given float64 and assigns it to the FlexSSOUserUnit field.
func (o *UpdateTenantPackageBody) SetFlexSSOUserUnit(v float64) {
	o.FlexSSOUserUnit = &v
}

// GetFlexAPICreditCostCents returns the FlexAPICreditCostCents field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetFlexAPICreditCostCents() float64 {
	if o == nil || IsNil(o.FlexAPICreditCostCents) {
		var ret float64
		return ret
	}
	return *o.FlexAPICreditCostCents
}

// GetFlexAPICreditCostCentsOk returns a tuple with the FlexAPICreditCostCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetFlexAPICreditCostCentsOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexAPICreditCostCents) {
		return nil, false
	}
	return o.FlexAPICreditCostCents, true
}

// HasFlexAPICreditCostCents returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasFlexAPICreditCostCents() bool {
	if o != nil && !IsNil(o.FlexAPICreditCostCents) {
		return true
	}

	return false
}

// SetFlexAPICreditCostCents gets a reference to the given float64 and assigns it to the FlexAPICreditCostCents field.
func (o *UpdateTenantPackageBody) SetFlexAPICreditCostCents(v float64) {
	o.FlexAPICreditCostCents = &v
}

// GetFlexAPICreditUnit returns the FlexAPICreditUnit field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetFlexAPICreditUnit() float64 {
	if o == nil || IsNil(o.FlexAPICreditUnit) {
		var ret float64
		return ret
	}
	return *o.FlexAPICreditUnit
}

// GetFlexAPICreditUnitOk returns a tuple with the FlexAPICreditUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetFlexAPICreditUnitOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexAPICreditUnit) {
		return nil, false
	}
	return o.FlexAPICreditUnit, true
}

// HasFlexAPICreditUnit returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasFlexAPICreditUnit() bool {
	if o != nil && !IsNil(o.FlexAPICreditUnit) {
		return true
	}

	return false
}

// SetFlexAPICreditUnit gets a reference to the given float64 and assigns it to the FlexAPICreditUnit field.
func (o *UpdateTenantPackageBody) SetFlexAPICreditUnit(v float64) {
	o.FlexAPICreditUnit = &v
}

// GetFlexModeratorCostCents returns the FlexModeratorCostCents field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetFlexModeratorCostCents() float64 {
	if o == nil || IsNil(o.FlexModeratorCostCents) {
		var ret float64
		return ret
	}
	return *o.FlexModeratorCostCents
}

// GetFlexModeratorCostCentsOk returns a tuple with the FlexModeratorCostCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetFlexModeratorCostCentsOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexModeratorCostCents) {
		return nil, false
	}
	return o.FlexModeratorCostCents, true
}

// HasFlexModeratorCostCents returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasFlexModeratorCostCents() bool {
	if o != nil && !IsNil(o.FlexModeratorCostCents) {
		return true
	}

	return false
}

// SetFlexModeratorCostCents gets a reference to the given float64 and assigns it to the FlexModeratorCostCents field.
func (o *UpdateTenantPackageBody) SetFlexModeratorCostCents(v float64) {
	o.FlexModeratorCostCents = &v
}

// GetFlexModeratorUnit returns the FlexModeratorUnit field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetFlexModeratorUnit() float64 {
	if o == nil || IsNil(o.FlexModeratorUnit) {
		var ret float64
		return ret
	}
	return *o.FlexModeratorUnit
}

// GetFlexModeratorUnitOk returns a tuple with the FlexModeratorUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetFlexModeratorUnitOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexModeratorUnit) {
		return nil, false
	}
	return o.FlexModeratorUnit, true
}

// HasFlexModeratorUnit returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasFlexModeratorUnit() bool {
	if o != nil && !IsNil(o.FlexModeratorUnit) {
		return true
	}

	return false
}

// SetFlexModeratorUnit gets a reference to the given float64 and assigns it to the FlexModeratorUnit field.
func (o *UpdateTenantPackageBody) SetFlexModeratorUnit(v float64) {
	o.FlexModeratorUnit = &v
}

// GetFlexAdminCostCents returns the FlexAdminCostCents field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetFlexAdminCostCents() float64 {
	if o == nil || IsNil(o.FlexAdminCostCents) {
		var ret float64
		return ret
	}
	return *o.FlexAdminCostCents
}

// GetFlexAdminCostCentsOk returns a tuple with the FlexAdminCostCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetFlexAdminCostCentsOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexAdminCostCents) {
		return nil, false
	}
	return o.FlexAdminCostCents, true
}

// HasFlexAdminCostCents returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasFlexAdminCostCents() bool {
	if o != nil && !IsNil(o.FlexAdminCostCents) {
		return true
	}

	return false
}

// SetFlexAdminCostCents gets a reference to the given float64 and assigns it to the FlexAdminCostCents field.
func (o *UpdateTenantPackageBody) SetFlexAdminCostCents(v float64) {
	o.FlexAdminCostCents = &v
}

// GetFlexAdminUnit returns the FlexAdminUnit field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetFlexAdminUnit() float64 {
	if o == nil || IsNil(o.FlexAdminUnit) {
		var ret float64
		return ret
	}
	return *o.FlexAdminUnit
}

// GetFlexAdminUnitOk returns a tuple with the FlexAdminUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetFlexAdminUnitOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexAdminUnit) {
		return nil, false
	}
	return o.FlexAdminUnit, true
}

// HasFlexAdminUnit returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasFlexAdminUnit() bool {
	if o != nil && !IsNil(o.FlexAdminUnit) {
		return true
	}

	return false
}

// SetFlexAdminUnit gets a reference to the given float64 and assigns it to the FlexAdminUnit field.
func (o *UpdateTenantPackageBody) SetFlexAdminUnit(v float64) {
	o.FlexAdminUnit = &v
}

// GetFlexDomainCostCents returns the FlexDomainCostCents field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetFlexDomainCostCents() float64 {
	if o == nil || IsNil(o.FlexDomainCostCents) {
		var ret float64
		return ret
	}
	return *o.FlexDomainCostCents
}

// GetFlexDomainCostCentsOk returns a tuple with the FlexDomainCostCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetFlexDomainCostCentsOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexDomainCostCents) {
		return nil, false
	}
	return o.FlexDomainCostCents, true
}

// HasFlexDomainCostCents returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasFlexDomainCostCents() bool {
	if o != nil && !IsNil(o.FlexDomainCostCents) {
		return true
	}

	return false
}

// SetFlexDomainCostCents gets a reference to the given float64 and assigns it to the FlexDomainCostCents field.
func (o *UpdateTenantPackageBody) SetFlexDomainCostCents(v float64) {
	o.FlexDomainCostCents = &v
}

// GetFlexDomainUnit returns the FlexDomainUnit field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetFlexDomainUnit() float64 {
	if o == nil || IsNil(o.FlexDomainUnit) {
		var ret float64
		return ret
	}
	return *o.FlexDomainUnit
}

// GetFlexDomainUnitOk returns a tuple with the FlexDomainUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetFlexDomainUnitOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexDomainUnit) {
		return nil, false
	}
	return o.FlexDomainUnit, true
}

// HasFlexDomainUnit returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasFlexDomainUnit() bool {
	if o != nil && !IsNil(o.FlexDomainUnit) {
		return true
	}

	return false
}

// SetFlexDomainUnit gets a reference to the given float64 and assigns it to the FlexDomainUnit field.
func (o *UpdateTenantPackageBody) SetFlexDomainUnit(v float64) {
	o.FlexDomainUnit = &v
}

// GetFlexMinimumCostCents returns the FlexMinimumCostCents field value if set, zero value otherwise.
func (o *UpdateTenantPackageBody) GetFlexMinimumCostCents() float64 {
	if o == nil || IsNil(o.FlexMinimumCostCents) {
		var ret float64
		return ret
	}
	return *o.FlexMinimumCostCents
}

// GetFlexMinimumCostCentsOk returns a tuple with the FlexMinimumCostCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTenantPackageBody) GetFlexMinimumCostCentsOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexMinimumCostCents) {
		return nil, false
	}
	return o.FlexMinimumCostCents, true
}

// HasFlexMinimumCostCents returns a boolean if a field has been set.
func (o *UpdateTenantPackageBody) HasFlexMinimumCostCents() bool {
	if o != nil && !IsNil(o.FlexMinimumCostCents) {
		return true
	}

	return false
}

// SetFlexMinimumCostCents gets a reference to the given float64 and assigns it to the FlexMinimumCostCents field.
func (o *UpdateTenantPackageBody) SetFlexMinimumCostCents(v float64) {
	o.FlexMinimumCostCents = &v
}

func (o UpdateTenantPackageBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTenantPackageBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.MonthlyCostUSD) {
		toSerialize["monthlyCostUSD"] = o.MonthlyCostUSD
	}
	if !IsNil(o.YearlyCostUSD) {
		toSerialize["yearlyCostUSD"] = o.YearlyCostUSD
	}
	if !IsNil(o.MaxMonthlyPageLoads) {
		toSerialize["maxMonthlyPageLoads"] = o.MaxMonthlyPageLoads
	}
	if !IsNil(o.MaxMonthlyAPICredits) {
		toSerialize["maxMonthlyAPICredits"] = o.MaxMonthlyAPICredits
	}
	if !IsNil(o.MaxMonthlyComments) {
		toSerialize["maxMonthlyComments"] = o.MaxMonthlyComments
	}
	if !IsNil(o.MaxConcurrentUsers) {
		toSerialize["maxConcurrentUsers"] = o.MaxConcurrentUsers
	}
	if !IsNil(o.MaxTenantUsers) {
		toSerialize["maxTenantUsers"] = o.MaxTenantUsers
	}
	if !IsNil(o.MaxSSOUsers) {
		toSerialize["maxSSOUsers"] = o.MaxSSOUsers
	}
	if !IsNil(o.MaxModerators) {
		toSerialize["maxModerators"] = o.MaxModerators
	}
	if !IsNil(o.MaxDomains) {
		toSerialize["maxDomains"] = o.MaxDomains
	}
	if !IsNil(o.HasDebranding) {
		toSerialize["hasDebranding"] = o.HasDebranding
	}
	if !IsNil(o.HasWhiteLabeling) {
		toSerialize["hasWhiteLabeling"] = o.HasWhiteLabeling
	}
	if !IsNil(o.ForWhoText) {
		toSerialize["forWhoText"] = o.ForWhoText
	}
	if !IsNil(o.FeatureTaglines) {
		toSerialize["featureTaglines"] = o.FeatureTaglines
	}
	if !IsNil(o.HasFlexPricing) {
		toSerialize["hasFlexPricing"] = o.HasFlexPricing
	}
	if !IsNil(o.FlexPageLoadCostCents) {
		toSerialize["flexPageLoadCostCents"] = o.FlexPageLoadCostCents
	}
	if !IsNil(o.FlexPageLoadUnit) {
		toSerialize["flexPageLoadUnit"] = o.FlexPageLoadUnit
	}
	if !IsNil(o.FlexCommentCostCents) {
		toSerialize["flexCommentCostCents"] = o.FlexCommentCostCents
	}
	if !IsNil(o.FlexCommentUnit) {
		toSerialize["flexCommentUnit"] = o.FlexCommentUnit
	}
	if !IsNil(o.FlexSSOUserCostCents) {
		toSerialize["flexSSOUserCostCents"] = o.FlexSSOUserCostCents
	}
	if !IsNil(o.FlexSSOUserUnit) {
		toSerialize["flexSSOUserUnit"] = o.FlexSSOUserUnit
	}
	if !IsNil(o.FlexAPICreditCostCents) {
		toSerialize["flexAPICreditCostCents"] = o.FlexAPICreditCostCents
	}
	if !IsNil(o.FlexAPICreditUnit) {
		toSerialize["flexAPICreditUnit"] = o.FlexAPICreditUnit
	}
	if !IsNil(o.FlexModeratorCostCents) {
		toSerialize["flexModeratorCostCents"] = o.FlexModeratorCostCents
	}
	if !IsNil(o.FlexModeratorUnit) {
		toSerialize["flexModeratorUnit"] = o.FlexModeratorUnit
	}
	if !IsNil(o.FlexAdminCostCents) {
		toSerialize["flexAdminCostCents"] = o.FlexAdminCostCents
	}
	if !IsNil(o.FlexAdminUnit) {
		toSerialize["flexAdminUnit"] = o.FlexAdminUnit
	}
	if !IsNil(o.FlexDomainCostCents) {
		toSerialize["flexDomainCostCents"] = o.FlexDomainCostCents
	}
	if !IsNil(o.FlexDomainUnit) {
		toSerialize["flexDomainUnit"] = o.FlexDomainUnit
	}
	if !IsNil(o.FlexMinimumCostCents) {
		toSerialize["flexMinimumCostCents"] = o.FlexMinimumCostCents
	}
	return toSerialize, nil
}

type NullableUpdateTenantPackageBody struct {
	value *UpdateTenantPackageBody
	isSet bool
}

func (v NullableUpdateTenantPackageBody) Get() *UpdateTenantPackageBody {
	return v.value
}

func (v *NullableUpdateTenantPackageBody) Set(val *UpdateTenantPackageBody) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTenantPackageBody) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTenantPackageBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTenantPackageBody(val *UpdateTenantPackageBody) *NullableUpdateTenantPackageBody {
	return &NullableUpdateTenantPackageBody{value: val, isSet: true}
}

func (v NullableUpdateTenantPackageBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTenantPackageBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


