/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the DeleteHashTagRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteHashTagRequest{}

// DeleteHashTagRequest struct for DeleteHashTagRequest
type DeleteHashTagRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
}

// NewDeleteHashTagRequest instantiates a new DeleteHashTagRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteHashTagRequest() *DeleteHashTagRequest {
	this := DeleteHashTagRequest{}
	return &this
}

// NewDeleteHashTagRequestWithDefaults instantiates a new DeleteHashTagRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteHashTagRequestWithDefaults() *DeleteHashTagRequest {
	this := DeleteHashTagRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *DeleteHashTagRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteHashTagRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *DeleteHashTagRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *DeleteHashTagRequest) SetTenantId(v string) {
	o.TenantId = &v
}

func (o DeleteHashTagRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteHashTagRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	return toSerialize, nil
}

type NullableDeleteHashTagRequest struct {
	value *DeleteHashTagRequest
	isSet bool
}

func (v NullableDeleteHashTagRequest) Get() *DeleteHashTagRequest {
	return v.value
}

func (v *NullableDeleteHashTagRequest) Set(val *DeleteHashTagRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteHashTagRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteHashTagRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteHashTagRequest(val *DeleteHashTagRequest) *NullableDeleteHashTagRequest {
	return &NullableDeleteHashTagRequest{value: val, isSet: true}
}

func (v NullableDeleteHashTagRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteHashTagRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


