/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateQuestionConfigBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateQuestionConfigBody{}

// CreateQuestionConfigBody struct for CreateQuestionConfigBody
type CreateQuestionConfigBody struct {
	Name string `json:"name"`
	Question string `json:"question"`
	HelpText *string `json:"helpText,omitempty"`
	Type string `json:"type"`
	NumStars *float64 `json:"numStars,omitempty"`
	Min *float64 `json:"min,omitempty"`
	Max *float64 `json:"max,omitempty"`
	DefaultValue *float64 `json:"defaultValue,omitempty"`
	LabelNegative *string `json:"labelNegative,omitempty"`
	LabelPositive *string `json:"labelPositive,omitempty"`
	CustomOptions []QuestionConfigCustomOptionsInner `json:"customOptions,omitempty"`
	SubQuestionIds []string `json:"subQuestionIds,omitempty"`
	AlwaysShowSubQuestions *bool `json:"alwaysShowSubQuestions,omitempty"`
	ReportingOrder float64 `json:"reportingOrder"`
	AdditionalProperties map[string]interface{}
}

type _CreateQuestionConfigBody CreateQuestionConfigBody

// NewCreateQuestionConfigBody instantiates a new CreateQuestionConfigBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateQuestionConfigBody(name string, question string, type_ string, reportingOrder float64) *CreateQuestionConfigBody {
	this := CreateQuestionConfigBody{}
	this.Name = name
	this.Question = question
	this.Type = type_
	this.ReportingOrder = reportingOrder
	return &this
}

// NewCreateQuestionConfigBodyWithDefaults instantiates a new CreateQuestionConfigBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateQuestionConfigBodyWithDefaults() *CreateQuestionConfigBody {
	this := CreateQuestionConfigBody{}
	return &this
}

// GetName returns the Name field value
func (o *CreateQuestionConfigBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateQuestionConfigBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateQuestionConfigBody) SetName(v string) {
	o.Name = v
}

// GetQuestion returns the Question field value
func (o *CreateQuestionConfigBody) GetQuestion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Question
}

// GetQuestionOk returns a tuple with the Question field value
// and a boolean to check if the value has been set.
func (o *CreateQuestionConfigBody) GetQuestionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Question, true
}

// SetQuestion sets field value
func (o *CreateQuestionConfigBody) SetQuestion(v string) {
	o.Question = v
}

// GetHelpText returns the HelpText field value if set, zero value otherwise.
func (o *CreateQuestionConfigBody) GetHelpText() string {
	if o == nil || IsNil(o.HelpText) {
		var ret string
		return ret
	}
	return *o.HelpText
}

// GetHelpTextOk returns a tuple with the HelpText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateQuestionConfigBody) GetHelpTextOk() (*string, bool) {
	if o == nil || IsNil(o.HelpText) {
		return nil, false
	}
	return o.HelpText, true
}

// HasHelpText returns a boolean if a field has been set.
func (o *CreateQuestionConfigBody) HasHelpText() bool {
	if o != nil && !IsNil(o.HelpText) {
		return true
	}

	return false
}

// SetHelpText gets a reference to the given string and assigns it to the HelpText field.
func (o *CreateQuestionConfigBody) SetHelpText(v string) {
	o.HelpText = &v
}

// GetType returns the Type field value
func (o *CreateQuestionConfigBody) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateQuestionConfigBody) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateQuestionConfigBody) SetType(v string) {
	o.Type = v
}

// GetNumStars returns the NumStars field value if set, zero value otherwise.
func (o *CreateQuestionConfigBody) GetNumStars() float64 {
	if o == nil || IsNil(o.NumStars) {
		var ret float64
		return ret
	}
	return *o.NumStars
}

// GetNumStarsOk returns a tuple with the NumStars field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateQuestionConfigBody) GetNumStarsOk() (*float64, bool) {
	if o == nil || IsNil(o.NumStars) {
		return nil, false
	}
	return o.NumStars, true
}

// HasNumStars returns a boolean if a field has been set.
func (o *CreateQuestionConfigBody) HasNumStars() bool {
	if o != nil && !IsNil(o.NumStars) {
		return true
	}

	return false
}

// SetNumStars gets a reference to the given float64 and assigns it to the NumStars field.
func (o *CreateQuestionConfigBody) SetNumStars(v float64) {
	o.NumStars = &v
}

// GetMin returns the Min field value if set, zero value otherwise.
func (o *CreateQuestionConfigBody) GetMin() float64 {
	if o == nil || IsNil(o.Min) {
		var ret float64
		return ret
	}
	return *o.Min
}

// GetMinOk returns a tuple with the Min field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateQuestionConfigBody) GetMinOk() (*float64, bool) {
	if o == nil || IsNil(o.Min) {
		return nil, false
	}
	return o.Min, true
}

// HasMin returns a boolean if a field has been set.
func (o *CreateQuestionConfigBody) HasMin() bool {
	if o != nil && !IsNil(o.Min) {
		return true
	}

	return false
}

// SetMin gets a reference to the given float64 and assigns it to the Min field.
func (o *CreateQuestionConfigBody) SetMin(v float64) {
	o.Min = &v
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *CreateQuestionConfigBody) GetMax() float64 {
	if o == nil || IsNil(o.Max) {
		var ret float64
		return ret
	}
	return *o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateQuestionConfigBody) GetMaxOk() (*float64, bool) {
	if o == nil || IsNil(o.Max) {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *CreateQuestionConfigBody) HasMax() bool {
	if o != nil && !IsNil(o.Max) {
		return true
	}

	return false
}

// SetMax gets a reference to the given float64 and assigns it to the Max field.
func (o *CreateQuestionConfigBody) SetMax(v float64) {
	o.Max = &v
}

// GetDefaultValue returns the DefaultValue field value if set, zero value otherwise.
func (o *CreateQuestionConfigBody) GetDefaultValue() float64 {
	if o == nil || IsNil(o.DefaultValue) {
		var ret float64
		return ret
	}
	return *o.DefaultValue
}

// GetDefaultValueOk returns a tuple with the DefaultValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateQuestionConfigBody) GetDefaultValueOk() (*float64, bool) {
	if o == nil || IsNil(o.DefaultValue) {
		return nil, false
	}
	return o.DefaultValue, true
}

// HasDefaultValue returns a boolean if a field has been set.
func (o *CreateQuestionConfigBody) HasDefaultValue() bool {
	if o != nil && !IsNil(o.DefaultValue) {
		return true
	}

	return false
}

// SetDefaultValue gets a reference to the given float64 and assigns it to the DefaultValue field.
func (o *CreateQuestionConfigBody) SetDefaultValue(v float64) {
	o.DefaultValue = &v
}

// GetLabelNegative returns the LabelNegative field value if set, zero value otherwise.
func (o *CreateQuestionConfigBody) GetLabelNegative() string {
	if o == nil || IsNil(o.LabelNegative) {
		var ret string
		return ret
	}
	return *o.LabelNegative
}

// GetLabelNegativeOk returns a tuple with the LabelNegative field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateQuestionConfigBody) GetLabelNegativeOk() (*string, bool) {
	if o == nil || IsNil(o.LabelNegative) {
		return nil, false
	}
	return o.LabelNegative, true
}

// HasLabelNegative returns a boolean if a field has been set.
func (o *CreateQuestionConfigBody) HasLabelNegative() bool {
	if o != nil && !IsNil(o.LabelNegative) {
		return true
	}

	return false
}

// SetLabelNegative gets a reference to the given string and assigns it to the LabelNegative field.
func (o *CreateQuestionConfigBody) SetLabelNegative(v string) {
	o.LabelNegative = &v
}

// GetLabelPositive returns the LabelPositive field value if set, zero value otherwise.
func (o *CreateQuestionConfigBody) GetLabelPositive() string {
	if o == nil || IsNil(o.LabelPositive) {
		var ret string
		return ret
	}
	return *o.LabelPositive
}

// GetLabelPositiveOk returns a tuple with the LabelPositive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateQuestionConfigBody) GetLabelPositiveOk() (*string, bool) {
	if o == nil || IsNil(o.LabelPositive) {
		return nil, false
	}
	return o.LabelPositive, true
}

// HasLabelPositive returns a boolean if a field has been set.
func (o *CreateQuestionConfigBody) HasLabelPositive() bool {
	if o != nil && !IsNil(o.LabelPositive) {
		return true
	}

	return false
}

// SetLabelPositive gets a reference to the given string and assigns it to the LabelPositive field.
func (o *CreateQuestionConfigBody) SetLabelPositive(v string) {
	o.LabelPositive = &v
}

// GetCustomOptions returns the CustomOptions field value if set, zero value otherwise.
func (o *CreateQuestionConfigBody) GetCustomOptions() []QuestionConfigCustomOptionsInner {
	if o == nil || IsNil(o.CustomOptions) {
		var ret []QuestionConfigCustomOptionsInner
		return ret
	}
	return o.CustomOptions
}

// GetCustomOptionsOk returns a tuple with the CustomOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateQuestionConfigBody) GetCustomOptionsOk() ([]QuestionConfigCustomOptionsInner, bool) {
	if o == nil || IsNil(o.CustomOptions) {
		return nil, false
	}
	return o.CustomOptions, true
}

// HasCustomOptions returns a boolean if a field has been set.
func (o *CreateQuestionConfigBody) HasCustomOptions() bool {
	if o != nil && !IsNil(o.CustomOptions) {
		return true
	}

	return false
}

// SetCustomOptions gets a reference to the given []QuestionConfigCustomOptionsInner and assigns it to the CustomOptions field.
func (o *CreateQuestionConfigBody) SetCustomOptions(v []QuestionConfigCustomOptionsInner) {
	o.CustomOptions = v
}

// GetSubQuestionIds returns the SubQuestionIds field value if set, zero value otherwise.
func (o *CreateQuestionConfigBody) GetSubQuestionIds() []string {
	if o == nil || IsNil(o.SubQuestionIds) {
		var ret []string
		return ret
	}
	return o.SubQuestionIds
}

// GetSubQuestionIdsOk returns a tuple with the SubQuestionIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateQuestionConfigBody) GetSubQuestionIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SubQuestionIds) {
		return nil, false
	}
	return o.SubQuestionIds, true
}

// HasSubQuestionIds returns a boolean if a field has been set.
func (o *CreateQuestionConfigBody) HasSubQuestionIds() bool {
	if o != nil && !IsNil(o.SubQuestionIds) {
		return true
	}

	return false
}

// SetSubQuestionIds gets a reference to the given []string and assigns it to the SubQuestionIds field.
func (o *CreateQuestionConfigBody) SetSubQuestionIds(v []string) {
	o.SubQuestionIds = v
}

// GetAlwaysShowSubQuestions returns the AlwaysShowSubQuestions field value if set, zero value otherwise.
func (o *CreateQuestionConfigBody) GetAlwaysShowSubQuestions() bool {
	if o == nil || IsNil(o.AlwaysShowSubQuestions) {
		var ret bool
		return ret
	}
	return *o.AlwaysShowSubQuestions
}

// GetAlwaysShowSubQuestionsOk returns a tuple with the AlwaysShowSubQuestions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateQuestionConfigBody) GetAlwaysShowSubQuestionsOk() (*bool, bool) {
	if o == nil || IsNil(o.AlwaysShowSubQuestions) {
		return nil, false
	}
	return o.AlwaysShowSubQuestions, true
}

// HasAlwaysShowSubQuestions returns a boolean if a field has been set.
func (o *CreateQuestionConfigBody) HasAlwaysShowSubQuestions() bool {
	if o != nil && !IsNil(o.AlwaysShowSubQuestions) {
		return true
	}

	return false
}

// SetAlwaysShowSubQuestions gets a reference to the given bool and assigns it to the AlwaysShowSubQuestions field.
func (o *CreateQuestionConfigBody) SetAlwaysShowSubQuestions(v bool) {
	o.AlwaysShowSubQuestions = &v
}

// GetReportingOrder returns the ReportingOrder field value
func (o *CreateQuestionConfigBody) GetReportingOrder() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.ReportingOrder
}

// GetReportingOrderOk returns a tuple with the ReportingOrder field value
// and a boolean to check if the value has been set.
func (o *CreateQuestionConfigBody) GetReportingOrderOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReportingOrder, true
}

// SetReportingOrder sets field value
func (o *CreateQuestionConfigBody) SetReportingOrder(v float64) {
	o.ReportingOrder = v
}

func (o CreateQuestionConfigBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateQuestionConfigBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["question"] = o.Question
	if !IsNil(o.HelpText) {
		toSerialize["helpText"] = o.HelpText
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.NumStars) {
		toSerialize["numStars"] = o.NumStars
	}
	if !IsNil(o.Min) {
		toSerialize["min"] = o.Min
	}
	if !IsNil(o.Max) {
		toSerialize["max"] = o.Max
	}
	if !IsNil(o.DefaultValue) {
		toSerialize["defaultValue"] = o.DefaultValue
	}
	if !IsNil(o.LabelNegative) {
		toSerialize["labelNegative"] = o.LabelNegative
	}
	if !IsNil(o.LabelPositive) {
		toSerialize["labelPositive"] = o.LabelPositive
	}
	if !IsNil(o.CustomOptions) {
		toSerialize["customOptions"] = o.CustomOptions
	}
	if !IsNil(o.SubQuestionIds) {
		toSerialize["subQuestionIds"] = o.SubQuestionIds
	}
	if !IsNil(o.AlwaysShowSubQuestions) {
		toSerialize["alwaysShowSubQuestions"] = o.AlwaysShowSubQuestions
	}
	toSerialize["reportingOrder"] = o.ReportingOrder

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateQuestionConfigBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"question",
		"type",
		"reportingOrder",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateQuestionConfigBody := _CreateQuestionConfigBody{}

	err = json.Unmarshal(data, &varCreateQuestionConfigBody)

	if err != nil {
		return err
	}

	*o = CreateQuestionConfigBody(varCreateQuestionConfigBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "question")
		delete(additionalProperties, "helpText")
		delete(additionalProperties, "type")
		delete(additionalProperties, "numStars")
		delete(additionalProperties, "min")
		delete(additionalProperties, "max")
		delete(additionalProperties, "defaultValue")
		delete(additionalProperties, "labelNegative")
		delete(additionalProperties, "labelPositive")
		delete(additionalProperties, "customOptions")
		delete(additionalProperties, "subQuestionIds")
		delete(additionalProperties, "alwaysShowSubQuestions")
		delete(additionalProperties, "reportingOrder")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateQuestionConfigBody struct {
	value *CreateQuestionConfigBody
	isSet bool
}

func (v NullableCreateQuestionConfigBody) Get() *CreateQuestionConfigBody {
	return v.value
}

func (v *NullableCreateQuestionConfigBody) Set(val *CreateQuestionConfigBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateQuestionConfigBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateQuestionConfigBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateQuestionConfigBody(val *CreateQuestionConfigBody) *NullableCreateQuestionConfigBody {
	return &NullableCreateQuestionConfigBody{value: val, isSet: true}
}

func (v NullableCreateQuestionConfigBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateQuestionConfigBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


