/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// GetTenantPackages200Response struct for GetTenantPackages200Response
type GetTenantPackages200Response struct {
	APIError *APIError
	GetTenantPackagesResponse *GetTenantPackagesResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetTenantPackages200Response) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal JSON data into GetTenantPackagesResponse
	err = json.Unmarshal(data, &dst.GetTenantPackagesResponse);
	if err == nil {
		jsonGetTenantPackagesResponse, _ := json.Marshal(dst.GetTenantPackagesResponse)
		if string(jsonGetTenantPackagesResponse) == "{}" { // empty struct
			dst.GetTenantPackagesResponse = nil
		} else {
			return nil // data stored in dst.GetTenantPackagesResponse, return on the first match
		}
	} else {
		dst.GetTenantPackagesResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetTenantPackages200Response)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetTenantPackages200Response) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.GetTenantPackagesResponse != nil {
		return json.Marshal(&src.GetTenantPackagesResponse)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableGetTenantPackages200Response struct {
	value *GetTenantPackages200Response
	isSet bool
}

func (v NullableGetTenantPackages200Response) Get() *GetTenantPackages200Response {
	return v.value
}

func (v *NullableGetTenantPackages200Response) Set(val *GetTenantPackages200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTenantPackages200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTenantPackages200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTenantPackages200Response(val *GetTenantPackages200Response) *NullableGetTenantPackages200Response {
	return &NullableGetTenantPackages200Response{value: val, isSet: true}
}

func (v NullableGetTenantPackages200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTenantPackages200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


