/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
)

// checks if the CommentLogData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommentLogData{}

// CommentLogData struct for CommentLogData
type CommentLogData struct {
	ClearContent *bool `json:"clearContent,omitempty"`
	IsDeletedUser *bool `json:"isDeletedUser,omitempty"`
	Phrase *string `json:"phrase,omitempty"`
	BadWord *string `json:"badWord,omitempty"`
	Word *string `json:"word,omitempty"`
	Locale *string `json:"locale,omitempty"`
	TenantBadgeId *string `json:"tenantBadgeId,omitempty"`
	BadgeId *string `json:"badgeId,omitempty"`
	WasLoggedIn *bool `json:"wasLoggedIn,omitempty"`
	FoundUser *bool `json:"foundUser,omitempty"`
	Verified *bool `json:"verified,omitempty"`
	Engine *string `json:"engine,omitempty"`
	EngineResponse *string `json:"engineResponse,omitempty"`
	EngineTokens *float64 `json:"engineTokens,omitempty"`
	TrustFactor *float64 `json:"trustFactor,omitempty"`
	Rule *SpamRule `json:"rule,omitempty"`
	UserId *string `json:"userId,omitempty"`
	Subscribers *float64 `json:"subscribers,omitempty"`
	NotificationCount *float64 `json:"notificationCount,omitempty"`
	VotesBefore NullableFloat64 `json:"votesBefore,omitempty"`
	VotesUpBefore NullableFloat64 `json:"votesUpBefore,omitempty"`
	VotesDownBefore NullableFloat64 `json:"votesDownBefore,omitempty"`
	VotesAfter NullableFloat64 `json:"votesAfter,omitempty"`
	VotesUpAfter NullableFloat64 `json:"votesUpAfter,omitempty"`
	VotesDownAfter NullableFloat64 `json:"votesDownAfter,omitempty"`
	RepeatAction *RepeatCommentHandlingAction `json:"repeatAction,omitempty"`
	Reason *RepeatCommentCheckIgnoredReason `json:"reason,omitempty"`
	OtherData interface{} `json:"otherData,omitempty"`
	SpamBefore *bool `json:"spamBefore,omitempty"`
	SpamAfter *bool `json:"spamAfter,omitempty"`
	PermanentFlag *string `json:"permanentFlag,omitempty"`
	ApprovedBefore *bool `json:"approvedBefore,omitempty"`
	ApprovedAfter *bool `json:"approvedAfter,omitempty"`
	ReviewedBefore *bool `json:"reviewedBefore,omitempty"`
	ReviewedAfter *bool `json:"reviewedAfter,omitempty"`
	TextBefore *string `json:"textBefore,omitempty"`
	TextAfter *string `json:"textAfter,omitempty"`
	ExpireBefore NullableTime `json:"expireBefore,omitempty"`
	ExpireAfter NullableTime `json:"expireAfter,omitempty"`
	FlagCountBefore NullableFloat64 `json:"flagCountBefore,omitempty"`
	TrustFactorBefore *float64 `json:"trustFactorBefore,omitempty"`
	TrustFactorAfter *float64 `json:"trustFactorAfter,omitempty"`
	ReferencedCommentId *string `json:"referencedCommentId,omitempty"`
}

// NewCommentLogData instantiates a new CommentLogData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommentLogData() *CommentLogData {
	this := CommentLogData{}
	return &this
}

// NewCommentLogDataWithDefaults instantiates a new CommentLogData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommentLogDataWithDefaults() *CommentLogData {
	this := CommentLogData{}
	return &this
}

// GetClearContent returns the ClearContent field value if set, zero value otherwise.
func (o *CommentLogData) GetClearContent() bool {
	if o == nil || IsNil(o.ClearContent) {
		var ret bool
		return ret
	}
	return *o.ClearContent
}

// GetClearContentOk returns a tuple with the ClearContent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetClearContentOk() (*bool, bool) {
	if o == nil || IsNil(o.ClearContent) {
		return nil, false
	}
	return o.ClearContent, true
}

// HasClearContent returns a boolean if a field has been set.
func (o *CommentLogData) HasClearContent() bool {
	if o != nil && !IsNil(o.ClearContent) {
		return true
	}

	return false
}

// SetClearContent gets a reference to the given bool and assigns it to the ClearContent field.
func (o *CommentLogData) SetClearContent(v bool) {
	o.ClearContent = &v
}

// GetIsDeletedUser returns the IsDeletedUser field value if set, zero value otherwise.
func (o *CommentLogData) GetIsDeletedUser() bool {
	if o == nil || IsNil(o.IsDeletedUser) {
		var ret bool
		return ret
	}
	return *o.IsDeletedUser
}

// GetIsDeletedUserOk returns a tuple with the IsDeletedUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetIsDeletedUserOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDeletedUser) {
		return nil, false
	}
	return o.IsDeletedUser, true
}

// HasIsDeletedUser returns a boolean if a field has been set.
func (o *CommentLogData) HasIsDeletedUser() bool {
	if o != nil && !IsNil(o.IsDeletedUser) {
		return true
	}

	return false
}

// SetIsDeletedUser gets a reference to the given bool and assigns it to the IsDeletedUser field.
func (o *CommentLogData) SetIsDeletedUser(v bool) {
	o.IsDeletedUser = &v
}

// GetPhrase returns the Phrase field value if set, zero value otherwise.
func (o *CommentLogData) GetPhrase() string {
	if o == nil || IsNil(o.Phrase) {
		var ret string
		return ret
	}
	return *o.Phrase
}

// GetPhraseOk returns a tuple with the Phrase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetPhraseOk() (*string, bool) {
	if o == nil || IsNil(o.Phrase) {
		return nil, false
	}
	return o.Phrase, true
}

// HasPhrase returns a boolean if a field has been set.
func (o *CommentLogData) HasPhrase() bool {
	if o != nil && !IsNil(o.Phrase) {
		return true
	}

	return false
}

// SetPhrase gets a reference to the given string and assigns it to the Phrase field.
func (o *CommentLogData) SetPhrase(v string) {
	o.Phrase = &v
}

// GetBadWord returns the BadWord field value if set, zero value otherwise.
func (o *CommentLogData) GetBadWord() string {
	if o == nil || IsNil(o.BadWord) {
		var ret string
		return ret
	}
	return *o.BadWord
}

// GetBadWordOk returns a tuple with the BadWord field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetBadWordOk() (*string, bool) {
	if o == nil || IsNil(o.BadWord) {
		return nil, false
	}
	return o.BadWord, true
}

// HasBadWord returns a boolean if a field has been set.
func (o *CommentLogData) HasBadWord() bool {
	if o != nil && !IsNil(o.BadWord) {
		return true
	}

	return false
}

// SetBadWord gets a reference to the given string and assigns it to the BadWord field.
func (o *CommentLogData) SetBadWord(v string) {
	o.BadWord = &v
}

// GetWord returns the Word field value if set, zero value otherwise.
func (o *CommentLogData) GetWord() string {
	if o == nil || IsNil(o.Word) {
		var ret string
		return ret
	}
	return *o.Word
}

// GetWordOk returns a tuple with the Word field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetWordOk() (*string, bool) {
	if o == nil || IsNil(o.Word) {
		return nil, false
	}
	return o.Word, true
}

// HasWord returns a boolean if a field has been set.
func (o *CommentLogData) HasWord() bool {
	if o != nil && !IsNil(o.Word) {
		return true
	}

	return false
}

// SetWord gets a reference to the given string and assigns it to the Word field.
func (o *CommentLogData) SetWord(v string) {
	o.Word = &v
}

// GetLocale returns the Locale field value if set, zero value otherwise.
func (o *CommentLogData) GetLocale() string {
	if o == nil || IsNil(o.Locale) {
		var ret string
		return ret
	}
	return *o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetLocaleOk() (*string, bool) {
	if o == nil || IsNil(o.Locale) {
		return nil, false
	}
	return o.Locale, true
}

// HasLocale returns a boolean if a field has been set.
func (o *CommentLogData) HasLocale() bool {
	if o != nil && !IsNil(o.Locale) {
		return true
	}

	return false
}

// SetLocale gets a reference to the given string and assigns it to the Locale field.
func (o *CommentLogData) SetLocale(v string) {
	o.Locale = &v
}

// GetTenantBadgeId returns the TenantBadgeId field value if set, zero value otherwise.
func (o *CommentLogData) GetTenantBadgeId() string {
	if o == nil || IsNil(o.TenantBadgeId) {
		var ret string
		return ret
	}
	return *o.TenantBadgeId
}

// GetTenantBadgeIdOk returns a tuple with the TenantBadgeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetTenantBadgeIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantBadgeId) {
		return nil, false
	}
	return o.TenantBadgeId, true
}

// HasTenantBadgeId returns a boolean if a field has been set.
func (o *CommentLogData) HasTenantBadgeId() bool {
	if o != nil && !IsNil(o.TenantBadgeId) {
		return true
	}

	return false
}

// SetTenantBadgeId gets a reference to the given string and assigns it to the TenantBadgeId field.
func (o *CommentLogData) SetTenantBadgeId(v string) {
	o.TenantBadgeId = &v
}

// GetBadgeId returns the BadgeId field value if set, zero value otherwise.
func (o *CommentLogData) GetBadgeId() string {
	if o == nil || IsNil(o.BadgeId) {
		var ret string
		return ret
	}
	return *o.BadgeId
}

// GetBadgeIdOk returns a tuple with the BadgeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetBadgeIdOk() (*string, bool) {
	if o == nil || IsNil(o.BadgeId) {
		return nil, false
	}
	return o.BadgeId, true
}

// HasBadgeId returns a boolean if a field has been set.
func (o *CommentLogData) HasBadgeId() bool {
	if o != nil && !IsNil(o.BadgeId) {
		return true
	}

	return false
}

// SetBadgeId gets a reference to the given string and assigns it to the BadgeId field.
func (o *CommentLogData) SetBadgeId(v string) {
	o.BadgeId = &v
}

// GetWasLoggedIn returns the WasLoggedIn field value if set, zero value otherwise.
func (o *CommentLogData) GetWasLoggedIn() bool {
	if o == nil || IsNil(o.WasLoggedIn) {
		var ret bool
		return ret
	}
	return *o.WasLoggedIn
}

// GetWasLoggedInOk returns a tuple with the WasLoggedIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetWasLoggedInOk() (*bool, bool) {
	if o == nil || IsNil(o.WasLoggedIn) {
		return nil, false
	}
	return o.WasLoggedIn, true
}

// HasWasLoggedIn returns a boolean if a field has been set.
func (o *CommentLogData) HasWasLoggedIn() bool {
	if o != nil && !IsNil(o.WasLoggedIn) {
		return true
	}

	return false
}

// SetWasLoggedIn gets a reference to the given bool and assigns it to the WasLoggedIn field.
func (o *CommentLogData) SetWasLoggedIn(v bool) {
	o.WasLoggedIn = &v
}

// GetFoundUser returns the FoundUser field value if set, zero value otherwise.
func (o *CommentLogData) GetFoundUser() bool {
	if o == nil || IsNil(o.FoundUser) {
		var ret bool
		return ret
	}
	return *o.FoundUser
}

// GetFoundUserOk returns a tuple with the FoundUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetFoundUserOk() (*bool, bool) {
	if o == nil || IsNil(o.FoundUser) {
		return nil, false
	}
	return o.FoundUser, true
}

// HasFoundUser returns a boolean if a field has been set.
func (o *CommentLogData) HasFoundUser() bool {
	if o != nil && !IsNil(o.FoundUser) {
		return true
	}

	return false
}

// SetFoundUser gets a reference to the given bool and assigns it to the FoundUser field.
func (o *CommentLogData) SetFoundUser(v bool) {
	o.FoundUser = &v
}

// GetVerified returns the Verified field value if set, zero value otherwise.
func (o *CommentLogData) GetVerified() bool {
	if o == nil || IsNil(o.Verified) {
		var ret bool
		return ret
	}
	return *o.Verified
}

// GetVerifiedOk returns a tuple with the Verified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetVerifiedOk() (*bool, bool) {
	if o == nil || IsNil(o.Verified) {
		return nil, false
	}
	return o.Verified, true
}

// HasVerified returns a boolean if a field has been set.
func (o *CommentLogData) HasVerified() bool {
	if o != nil && !IsNil(o.Verified) {
		return true
	}

	return false
}

// SetVerified gets a reference to the given bool and assigns it to the Verified field.
func (o *CommentLogData) SetVerified(v bool) {
	o.Verified = &v
}

// GetEngine returns the Engine field value if set, zero value otherwise.
func (o *CommentLogData) GetEngine() string {
	if o == nil || IsNil(o.Engine) {
		var ret string
		return ret
	}
	return *o.Engine
}

// GetEngineOk returns a tuple with the Engine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetEngineOk() (*string, bool) {
	if o == nil || IsNil(o.Engine) {
		return nil, false
	}
	return o.Engine, true
}

// HasEngine returns a boolean if a field has been set.
func (o *CommentLogData) HasEngine() bool {
	if o != nil && !IsNil(o.Engine) {
		return true
	}

	return false
}

// SetEngine gets a reference to the given string and assigns it to the Engine field.
func (o *CommentLogData) SetEngine(v string) {
	o.Engine = &v
}

// GetEngineResponse returns the EngineResponse field value if set, zero value otherwise.
func (o *CommentLogData) GetEngineResponse() string {
	if o == nil || IsNil(o.EngineResponse) {
		var ret string
		return ret
	}
	return *o.EngineResponse
}

// GetEngineResponseOk returns a tuple with the EngineResponse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetEngineResponseOk() (*string, bool) {
	if o == nil || IsNil(o.EngineResponse) {
		return nil, false
	}
	return o.EngineResponse, true
}

// HasEngineResponse returns a boolean if a field has been set.
func (o *CommentLogData) HasEngineResponse() bool {
	if o != nil && !IsNil(o.EngineResponse) {
		return true
	}

	return false
}

// SetEngineResponse gets a reference to the given string and assigns it to the EngineResponse field.
func (o *CommentLogData) SetEngineResponse(v string) {
	o.EngineResponse = &v
}

// GetEngineTokens returns the EngineTokens field value if set, zero value otherwise.
func (o *CommentLogData) GetEngineTokens() float64 {
	if o == nil || IsNil(o.EngineTokens) {
		var ret float64
		return ret
	}
	return *o.EngineTokens
}

// GetEngineTokensOk returns a tuple with the EngineTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetEngineTokensOk() (*float64, bool) {
	if o == nil || IsNil(o.EngineTokens) {
		return nil, false
	}
	return o.EngineTokens, true
}

// HasEngineTokens returns a boolean if a field has been set.
func (o *CommentLogData) HasEngineTokens() bool {
	if o != nil && !IsNil(o.EngineTokens) {
		return true
	}

	return false
}

// SetEngineTokens gets a reference to the given float64 and assigns it to the EngineTokens field.
func (o *CommentLogData) SetEngineTokens(v float64) {
	o.EngineTokens = &v
}

// GetTrustFactor returns the TrustFactor field value if set, zero value otherwise.
func (o *CommentLogData) GetTrustFactor() float64 {
	if o == nil || IsNil(o.TrustFactor) {
		var ret float64
		return ret
	}
	return *o.TrustFactor
}

// GetTrustFactorOk returns a tuple with the TrustFactor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetTrustFactorOk() (*float64, bool) {
	if o == nil || IsNil(o.TrustFactor) {
		return nil, false
	}
	return o.TrustFactor, true
}

// HasTrustFactor returns a boolean if a field has been set.
func (o *CommentLogData) HasTrustFactor() bool {
	if o != nil && !IsNil(o.TrustFactor) {
		return true
	}

	return false
}

// SetTrustFactor gets a reference to the given float64 and assigns it to the TrustFactor field.
func (o *CommentLogData) SetTrustFactor(v float64) {
	o.TrustFactor = &v
}

// GetRule returns the Rule field value if set, zero value otherwise.
func (o *CommentLogData) GetRule() SpamRule {
	if o == nil || IsNil(o.Rule) {
		var ret SpamRule
		return ret
	}
	return *o.Rule
}

// GetRuleOk returns a tuple with the Rule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetRuleOk() (*SpamRule, bool) {
	if o == nil || IsNil(o.Rule) {
		return nil, false
	}
	return o.Rule, true
}

// HasRule returns a boolean if a field has been set.
func (o *CommentLogData) HasRule() bool {
	if o != nil && !IsNil(o.Rule) {
		return true
	}

	return false
}

// SetRule gets a reference to the given SpamRule and assigns it to the Rule field.
func (o *CommentLogData) SetRule(v SpamRule) {
	o.Rule = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *CommentLogData) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *CommentLogData) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *CommentLogData) SetUserId(v string) {
	o.UserId = &v
}

// GetSubscribers returns the Subscribers field value if set, zero value otherwise.
func (o *CommentLogData) GetSubscribers() float64 {
	if o == nil || IsNil(o.Subscribers) {
		var ret float64
		return ret
	}
	return *o.Subscribers
}

// GetSubscribersOk returns a tuple with the Subscribers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetSubscribersOk() (*float64, bool) {
	if o == nil || IsNil(o.Subscribers) {
		return nil, false
	}
	return o.Subscribers, true
}

// HasSubscribers returns a boolean if a field has been set.
func (o *CommentLogData) HasSubscribers() bool {
	if o != nil && !IsNil(o.Subscribers) {
		return true
	}

	return false
}

// SetSubscribers gets a reference to the given float64 and assigns it to the Subscribers field.
func (o *CommentLogData) SetSubscribers(v float64) {
	o.Subscribers = &v
}

// GetNotificationCount returns the NotificationCount field value if set, zero value otherwise.
func (o *CommentLogData) GetNotificationCount() float64 {
	if o == nil || IsNil(o.NotificationCount) {
		var ret float64
		return ret
	}
	return *o.NotificationCount
}

// GetNotificationCountOk returns a tuple with the NotificationCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetNotificationCountOk() (*float64, bool) {
	if o == nil || IsNil(o.NotificationCount) {
		return nil, false
	}
	return o.NotificationCount, true
}

// HasNotificationCount returns a boolean if a field has been set.
func (o *CommentLogData) HasNotificationCount() bool {
	if o != nil && !IsNil(o.NotificationCount) {
		return true
	}

	return false
}

// SetNotificationCount gets a reference to the given float64 and assigns it to the NotificationCount field.
func (o *CommentLogData) SetNotificationCount(v float64) {
	o.NotificationCount = &v
}

// GetVotesBefore returns the VotesBefore field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CommentLogData) GetVotesBefore() float64 {
	if o == nil || IsNil(o.VotesBefore.Get()) {
		var ret float64
		return ret
	}
	return *o.VotesBefore.Get()
}

// GetVotesBeforeOk returns a tuple with the VotesBefore field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CommentLogData) GetVotesBeforeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.VotesBefore.Get(), o.VotesBefore.IsSet()
}

// HasVotesBefore returns a boolean if a field has been set.
func (o *CommentLogData) HasVotesBefore() bool {
	if o != nil && o.VotesBefore.IsSet() {
		return true
	}

	return false
}

// SetVotesBefore gets a reference to the given NullableFloat64 and assigns it to the VotesBefore field.
func (o *CommentLogData) SetVotesBefore(v float64) {
	o.VotesBefore.Set(&v)
}
// SetVotesBeforeNil sets the value for VotesBefore to be an explicit nil
func (o *CommentLogData) SetVotesBeforeNil() {
	o.VotesBefore.Set(nil)
}

// UnsetVotesBefore ensures that no value is present for VotesBefore, not even an explicit nil
func (o *CommentLogData) UnsetVotesBefore() {
	o.VotesBefore.Unset()
}

// GetVotesUpBefore returns the VotesUpBefore field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CommentLogData) GetVotesUpBefore() float64 {
	if o == nil || IsNil(o.VotesUpBefore.Get()) {
		var ret float64
		return ret
	}
	return *o.VotesUpBefore.Get()
}

// GetVotesUpBeforeOk returns a tuple with the VotesUpBefore field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CommentLogData) GetVotesUpBeforeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.VotesUpBefore.Get(), o.VotesUpBefore.IsSet()
}

// HasVotesUpBefore returns a boolean if a field has been set.
func (o *CommentLogData) HasVotesUpBefore() bool {
	if o != nil && o.VotesUpBefore.IsSet() {
		return true
	}

	return false
}

// SetVotesUpBefore gets a reference to the given NullableFloat64 and assigns it to the VotesUpBefore field.
func (o *CommentLogData) SetVotesUpBefore(v float64) {
	o.VotesUpBefore.Set(&v)
}
// SetVotesUpBeforeNil sets the value for VotesUpBefore to be an explicit nil
func (o *CommentLogData) SetVotesUpBeforeNil() {
	o.VotesUpBefore.Set(nil)
}

// UnsetVotesUpBefore ensures that no value is present for VotesUpBefore, not even an explicit nil
func (o *CommentLogData) UnsetVotesUpBefore() {
	o.VotesUpBefore.Unset()
}

// GetVotesDownBefore returns the VotesDownBefore field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CommentLogData) GetVotesDownBefore() float64 {
	if o == nil || IsNil(o.VotesDownBefore.Get()) {
		var ret float64
		return ret
	}
	return *o.VotesDownBefore.Get()
}

// GetVotesDownBeforeOk returns a tuple with the VotesDownBefore field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CommentLogData) GetVotesDownBeforeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.VotesDownBefore.Get(), o.VotesDownBefore.IsSet()
}

// HasVotesDownBefore returns a boolean if a field has been set.
func (o *CommentLogData) HasVotesDownBefore() bool {
	if o != nil && o.VotesDownBefore.IsSet() {
		return true
	}

	return false
}

// SetVotesDownBefore gets a reference to the given NullableFloat64 and assigns it to the VotesDownBefore field.
func (o *CommentLogData) SetVotesDownBefore(v float64) {
	o.VotesDownBefore.Set(&v)
}
// SetVotesDownBeforeNil sets the value for VotesDownBefore to be an explicit nil
func (o *CommentLogData) SetVotesDownBeforeNil() {
	o.VotesDownBefore.Set(nil)
}

// UnsetVotesDownBefore ensures that no value is present for VotesDownBefore, not even an explicit nil
func (o *CommentLogData) UnsetVotesDownBefore() {
	o.VotesDownBefore.Unset()
}

// GetVotesAfter returns the VotesAfter field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CommentLogData) GetVotesAfter() float64 {
	if o == nil || IsNil(o.VotesAfter.Get()) {
		var ret float64
		return ret
	}
	return *o.VotesAfter.Get()
}

// GetVotesAfterOk returns a tuple with the VotesAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CommentLogData) GetVotesAfterOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.VotesAfter.Get(), o.VotesAfter.IsSet()
}

// HasVotesAfter returns a boolean if a field has been set.
func (o *CommentLogData) HasVotesAfter() bool {
	if o != nil && o.VotesAfter.IsSet() {
		return true
	}

	return false
}

// SetVotesAfter gets a reference to the given NullableFloat64 and assigns it to the VotesAfter field.
func (o *CommentLogData) SetVotesAfter(v float64) {
	o.VotesAfter.Set(&v)
}
// SetVotesAfterNil sets the value for VotesAfter to be an explicit nil
func (o *CommentLogData) SetVotesAfterNil() {
	o.VotesAfter.Set(nil)
}

// UnsetVotesAfter ensures that no value is present for VotesAfter, not even an explicit nil
func (o *CommentLogData) UnsetVotesAfter() {
	o.VotesAfter.Unset()
}

// GetVotesUpAfter returns the VotesUpAfter field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CommentLogData) GetVotesUpAfter() float64 {
	if o == nil || IsNil(o.VotesUpAfter.Get()) {
		var ret float64
		return ret
	}
	return *o.VotesUpAfter.Get()
}

// GetVotesUpAfterOk returns a tuple with the VotesUpAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CommentLogData) GetVotesUpAfterOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.VotesUpAfter.Get(), o.VotesUpAfter.IsSet()
}

// HasVotesUpAfter returns a boolean if a field has been set.
func (o *CommentLogData) HasVotesUpAfter() bool {
	if o != nil && o.VotesUpAfter.IsSet() {
		return true
	}

	return false
}

// SetVotesUpAfter gets a reference to the given NullableFloat64 and assigns it to the VotesUpAfter field.
func (o *CommentLogData) SetVotesUpAfter(v float64) {
	o.VotesUpAfter.Set(&v)
}
// SetVotesUpAfterNil sets the value for VotesUpAfter to be an explicit nil
func (o *CommentLogData) SetVotesUpAfterNil() {
	o.VotesUpAfter.Set(nil)
}

// UnsetVotesUpAfter ensures that no value is present for VotesUpAfter, not even an explicit nil
func (o *CommentLogData) UnsetVotesUpAfter() {
	o.VotesUpAfter.Unset()
}

// GetVotesDownAfter returns the VotesDownAfter field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CommentLogData) GetVotesDownAfter() float64 {
	if o == nil || IsNil(o.VotesDownAfter.Get()) {
		var ret float64
		return ret
	}
	return *o.VotesDownAfter.Get()
}

// GetVotesDownAfterOk returns a tuple with the VotesDownAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CommentLogData) GetVotesDownAfterOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.VotesDownAfter.Get(), o.VotesDownAfter.IsSet()
}

// HasVotesDownAfter returns a boolean if a field has been set.
func (o *CommentLogData) HasVotesDownAfter() bool {
	if o != nil && o.VotesDownAfter.IsSet() {
		return true
	}

	return false
}

// SetVotesDownAfter gets a reference to the given NullableFloat64 and assigns it to the VotesDownAfter field.
func (o *CommentLogData) SetVotesDownAfter(v float64) {
	o.VotesDownAfter.Set(&v)
}
// SetVotesDownAfterNil sets the value for VotesDownAfter to be an explicit nil
func (o *CommentLogData) SetVotesDownAfterNil() {
	o.VotesDownAfter.Set(nil)
}

// UnsetVotesDownAfter ensures that no value is present for VotesDownAfter, not even an explicit nil
func (o *CommentLogData) UnsetVotesDownAfter() {
	o.VotesDownAfter.Unset()
}

// GetRepeatAction returns the RepeatAction field value if set, zero value otherwise.
func (o *CommentLogData) GetRepeatAction() RepeatCommentHandlingAction {
	if o == nil || IsNil(o.RepeatAction) {
		var ret RepeatCommentHandlingAction
		return ret
	}
	return *o.RepeatAction
}

// GetRepeatActionOk returns a tuple with the RepeatAction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetRepeatActionOk() (*RepeatCommentHandlingAction, bool) {
	if o == nil || IsNil(o.RepeatAction) {
		return nil, false
	}
	return o.RepeatAction, true
}

// HasRepeatAction returns a boolean if a field has been set.
func (o *CommentLogData) HasRepeatAction() bool {
	if o != nil && !IsNil(o.RepeatAction) {
		return true
	}

	return false
}

// SetRepeatAction gets a reference to the given RepeatCommentHandlingAction and assigns it to the RepeatAction field.
func (o *CommentLogData) SetRepeatAction(v RepeatCommentHandlingAction) {
	o.RepeatAction = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *CommentLogData) GetReason() RepeatCommentCheckIgnoredReason {
	if o == nil || IsNil(o.Reason) {
		var ret RepeatCommentCheckIgnoredReason
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetReasonOk() (*RepeatCommentCheckIgnoredReason, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *CommentLogData) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given RepeatCommentCheckIgnoredReason and assigns it to the Reason field.
func (o *CommentLogData) SetReason(v RepeatCommentCheckIgnoredReason) {
	o.Reason = &v
}

// GetOtherData returns the OtherData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CommentLogData) GetOtherData() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.OtherData
}

// GetOtherDataOk returns a tuple with the OtherData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CommentLogData) GetOtherDataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.OtherData) {
		return nil, false
	}
	return &o.OtherData, true
}

// HasOtherData returns a boolean if a field has been set.
func (o *CommentLogData) HasOtherData() bool {
	if o != nil && !IsNil(o.OtherData) {
		return true
	}

	return false
}

// SetOtherData gets a reference to the given interface{} and assigns it to the OtherData field.
func (o *CommentLogData) SetOtherData(v interface{}) {
	o.OtherData = v
}

// GetSpamBefore returns the SpamBefore field value if set, zero value otherwise.
func (o *CommentLogData) GetSpamBefore() bool {
	if o == nil || IsNil(o.SpamBefore) {
		var ret bool
		return ret
	}
	return *o.SpamBefore
}

// GetSpamBeforeOk returns a tuple with the SpamBefore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetSpamBeforeOk() (*bool, bool) {
	if o == nil || IsNil(o.SpamBefore) {
		return nil, false
	}
	return o.SpamBefore, true
}

// HasSpamBefore returns a boolean if a field has been set.
func (o *CommentLogData) HasSpamBefore() bool {
	if o != nil && !IsNil(o.SpamBefore) {
		return true
	}

	return false
}

// SetSpamBefore gets a reference to the given bool and assigns it to the SpamBefore field.
func (o *CommentLogData) SetSpamBefore(v bool) {
	o.SpamBefore = &v
}

// GetSpamAfter returns the SpamAfter field value if set, zero value otherwise.
func (o *CommentLogData) GetSpamAfter() bool {
	if o == nil || IsNil(o.SpamAfter) {
		var ret bool
		return ret
	}
	return *o.SpamAfter
}

// GetSpamAfterOk returns a tuple with the SpamAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetSpamAfterOk() (*bool, bool) {
	if o == nil || IsNil(o.SpamAfter) {
		return nil, false
	}
	return o.SpamAfter, true
}

// HasSpamAfter returns a boolean if a field has been set.
func (o *CommentLogData) HasSpamAfter() bool {
	if o != nil && !IsNil(o.SpamAfter) {
		return true
	}

	return false
}

// SetSpamAfter gets a reference to the given bool and assigns it to the SpamAfter field.
func (o *CommentLogData) SetSpamAfter(v bool) {
	o.SpamAfter = &v
}

// GetPermanentFlag returns the PermanentFlag field value if set, zero value otherwise.
func (o *CommentLogData) GetPermanentFlag() string {
	if o == nil || IsNil(o.PermanentFlag) {
		var ret string
		return ret
	}
	return *o.PermanentFlag
}

// GetPermanentFlagOk returns a tuple with the PermanentFlag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetPermanentFlagOk() (*string, bool) {
	if o == nil || IsNil(o.PermanentFlag) {
		return nil, false
	}
	return o.PermanentFlag, true
}

// HasPermanentFlag returns a boolean if a field has been set.
func (o *CommentLogData) HasPermanentFlag() bool {
	if o != nil && !IsNil(o.PermanentFlag) {
		return true
	}

	return false
}

// SetPermanentFlag gets a reference to the given string and assigns it to the PermanentFlag field.
func (o *CommentLogData) SetPermanentFlag(v string) {
	o.PermanentFlag = &v
}

// GetApprovedBefore returns the ApprovedBefore field value if set, zero value otherwise.
func (o *CommentLogData) GetApprovedBefore() bool {
	if o == nil || IsNil(o.ApprovedBefore) {
		var ret bool
		return ret
	}
	return *o.ApprovedBefore
}

// GetApprovedBeforeOk returns a tuple with the ApprovedBefore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetApprovedBeforeOk() (*bool, bool) {
	if o == nil || IsNil(o.ApprovedBefore) {
		return nil, false
	}
	return o.ApprovedBefore, true
}

// HasApprovedBefore returns a boolean if a field has been set.
func (o *CommentLogData) HasApprovedBefore() bool {
	if o != nil && !IsNil(o.ApprovedBefore) {
		return true
	}

	return false
}

// SetApprovedBefore gets a reference to the given bool and assigns it to the ApprovedBefore field.
func (o *CommentLogData) SetApprovedBefore(v bool) {
	o.ApprovedBefore = &v
}

// GetApprovedAfter returns the ApprovedAfter field value if set, zero value otherwise.
func (o *CommentLogData) GetApprovedAfter() bool {
	if o == nil || IsNil(o.ApprovedAfter) {
		var ret bool
		return ret
	}
	return *o.ApprovedAfter
}

// GetApprovedAfterOk returns a tuple with the ApprovedAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetApprovedAfterOk() (*bool, bool) {
	if o == nil || IsNil(o.ApprovedAfter) {
		return nil, false
	}
	return o.ApprovedAfter, true
}

// HasApprovedAfter returns a boolean if a field has been set.
func (o *CommentLogData) HasApprovedAfter() bool {
	if o != nil && !IsNil(o.ApprovedAfter) {
		return true
	}

	return false
}

// SetApprovedAfter gets a reference to the given bool and assigns it to the ApprovedAfter field.
func (o *CommentLogData) SetApprovedAfter(v bool) {
	o.ApprovedAfter = &v
}

// GetReviewedBefore returns the ReviewedBefore field value if set, zero value otherwise.
func (o *CommentLogData) GetReviewedBefore() bool {
	if o == nil || IsNil(o.ReviewedBefore) {
		var ret bool
		return ret
	}
	return *o.ReviewedBefore
}

// GetReviewedBeforeOk returns a tuple with the ReviewedBefore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetReviewedBeforeOk() (*bool, bool) {
	if o == nil || IsNil(o.ReviewedBefore) {
		return nil, false
	}
	return o.ReviewedBefore, true
}

// HasReviewedBefore returns a boolean if a field has been set.
func (o *CommentLogData) HasReviewedBefore() bool {
	if o != nil && !IsNil(o.ReviewedBefore) {
		return true
	}

	return false
}

// SetReviewedBefore gets a reference to the given bool and assigns it to the ReviewedBefore field.
func (o *CommentLogData) SetReviewedBefore(v bool) {
	o.ReviewedBefore = &v
}

// GetReviewedAfter returns the ReviewedAfter field value if set, zero value otherwise.
func (o *CommentLogData) GetReviewedAfter() bool {
	if o == nil || IsNil(o.ReviewedAfter) {
		var ret bool
		return ret
	}
	return *o.ReviewedAfter
}

// GetReviewedAfterOk returns a tuple with the ReviewedAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetReviewedAfterOk() (*bool, bool) {
	if o == nil || IsNil(o.ReviewedAfter) {
		return nil, false
	}
	return o.ReviewedAfter, true
}

// HasReviewedAfter returns a boolean if a field has been set.
func (o *CommentLogData) HasReviewedAfter() bool {
	if o != nil && !IsNil(o.ReviewedAfter) {
		return true
	}

	return false
}

// SetReviewedAfter gets a reference to the given bool and assigns it to the ReviewedAfter field.
func (o *CommentLogData) SetReviewedAfter(v bool) {
	o.ReviewedAfter = &v
}

// GetTextBefore returns the TextBefore field value if set, zero value otherwise.
func (o *CommentLogData) GetTextBefore() string {
	if o == nil || IsNil(o.TextBefore) {
		var ret string
		return ret
	}
	return *o.TextBefore
}

// GetTextBeforeOk returns a tuple with the TextBefore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetTextBeforeOk() (*string, bool) {
	if o == nil || IsNil(o.TextBefore) {
		return nil, false
	}
	return o.TextBefore, true
}

// HasTextBefore returns a boolean if a field has been set.
func (o *CommentLogData) HasTextBefore() bool {
	if o != nil && !IsNil(o.TextBefore) {
		return true
	}

	return false
}

// SetTextBefore gets a reference to the given string and assigns it to the TextBefore field.
func (o *CommentLogData) SetTextBefore(v string) {
	o.TextBefore = &v
}

// GetTextAfter returns the TextAfter field value if set, zero value otherwise.
func (o *CommentLogData) GetTextAfter() string {
	if o == nil || IsNil(o.TextAfter) {
		var ret string
		return ret
	}
	return *o.TextAfter
}

// GetTextAfterOk returns a tuple with the TextAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetTextAfterOk() (*string, bool) {
	if o == nil || IsNil(o.TextAfter) {
		return nil, false
	}
	return o.TextAfter, true
}

// HasTextAfter returns a boolean if a field has been set.
func (o *CommentLogData) HasTextAfter() bool {
	if o != nil && !IsNil(o.TextAfter) {
		return true
	}

	return false
}

// SetTextAfter gets a reference to the given string and assigns it to the TextAfter field.
func (o *CommentLogData) SetTextAfter(v string) {
	o.TextAfter = &v
}

// GetExpireBefore returns the ExpireBefore field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CommentLogData) GetExpireBefore() time.Time {
	if o == nil || IsNil(o.ExpireBefore.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ExpireBefore.Get()
}

// GetExpireBeforeOk returns a tuple with the ExpireBefore field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CommentLogData) GetExpireBeforeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpireBefore.Get(), o.ExpireBefore.IsSet()
}

// HasExpireBefore returns a boolean if a field has been set.
func (o *CommentLogData) HasExpireBefore() bool {
	if o != nil && o.ExpireBefore.IsSet() {
		return true
	}

	return false
}

// SetExpireBefore gets a reference to the given NullableTime and assigns it to the ExpireBefore field.
func (o *CommentLogData) SetExpireBefore(v time.Time) {
	o.ExpireBefore.Set(&v)
}
// SetExpireBeforeNil sets the value for ExpireBefore to be an explicit nil
func (o *CommentLogData) SetExpireBeforeNil() {
	o.ExpireBefore.Set(nil)
}

// UnsetExpireBefore ensures that no value is present for ExpireBefore, not even an explicit nil
func (o *CommentLogData) UnsetExpireBefore() {
	o.ExpireBefore.Unset()
}

// GetExpireAfter returns the ExpireAfter field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CommentLogData) GetExpireAfter() time.Time {
	if o == nil || IsNil(o.ExpireAfter.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ExpireAfter.Get()
}

// GetExpireAfterOk returns a tuple with the ExpireAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CommentLogData) GetExpireAfterOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpireAfter.Get(), o.ExpireAfter.IsSet()
}

// HasExpireAfter returns a boolean if a field has been set.
func (o *CommentLogData) HasExpireAfter() bool {
	if o != nil && o.ExpireAfter.IsSet() {
		return true
	}

	return false
}

// SetExpireAfter gets a reference to the given NullableTime and assigns it to the ExpireAfter field.
func (o *CommentLogData) SetExpireAfter(v time.Time) {
	o.ExpireAfter.Set(&v)
}
// SetExpireAfterNil sets the value for ExpireAfter to be an explicit nil
func (o *CommentLogData) SetExpireAfterNil() {
	o.ExpireAfter.Set(nil)
}

// UnsetExpireAfter ensures that no value is present for ExpireAfter, not even an explicit nil
func (o *CommentLogData) UnsetExpireAfter() {
	o.ExpireAfter.Unset()
}

// GetFlagCountBefore returns the FlagCountBefore field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CommentLogData) GetFlagCountBefore() float64 {
	if o == nil || IsNil(o.FlagCountBefore.Get()) {
		var ret float64
		return ret
	}
	return *o.FlagCountBefore.Get()
}

// GetFlagCountBeforeOk returns a tuple with the FlagCountBefore field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CommentLogData) GetFlagCountBeforeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.FlagCountBefore.Get(), o.FlagCountBefore.IsSet()
}

// HasFlagCountBefore returns a boolean if a field has been set.
func (o *CommentLogData) HasFlagCountBefore() bool {
	if o != nil && o.FlagCountBefore.IsSet() {
		return true
	}

	return false
}

// SetFlagCountBefore gets a reference to the given NullableFloat64 and assigns it to the FlagCountBefore field.
func (o *CommentLogData) SetFlagCountBefore(v float64) {
	o.FlagCountBefore.Set(&v)
}
// SetFlagCountBeforeNil sets the value for FlagCountBefore to be an explicit nil
func (o *CommentLogData) SetFlagCountBeforeNil() {
	o.FlagCountBefore.Set(nil)
}

// UnsetFlagCountBefore ensures that no value is present for FlagCountBefore, not even an explicit nil
func (o *CommentLogData) UnsetFlagCountBefore() {
	o.FlagCountBefore.Unset()
}

// GetTrustFactorBefore returns the TrustFactorBefore field value if set, zero value otherwise.
func (o *CommentLogData) GetTrustFactorBefore() float64 {
	if o == nil || IsNil(o.TrustFactorBefore) {
		var ret float64
		return ret
	}
	return *o.TrustFactorBefore
}

// GetTrustFactorBeforeOk returns a tuple with the TrustFactorBefore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetTrustFactorBeforeOk() (*float64, bool) {
	if o == nil || IsNil(o.TrustFactorBefore) {
		return nil, false
	}
	return o.TrustFactorBefore, true
}

// HasTrustFactorBefore returns a boolean if a field has been set.
func (o *CommentLogData) HasTrustFactorBefore() bool {
	if o != nil && !IsNil(o.TrustFactorBefore) {
		return true
	}

	return false
}

// SetTrustFactorBefore gets a reference to the given float64 and assigns it to the TrustFactorBefore field.
func (o *CommentLogData) SetTrustFactorBefore(v float64) {
	o.TrustFactorBefore = &v
}

// GetTrustFactorAfter returns the TrustFactorAfter field value if set, zero value otherwise.
func (o *CommentLogData) GetTrustFactorAfter() float64 {
	if o == nil || IsNil(o.TrustFactorAfter) {
		var ret float64
		return ret
	}
	return *o.TrustFactorAfter
}

// GetTrustFactorAfterOk returns a tuple with the TrustFactorAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetTrustFactorAfterOk() (*float64, bool) {
	if o == nil || IsNil(o.TrustFactorAfter) {
		return nil, false
	}
	return o.TrustFactorAfter, true
}

// HasTrustFactorAfter returns a boolean if a field has been set.
func (o *CommentLogData) HasTrustFactorAfter() bool {
	if o != nil && !IsNil(o.TrustFactorAfter) {
		return true
	}

	return false
}

// SetTrustFactorAfter gets a reference to the given float64 and assigns it to the TrustFactorAfter field.
func (o *CommentLogData) SetTrustFactorAfter(v float64) {
	o.TrustFactorAfter = &v
}

// GetReferencedCommentId returns the ReferencedCommentId field value if set, zero value otherwise.
func (o *CommentLogData) GetReferencedCommentId() string {
	if o == nil || IsNil(o.ReferencedCommentId) {
		var ret string
		return ret
	}
	return *o.ReferencedCommentId
}

// GetReferencedCommentIdOk returns a tuple with the ReferencedCommentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentLogData) GetReferencedCommentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ReferencedCommentId) {
		return nil, false
	}
	return o.ReferencedCommentId, true
}

// HasReferencedCommentId returns a boolean if a field has been set.
func (o *CommentLogData) HasReferencedCommentId() bool {
	if o != nil && !IsNil(o.ReferencedCommentId) {
		return true
	}

	return false
}

// SetReferencedCommentId gets a reference to the given string and assigns it to the ReferencedCommentId field.
func (o *CommentLogData) SetReferencedCommentId(v string) {
	o.ReferencedCommentId = &v
}

func (o CommentLogData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommentLogData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClearContent) {
		toSerialize["clearContent"] = o.ClearContent
	}
	if !IsNil(o.IsDeletedUser) {
		toSerialize["isDeletedUser"] = o.IsDeletedUser
	}
	if !IsNil(o.Phrase) {
		toSerialize["phrase"] = o.Phrase
	}
	if !IsNil(o.BadWord) {
		toSerialize["badWord"] = o.BadWord
	}
	if !IsNil(o.Word) {
		toSerialize["word"] = o.Word
	}
	if !IsNil(o.Locale) {
		toSerialize["locale"] = o.Locale
	}
	if !IsNil(o.TenantBadgeId) {
		toSerialize["tenantBadgeId"] = o.TenantBadgeId
	}
	if !IsNil(o.BadgeId) {
		toSerialize["badgeId"] = o.BadgeId
	}
	if !IsNil(o.WasLoggedIn) {
		toSerialize["wasLoggedIn"] = o.WasLoggedIn
	}
	if !IsNil(o.FoundUser) {
		toSerialize["foundUser"] = o.FoundUser
	}
	if !IsNil(o.Verified) {
		toSerialize["verified"] = o.Verified
	}
	if !IsNil(o.Engine) {
		toSerialize["engine"] = o.Engine
	}
	if !IsNil(o.EngineResponse) {
		toSerialize["engineResponse"] = o.EngineResponse
	}
	if !IsNil(o.EngineTokens) {
		toSerialize["engineTokens"] = o.EngineTokens
	}
	if !IsNil(o.TrustFactor) {
		toSerialize["trustFactor"] = o.TrustFactor
	}
	if !IsNil(o.Rule) {
		toSerialize["rule"] = o.Rule
	}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	if !IsNil(o.Subscribers) {
		toSerialize["subscribers"] = o.Subscribers
	}
	if !IsNil(o.NotificationCount) {
		toSerialize["notificationCount"] = o.NotificationCount
	}
	if o.VotesBefore.IsSet() {
		toSerialize["votesBefore"] = o.VotesBefore.Get()
	}
	if o.VotesUpBefore.IsSet() {
		toSerialize["votesUpBefore"] = o.VotesUpBefore.Get()
	}
	if o.VotesDownBefore.IsSet() {
		toSerialize["votesDownBefore"] = o.VotesDownBefore.Get()
	}
	if o.VotesAfter.IsSet() {
		toSerialize["votesAfter"] = o.VotesAfter.Get()
	}
	if o.VotesUpAfter.IsSet() {
		toSerialize["votesUpAfter"] = o.VotesUpAfter.Get()
	}
	if o.VotesDownAfter.IsSet() {
		toSerialize["votesDownAfter"] = o.VotesDownAfter.Get()
	}
	if !IsNil(o.RepeatAction) {
		toSerialize["repeatAction"] = o.RepeatAction
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	if o.OtherData != nil {
		toSerialize["otherData"] = o.OtherData
	}
	if !IsNil(o.SpamBefore) {
		toSerialize["spamBefore"] = o.SpamBefore
	}
	if !IsNil(o.SpamAfter) {
		toSerialize["spamAfter"] = o.SpamAfter
	}
	if !IsNil(o.PermanentFlag) {
		toSerialize["permanentFlag"] = o.PermanentFlag
	}
	if !IsNil(o.ApprovedBefore) {
		toSerialize["approvedBefore"] = o.ApprovedBefore
	}
	if !IsNil(o.ApprovedAfter) {
		toSerialize["approvedAfter"] = o.ApprovedAfter
	}
	if !IsNil(o.ReviewedBefore) {
		toSerialize["reviewedBefore"] = o.ReviewedBefore
	}
	if !IsNil(o.ReviewedAfter) {
		toSerialize["reviewedAfter"] = o.ReviewedAfter
	}
	if !IsNil(o.TextBefore) {
		toSerialize["textBefore"] = o.TextBefore
	}
	if !IsNil(o.TextAfter) {
		toSerialize["textAfter"] = o.TextAfter
	}
	if o.ExpireBefore.IsSet() {
		toSerialize["expireBefore"] = o.ExpireBefore.Get()
	}
	if o.ExpireAfter.IsSet() {
		toSerialize["expireAfter"] = o.ExpireAfter.Get()
	}
	if o.FlagCountBefore.IsSet() {
		toSerialize["flagCountBefore"] = o.FlagCountBefore.Get()
	}
	if !IsNil(o.TrustFactorBefore) {
		toSerialize["trustFactorBefore"] = o.TrustFactorBefore
	}
	if !IsNil(o.TrustFactorAfter) {
		toSerialize["trustFactorAfter"] = o.TrustFactorAfter
	}
	if !IsNil(o.ReferencedCommentId) {
		toSerialize["referencedCommentId"] = o.ReferencedCommentId
	}
	return toSerialize, nil
}

type NullableCommentLogData struct {
	value *CommentLogData
	isSet bool
}

func (v NullableCommentLogData) Get() *CommentLogData {
	return v.value
}

func (v *NullableCommentLogData) Set(val *CommentLogData) {
	v.value = val
	v.isSet = true
}

func (v NullableCommentLogData) IsSet() bool {
	return v.isSet
}

func (v *NullableCommentLogData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommentLogData(val *CommentLogData) *NullableCommentLogData {
	return &NullableCommentLogData{value: val, isSet: true}
}

func (v NullableCommentLogData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommentLogData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


