/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetBannedUsersCountResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetBannedUsersCountResponse{}

// GetBannedUsersCountResponse struct for GetBannedUsersCountResponse
type GetBannedUsersCountResponse struct {
	TotalCount float64 `json:"totalCount"`
	Status string `json:"status"`
}

type _GetBannedUsersCountResponse GetBannedUsersCountResponse

// NewGetBannedUsersCountResponse instantiates a new GetBannedUsersCountResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBannedUsersCountResponse(totalCount float64, status string) *GetBannedUsersCountResponse {
	this := GetBannedUsersCountResponse{}
	this.TotalCount = totalCount
	this.Status = status
	return &this
}

// NewGetBannedUsersCountResponseWithDefaults instantiates a new GetBannedUsersCountResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBannedUsersCountResponseWithDefaults() *GetBannedUsersCountResponse {
	this := GetBannedUsersCountResponse{}
	return &this
}

// GetTotalCount returns the TotalCount field value
func (o *GetBannedUsersCountResponse) GetTotalCount() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *GetBannedUsersCountResponse) GetTotalCountOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *GetBannedUsersCountResponse) SetTotalCount(v float64) {
	o.TotalCount = v
}

// GetStatus returns the Status field value
func (o *GetBannedUsersCountResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetBannedUsersCountResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetBannedUsersCountResponse) SetStatus(v string) {
	o.Status = v
}

func (o GetBannedUsersCountResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetBannedUsersCountResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["totalCount"] = o.TotalCount
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *GetBannedUsersCountResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"totalCount",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetBannedUsersCountResponse := _GetBannedUsersCountResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetBannedUsersCountResponse)

	if err != nil {
		return err
	}

	*o = GetBannedUsersCountResponse(varGetBannedUsersCountResponse)

	return err
}

type NullableGetBannedUsersCountResponse struct {
	value *GetBannedUsersCountResponse
	isSet bool
}

func (v NullableGetBannedUsersCountResponse) Get() *GetBannedUsersCountResponse {
	return v.value
}

func (v *NullableGetBannedUsersCountResponse) Set(val *GetBannedUsersCountResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBannedUsersCountResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBannedUsersCountResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBannedUsersCountResponse(val *GetBannedUsersCountResponse) *NullableGetBannedUsersCountResponse {
	return &NullableGetBannedUsersCountResponse{value: val, isSet: true}
}

func (v NullableGetBannedUsersCountResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBannedUsersCountResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


