/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// GetV2PageReactsResponse struct for GetV2PageReactsResponse
type GetV2PageReactsResponse struct {
	APIError *APIError
	GetV2PageReacts *GetV2PageReacts
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetV2PageReactsResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal JSON data into GetV2PageReacts
	err = json.Unmarshal(data, &dst.GetV2PageReacts);
	if err == nil {
		jsonGetV2PageReacts, _ := json.Marshal(dst.GetV2PageReacts)
		if string(jsonGetV2PageReacts) == "{}" { // empty struct
			dst.GetV2PageReacts = nil
		} else {
			return nil // data stored in dst.GetV2PageReacts, return on the first match
		}
	} else {
		dst.GetV2PageReacts = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetV2PageReactsResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetV2PageReactsResponse) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.GetV2PageReacts != nil {
		return json.Marshal(&src.GetV2PageReacts)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableGetV2PageReactsResponse struct {
	value *GetV2PageReactsResponse
	isSet bool
}

func (v NullableGetV2PageReactsResponse) Get() *GetV2PageReactsResponse {
	return v.value
}

func (v *NullableGetV2PageReactsResponse) Set(val *GetV2PageReactsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetV2PageReactsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetV2PageReactsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetV2PageReactsResponse(val *GetV2PageReactsResponse) *NullableGetV2PageReactsResponse {
	return &NullableGetV2PageReactsResponse{value: val, isSet: true}
}

func (v NullableGetV2PageReactsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetV2PageReactsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


