/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// RepeatCommentHandlingAction the model 'RepeatCommentHandlingAction'
type RepeatCommentHandlingAction float32

// List of RepeatCommentHandlingAction
const (
	REPEATCOMMENTHANDLINGACTION__0 RepeatCommentHandlingAction = 0
	REPEATCOMMENTHANDLINGACTION__1 RepeatCommentHandlingAction = 1
	REPEATCOMMENTHANDLINGACTION__2 RepeatCommentHandlingAction = 2
)

// All allowed values of RepeatCommentHandlingAction enum
var AllowedRepeatCommentHandlingActionEnumValues = []RepeatCommentHandlingAction{
	0,
	1,
	2,
}

func (v *RepeatCommentHandlingAction) UnmarshalJSON(src []byte) error {
	var value float32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RepeatCommentHandlingAction(value)
	for _, existing := range AllowedRepeatCommentHandlingActionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RepeatCommentHandlingAction", value)
}

// NewRepeatCommentHandlingActionFromValue returns a pointer to a valid RepeatCommentHandlingAction
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRepeatCommentHandlingActionFromValue(v float32) (*RepeatCommentHandlingAction, error) {
	ev := RepeatCommentHandlingAction(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RepeatCommentHandlingAction: valid values are %v", v, AllowedRepeatCommentHandlingActionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RepeatCommentHandlingAction) IsValid() bool {
	for _, existing := range AllowedRepeatCommentHandlingActionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RepeatCommentHandlingAction value
func (v RepeatCommentHandlingAction) Ptr() *RepeatCommentHandlingAction {
	return &v
}

type NullableRepeatCommentHandlingAction struct {
	value *RepeatCommentHandlingAction
	isSet bool
}

func (v NullableRepeatCommentHandlingAction) Get() *RepeatCommentHandlingAction {
	return v.value
}

func (v *NullableRepeatCommentHandlingAction) Set(val *RepeatCommentHandlingAction) {
	v.value = val
	v.isSet = true
}

func (v NullableRepeatCommentHandlingAction) IsSet() bool {
	return v.isSet
}

func (v *NullableRepeatCommentHandlingAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRepeatCommentHandlingAction(val *RepeatCommentHandlingAction) *NullableRepeatCommentHandlingAction {
	return &NullableRepeatCommentHandlingAction{value: val, isSet: true}
}

func (v NullableRepeatCommentHandlingAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRepeatCommentHandlingAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

