/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetDomainConfigs200ResponseAnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDomainConfigs200ResponseAnyOf{}

// GetDomainConfigs200ResponseAnyOf struct for GetDomainConfigs200ResponseAnyOf
type GetDomainConfigs200ResponseAnyOf struct {
	Configurations interface{} `json:"configurations"`
	Status interface{} `json:"status"`
}

type _GetDomainConfigs200ResponseAnyOf GetDomainConfigs200ResponseAnyOf

// NewGetDomainConfigs200ResponseAnyOf instantiates a new GetDomainConfigs200ResponseAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDomainConfigs200ResponseAnyOf(configurations interface{}, status interface{}) *GetDomainConfigs200ResponseAnyOf {
	this := GetDomainConfigs200ResponseAnyOf{}
	this.Configurations = configurations
	this.Status = status
	return &this
}

// NewGetDomainConfigs200ResponseAnyOfWithDefaults instantiates a new GetDomainConfigs200ResponseAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDomainConfigs200ResponseAnyOfWithDefaults() *GetDomainConfigs200ResponseAnyOf {
	this := GetDomainConfigs200ResponseAnyOf{}
	return &this
}

// GetConfigurations returns the Configurations field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *GetDomainConfigs200ResponseAnyOf) GetConfigurations() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Configurations
}

// GetConfigurationsOk returns a tuple with the Configurations field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDomainConfigs200ResponseAnyOf) GetConfigurationsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Configurations) {
		return nil, false
	}
	return &o.Configurations, true
}

// SetConfigurations sets field value
func (o *GetDomainConfigs200ResponseAnyOf) SetConfigurations(v interface{}) {
	o.Configurations = v
}

// GetStatus returns the Status field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *GetDomainConfigs200ResponseAnyOf) GetStatus() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDomainConfigs200ResponseAnyOf) GetStatusOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetDomainConfigs200ResponseAnyOf) SetStatus(v interface{}) {
	o.Status = v
}

func (o GetDomainConfigs200ResponseAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDomainConfigs200ResponseAnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Configurations != nil {
		toSerialize["configurations"] = o.Configurations
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

func (o *GetDomainConfigs200ResponseAnyOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"configurations",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetDomainConfigs200ResponseAnyOf := _GetDomainConfigs200ResponseAnyOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetDomainConfigs200ResponseAnyOf)

	if err != nil {
		return err
	}

	*o = GetDomainConfigs200ResponseAnyOf(varGetDomainConfigs200ResponseAnyOf)

	return err
}

type NullableGetDomainConfigs200ResponseAnyOf struct {
	value *GetDomainConfigs200ResponseAnyOf
	isSet bool
}

func (v NullableGetDomainConfigs200ResponseAnyOf) Get() *GetDomainConfigs200ResponseAnyOf {
	return v.value
}

func (v *NullableGetDomainConfigs200ResponseAnyOf) Set(val *GetDomainConfigs200ResponseAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDomainConfigs200ResponseAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDomainConfigs200ResponseAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDomainConfigs200ResponseAnyOf(val *GetDomainConfigs200ResponseAnyOf) *NullableGetDomainConfigs200ResponseAnyOf {
	return &NullableGetDomainConfigs200ResponseAnyOf{value: val, isSet: true}
}

func (v NullableGetDomainConfigs200ResponseAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDomainConfigs200ResponseAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


