/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the UserPresenceData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserPresenceData{}

// UserPresenceData struct for UserPresenceData
type UserPresenceData struct {
	UrlIdWS *string `json:"urlIdWS,omitempty"`
	UserIdWS *string `json:"userIdWS,omitempty"`
	TenantIdWS *string `json:"tenantIdWS,omitempty"`
}

// NewUserPresenceData instantiates a new UserPresenceData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserPresenceData() *UserPresenceData {
	this := UserPresenceData{}
	return &this
}

// NewUserPresenceDataWithDefaults instantiates a new UserPresenceData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserPresenceDataWithDefaults() *UserPresenceData {
	this := UserPresenceData{}
	return &this
}

// GetUrlIdWS returns the UrlIdWS field value if set, zero value otherwise.
func (o *UserPresenceData) GetUrlIdWS() string {
	if o == nil || IsNil(o.UrlIdWS) {
		var ret string
		return ret
	}
	return *o.UrlIdWS
}

// GetUrlIdWSOk returns a tuple with the UrlIdWS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserPresenceData) GetUrlIdWSOk() (*string, bool) {
	if o == nil || IsNil(o.UrlIdWS) {
		return nil, false
	}
	return o.UrlIdWS, true
}

// HasUrlIdWS returns a boolean if a field has been set.
func (o *UserPresenceData) HasUrlIdWS() bool {
	if o != nil && !IsNil(o.UrlIdWS) {
		return true
	}

	return false
}

// SetUrlIdWS gets a reference to the given string and assigns it to the UrlIdWS field.
func (o *UserPresenceData) SetUrlIdWS(v string) {
	o.UrlIdWS = &v
}

// GetUserIdWS returns the UserIdWS field value if set, zero value otherwise.
func (o *UserPresenceData) GetUserIdWS() string {
	if o == nil || IsNil(o.UserIdWS) {
		var ret string
		return ret
	}
	return *o.UserIdWS
}

// GetUserIdWSOk returns a tuple with the UserIdWS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserPresenceData) GetUserIdWSOk() (*string, bool) {
	if o == nil || IsNil(o.UserIdWS) {
		return nil, false
	}
	return o.UserIdWS, true
}

// HasUserIdWS returns a boolean if a field has been set.
func (o *UserPresenceData) HasUserIdWS() bool {
	if o != nil && !IsNil(o.UserIdWS) {
		return true
	}

	return false
}

// SetUserIdWS gets a reference to the given string and assigns it to the UserIdWS field.
func (o *UserPresenceData) SetUserIdWS(v string) {
	o.UserIdWS = &v
}

// GetTenantIdWS returns the TenantIdWS field value if set, zero value otherwise.
func (o *UserPresenceData) GetTenantIdWS() string {
	if o == nil || IsNil(o.TenantIdWS) {
		var ret string
		return ret
	}
	return *o.TenantIdWS
}

// GetTenantIdWSOk returns a tuple with the TenantIdWS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserPresenceData) GetTenantIdWSOk() (*string, bool) {
	if o == nil || IsNil(o.TenantIdWS) {
		return nil, false
	}
	return o.TenantIdWS, true
}

// HasTenantIdWS returns a boolean if a field has been set.
func (o *UserPresenceData) HasTenantIdWS() bool {
	if o != nil && !IsNil(o.TenantIdWS) {
		return true
	}

	return false
}

// SetTenantIdWS gets a reference to the given string and assigns it to the TenantIdWS field.
func (o *UserPresenceData) SetTenantIdWS(v string) {
	o.TenantIdWS = &v
}

func (o UserPresenceData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserPresenceData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UrlIdWS) {
		toSerialize["urlIdWS"] = o.UrlIdWS
	}
	if !IsNil(o.UserIdWS) {
		toSerialize["userIdWS"] = o.UserIdWS
	}
	if !IsNil(o.TenantIdWS) {
		toSerialize["tenantIdWS"] = o.TenantIdWS
	}
	return toSerialize, nil
}

type NullableUserPresenceData struct {
	value *UserPresenceData
	isSet bool
}

func (v NullableUserPresenceData) Get() *UserPresenceData {
	return v.value
}

func (v *NullableUserPresenceData) Set(val *UserPresenceData) {
	v.value = val
	v.isSet = true
}

func (v NullableUserPresenceData) IsSet() bool {
	return v.isSet
}

func (v *NullableUserPresenceData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserPresenceData(val *UserPresenceData) *NullableUserPresenceData {
	return &NullableUserPresenceData{value: val, isSet: true}
}

func (v NullableUserPresenceData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserPresenceData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


