/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// GetEmailTemplateRenderErrors200Response struct for GetEmailTemplateRenderErrors200Response
type GetEmailTemplateRenderErrors200Response struct {
	APIError *APIError
	GetEmailTemplateRenderErrorsResponse *GetEmailTemplateRenderErrorsResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetEmailTemplateRenderErrors200Response) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal JSON data into GetEmailTemplateRenderErrorsResponse
	err = json.Unmarshal(data, &dst.GetEmailTemplateRenderErrorsResponse);
	if err == nil {
		jsonGetEmailTemplateRenderErrorsResponse, _ := json.Marshal(dst.GetEmailTemplateRenderErrorsResponse)
		if string(jsonGetEmailTemplateRenderErrorsResponse) == "{}" { // empty struct
			dst.GetEmailTemplateRenderErrorsResponse = nil
		} else {
			return nil // data stored in dst.GetEmailTemplateRenderErrorsResponse, return on the first match
		}
	} else {
		dst.GetEmailTemplateRenderErrorsResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetEmailTemplateRenderErrors200Response)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetEmailTemplateRenderErrors200Response) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.GetEmailTemplateRenderErrorsResponse != nil {
		return json.Marshal(&src.GetEmailTemplateRenderErrorsResponse)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableGetEmailTemplateRenderErrors200Response struct {
	value *GetEmailTemplateRenderErrors200Response
	isSet bool
}

func (v NullableGetEmailTemplateRenderErrors200Response) Get() *GetEmailTemplateRenderErrors200Response {
	return v.value
}

func (v *NullableGetEmailTemplateRenderErrors200Response) Set(val *GetEmailTemplateRenderErrors200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEmailTemplateRenderErrors200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEmailTemplateRenderErrors200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEmailTemplateRenderErrors200Response(val *GetEmailTemplateRenderErrors200Response) *NullableGetEmailTemplateRenderErrors200Response {
	return &NullableGetEmailTemplateRenderErrors200Response{value: val, isSet: true}
}

func (v NullableGetEmailTemplateRenderErrors200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEmailTemplateRenderErrors200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


