/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the UnBlockFromCommentParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnBlockFromCommentParams{}

// UnBlockFromCommentParams struct for UnBlockFromCommentParams
type UnBlockFromCommentParams struct {
	CommentIdsToCheck []string `json:"commentIdsToCheck,omitempty"`
}

// NewUnBlockFromCommentParams instantiates a new UnBlockFromCommentParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnBlockFromCommentParams() *UnBlockFromCommentParams {
	this := UnBlockFromCommentParams{}
	return &this
}

// NewUnBlockFromCommentParamsWithDefaults instantiates a new UnBlockFromCommentParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnBlockFromCommentParamsWithDefaults() *UnBlockFromCommentParams {
	this := UnBlockFromCommentParams{}
	return &this
}

// GetCommentIdsToCheck returns the CommentIdsToCheck field value if set, zero value otherwise.
func (o *UnBlockFromCommentParams) GetCommentIdsToCheck() []string {
	if o == nil || IsNil(o.CommentIdsToCheck) {
		var ret []string
		return ret
	}
	return o.CommentIdsToCheck
}

// GetCommentIdsToCheckOk returns a tuple with the CommentIdsToCheck field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnBlockFromCommentParams) GetCommentIdsToCheckOk() ([]string, bool) {
	if o == nil || IsNil(o.CommentIdsToCheck) {
		return nil, false
	}
	return o.CommentIdsToCheck, true
}

// HasCommentIdsToCheck returns a boolean if a field has been set.
func (o *UnBlockFromCommentParams) HasCommentIdsToCheck() bool {
	if o != nil && !IsNil(o.CommentIdsToCheck) {
		return true
	}

	return false
}

// SetCommentIdsToCheck gets a reference to the given []string and assigns it to the CommentIdsToCheck field.
func (o *UnBlockFromCommentParams) SetCommentIdsToCheck(v []string) {
	o.CommentIdsToCheck = v
}

func (o UnBlockFromCommentParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnBlockFromCommentParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CommentIdsToCheck) {
		toSerialize["commentIdsToCheck"] = o.CommentIdsToCheck
	}
	return toSerialize, nil
}

type NullableUnBlockFromCommentParams struct {
	value *UnBlockFromCommentParams
	isSet bool
}

func (v NullableUnBlockFromCommentParams) Get() *UnBlockFromCommentParams {
	return v.value
}

func (v *NullableUnBlockFromCommentParams) Set(val *UnBlockFromCommentParams) {
	v.value = val
	v.isSet = true
}

func (v NullableUnBlockFromCommentParams) IsSet() bool {
	return v.isSet
}

func (v *NullableUnBlockFromCommentParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnBlockFromCommentParams(val *UnBlockFromCommentParams) *NullableUnBlockFromCommentParams {
	return &NullableUnBlockFromCommentParams{value: val, isSet: true}
}

func (v NullableUnBlockFromCommentParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnBlockFromCommentParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


