/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// NotificationObjectType the model 'NotificationObjectType'
type NotificationObjectType float32

// List of NotificationObjectType
const (
	NOTIFICATIONOBJECTTYPE__0 NotificationObjectType = 0
	NOTIFICATIONOBJECTTYPE__1 NotificationObjectType = 1
	NOTIFICATIONOBJECTTYPE__2 NotificationObjectType = 2
)

// All allowed values of NotificationObjectType enum
var AllowedNotificationObjectTypeEnumValues = []NotificationObjectType{
	0,
	1,
	2,
}

func (v *NotificationObjectType) UnmarshalJSON(src []byte) error {
	var value float32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := NotificationObjectType(value)
	for _, existing := range AllowedNotificationObjectTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid NotificationObjectType", value)
}

// NewNotificationObjectTypeFromValue returns a pointer to a valid NotificationObjectType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewNotificationObjectTypeFromValue(v float32) (*NotificationObjectType, error) {
	ev := NotificationObjectType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for NotificationObjectType: valid values are %v", v, AllowedNotificationObjectTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v NotificationObjectType) IsValid() bool {
	for _, existing := range AllowedNotificationObjectTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to NotificationObjectType value
func (v NotificationObjectType) Ptr() *NotificationObjectType {
	return &v
}

type NullableNotificationObjectType struct {
	value *NotificationObjectType
	isSet bool
}

func (v NullableNotificationObjectType) Get() *NotificationObjectType {
	return v.value
}

func (v *NullableNotificationObjectType) Set(val *NotificationObjectType) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationObjectType) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationObjectType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationObjectType(val *NotificationObjectType) *NullableNotificationObjectType {
	return &NullableNotificationObjectType{value: val, isSet: true}
}

func (v NullableNotificationObjectType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationObjectType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

