/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the TenantPackage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantPackage{}

// TenantPackage struct for TenantPackage
type TenantPackage struct {
	Id string `json:"_id"`
	Name string `json:"name"`
	TenantId string `json:"tenantId"`
	CreatedAt time.Time `json:"createdAt"`
	MonthlyCostUSD NullableFloat64 `json:"monthlyCostUSD"`
	YearlyCostUSD NullableFloat64 `json:"yearlyCostUSD"`
	MonthlyStripePlanId NullableString `json:"monthlyStripePlanId"`
	YearlyStripePlanId NullableString `json:"yearlyStripePlanId"`
	MaxMonthlyPageLoads float64 `json:"maxMonthlyPageLoads"`
	MaxMonthlyAPICredits float64 `json:"maxMonthlyAPICredits"`
	MaxMonthlySmallWidgetsCredits float64 `json:"maxMonthlySmallWidgetsCredits"`
	MaxMonthlyComments float64 `json:"maxMonthlyComments"`
	MaxConcurrentUsers float64 `json:"maxConcurrentUsers"`
	MaxTenantUsers float64 `json:"maxTenantUsers"`
	MaxSSOUsers float64 `json:"maxSSOUsers"`
	MaxModerators float64 `json:"maxModerators"`
	MaxDomains float64 `json:"maxDomains"`
	MaxWhiteLabeledTenants float64 `json:"maxWhiteLabeledTenants"`
	MaxMonthlyEventLogRequests float64 `json:"maxMonthlyEventLogRequests"`
	HasWhiteLabeling bool `json:"hasWhiteLabeling"`
	HasDebranding bool `json:"hasDebranding"`
	HasLLMSpamDetection bool `json:"hasLLMSpamDetection"`
	ForWhoText string `json:"forWhoText"`
	FeatureTaglines []string `json:"featureTaglines"`
	HasAuditing bool `json:"hasAuditing"`
	HasFlexPricing bool `json:"hasFlexPricing"`
	EnableSAML *bool `json:"enableSAML,omitempty"`
	FlexPageLoadCostCents *float64 `json:"flexPageLoadCostCents,omitempty"`
	FlexPageLoadUnit *float64 `json:"flexPageLoadUnit,omitempty"`
	FlexCommentCostCents *float64 `json:"flexCommentCostCents,omitempty"`
	FlexCommentUnit *float64 `json:"flexCommentUnit,omitempty"`
	FlexSSOUserCostCents *float64 `json:"flexSSOUserCostCents,omitempty"`
	FlexSSOUserUnit *float64 `json:"flexSSOUserUnit,omitempty"`
	FlexAPICreditCostCents *float64 `json:"flexAPICreditCostCents,omitempty"`
	FlexAPICreditUnit *float64 `json:"flexAPICreditUnit,omitempty"`
	FlexSmallWidgetsCreditCostCents *float64 `json:"flexSmallWidgetsCreditCostCents,omitempty"`
	FlexSmallWidgetsCreditUnit *float64 `json:"flexSmallWidgetsCreditUnit,omitempty"`
	FlexModeratorCostCents *float64 `json:"flexModeratorCostCents,omitempty"`
	FlexModeratorUnit *float64 `json:"flexModeratorUnit,omitempty"`
	FlexAdminCostCents *float64 `json:"flexAdminCostCents,omitempty"`
	FlexAdminUnit *float64 `json:"flexAdminUnit,omitempty"`
	FlexDomainCostCents *float64 `json:"flexDomainCostCents,omitempty"`
	FlexDomainUnit *float64 `json:"flexDomainUnit,omitempty"`
	FlexChatGPTCostCents *float64 `json:"flexChatGPTCostCents,omitempty"`
	FlexChatGPTUnit *float64 `json:"flexChatGPTUnit,omitempty"`
	FlexMinimumCostCents *float64 `json:"flexMinimumCostCents,omitempty"`
	FlexManagedTenantCostCents *float64 `json:"flexManagedTenantCostCents,omitempty"`
	FlexSSOAdminCostCents *float64 `json:"flexSSOAdminCostCents,omitempty"`
	FlexSSOAdminUnit *float64 `json:"flexSSOAdminUnit,omitempty"`
	FlexSSOModeratorCostCents *float64 `json:"flexSSOModeratorCostCents,omitempty"`
	FlexSSOModeratorUnit *float64 `json:"flexSSOModeratorUnit,omitempty"`
	IsSSOBillingMonthlyActiveUsers *bool `json:"isSSOBillingMonthlyActiveUsers,omitempty"`
}

type _TenantPackage TenantPackage

// NewTenantPackage instantiates a new TenantPackage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantPackage(id string, name string, tenantId string, createdAt time.Time, monthlyCostUSD NullableFloat64, yearlyCostUSD NullableFloat64, monthlyStripePlanId NullableString, yearlyStripePlanId NullableString, maxMonthlyPageLoads float64, maxMonthlyAPICredits float64, maxMonthlySmallWidgetsCredits float64, maxMonthlyComments float64, maxConcurrentUsers float64, maxTenantUsers float64, maxSSOUsers float64, maxModerators float64, maxDomains float64, maxWhiteLabeledTenants float64, maxMonthlyEventLogRequests float64, hasWhiteLabeling bool, hasDebranding bool, hasLLMSpamDetection bool, forWhoText string, featureTaglines []string, hasAuditing bool, hasFlexPricing bool) *TenantPackage {
	this := TenantPackage{}
	this.Id = id
	this.Name = name
	this.TenantId = tenantId
	this.CreatedAt = createdAt
	this.MonthlyCostUSD = monthlyCostUSD
	this.YearlyCostUSD = yearlyCostUSD
	this.MonthlyStripePlanId = monthlyStripePlanId
	this.YearlyStripePlanId = yearlyStripePlanId
	this.MaxMonthlyPageLoads = maxMonthlyPageLoads
	this.MaxMonthlyAPICredits = maxMonthlyAPICredits
	this.MaxMonthlySmallWidgetsCredits = maxMonthlySmallWidgetsCredits
	this.MaxMonthlyComments = maxMonthlyComments
	this.MaxConcurrentUsers = maxConcurrentUsers
	this.MaxTenantUsers = maxTenantUsers
	this.MaxSSOUsers = maxSSOUsers
	this.MaxModerators = maxModerators
	this.MaxDomains = maxDomains
	this.MaxWhiteLabeledTenants = maxWhiteLabeledTenants
	this.MaxMonthlyEventLogRequests = maxMonthlyEventLogRequests
	this.HasWhiteLabeling = hasWhiteLabeling
	this.HasDebranding = hasDebranding
	this.HasLLMSpamDetection = hasLLMSpamDetection
	this.ForWhoText = forWhoText
	this.FeatureTaglines = featureTaglines
	this.HasAuditing = hasAuditing
	this.HasFlexPricing = hasFlexPricing
	return &this
}

// NewTenantPackageWithDefaults instantiates a new TenantPackage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantPackageWithDefaults() *TenantPackage {
	this := TenantPackage{}
	return &this
}

// GetId returns the Id field value
func (o *TenantPackage) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TenantPackage) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *TenantPackage) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TenantPackage) SetName(v string) {
	o.Name = v
}

// GetTenantId returns the TenantId field value
func (o *TenantPackage) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *TenantPackage) SetTenantId(v string) {
	o.TenantId = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *TenantPackage) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *TenantPackage) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetMonthlyCostUSD returns the MonthlyCostUSD field value
// If the value is explicit nil, the zero value for float64 will be returned
func (o *TenantPackage) GetMonthlyCostUSD() float64 {
	if o == nil || o.MonthlyCostUSD.Get() == nil {
		var ret float64
		return ret
	}

	return *o.MonthlyCostUSD.Get()
}

// GetMonthlyCostUSDOk returns a tuple with the MonthlyCostUSD field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TenantPackage) GetMonthlyCostUSDOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.MonthlyCostUSD.Get(), o.MonthlyCostUSD.IsSet()
}

// SetMonthlyCostUSD sets field value
func (o *TenantPackage) SetMonthlyCostUSD(v float64) {
	o.MonthlyCostUSD.Set(&v)
}

// GetYearlyCostUSD returns the YearlyCostUSD field value
// If the value is explicit nil, the zero value for float64 will be returned
func (o *TenantPackage) GetYearlyCostUSD() float64 {
	if o == nil || o.YearlyCostUSD.Get() == nil {
		var ret float64
		return ret
	}

	return *o.YearlyCostUSD.Get()
}

// GetYearlyCostUSDOk returns a tuple with the YearlyCostUSD field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TenantPackage) GetYearlyCostUSDOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.YearlyCostUSD.Get(), o.YearlyCostUSD.IsSet()
}

// SetYearlyCostUSD sets field value
func (o *TenantPackage) SetYearlyCostUSD(v float64) {
	o.YearlyCostUSD.Set(&v)
}

// GetMonthlyStripePlanId returns the MonthlyStripePlanId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TenantPackage) GetMonthlyStripePlanId() string {
	if o == nil || o.MonthlyStripePlanId.Get() == nil {
		var ret string
		return ret
	}

	return *o.MonthlyStripePlanId.Get()
}

// GetMonthlyStripePlanIdOk returns a tuple with the MonthlyStripePlanId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TenantPackage) GetMonthlyStripePlanIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MonthlyStripePlanId.Get(), o.MonthlyStripePlanId.IsSet()
}

// SetMonthlyStripePlanId sets field value
func (o *TenantPackage) SetMonthlyStripePlanId(v string) {
	o.MonthlyStripePlanId.Set(&v)
}

// GetYearlyStripePlanId returns the YearlyStripePlanId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TenantPackage) GetYearlyStripePlanId() string {
	if o == nil || o.YearlyStripePlanId.Get() == nil {
		var ret string
		return ret
	}

	return *o.YearlyStripePlanId.Get()
}

// GetYearlyStripePlanIdOk returns a tuple with the YearlyStripePlanId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TenantPackage) GetYearlyStripePlanIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.YearlyStripePlanId.Get(), o.YearlyStripePlanId.IsSet()
}

// SetYearlyStripePlanId sets field value
func (o *TenantPackage) SetYearlyStripePlanId(v string) {
	o.YearlyStripePlanId.Set(&v)
}

// GetMaxMonthlyPageLoads returns the MaxMonthlyPageLoads field value
func (o *TenantPackage) GetMaxMonthlyPageLoads() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.MaxMonthlyPageLoads
}

// GetMaxMonthlyPageLoadsOk returns a tuple with the MaxMonthlyPageLoads field value
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetMaxMonthlyPageLoadsOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxMonthlyPageLoads, true
}

// SetMaxMonthlyPageLoads sets field value
func (o *TenantPackage) SetMaxMonthlyPageLoads(v float64) {
	o.MaxMonthlyPageLoads = v
}

// GetMaxMonthlyAPICredits returns the MaxMonthlyAPICredits field value
func (o *TenantPackage) GetMaxMonthlyAPICredits() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.MaxMonthlyAPICredits
}

// GetMaxMonthlyAPICreditsOk returns a tuple with the MaxMonthlyAPICredits field value
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetMaxMonthlyAPICreditsOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxMonthlyAPICredits, true
}

// SetMaxMonthlyAPICredits sets field value
func (o *TenantPackage) SetMaxMonthlyAPICredits(v float64) {
	o.MaxMonthlyAPICredits = v
}

// GetMaxMonthlySmallWidgetsCredits returns the MaxMonthlySmallWidgetsCredits field value
func (o *TenantPackage) GetMaxMonthlySmallWidgetsCredits() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.MaxMonthlySmallWidgetsCredits
}

// GetMaxMonthlySmallWidgetsCreditsOk returns a tuple with the MaxMonthlySmallWidgetsCredits field value
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetMaxMonthlySmallWidgetsCreditsOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxMonthlySmallWidgetsCredits, true
}

// SetMaxMonthlySmallWidgetsCredits sets field value
func (o *TenantPackage) SetMaxMonthlySmallWidgetsCredits(v float64) {
	o.MaxMonthlySmallWidgetsCredits = v
}

// GetMaxMonthlyComments returns the MaxMonthlyComments field value
func (o *TenantPackage) GetMaxMonthlyComments() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.MaxMonthlyComments
}

// GetMaxMonthlyCommentsOk returns a tuple with the MaxMonthlyComments field value
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetMaxMonthlyCommentsOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxMonthlyComments, true
}

// SetMaxMonthlyComments sets field value
func (o *TenantPackage) SetMaxMonthlyComments(v float64) {
	o.MaxMonthlyComments = v
}

// GetMaxConcurrentUsers returns the MaxConcurrentUsers field value
func (o *TenantPackage) GetMaxConcurrentUsers() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.MaxConcurrentUsers
}

// GetMaxConcurrentUsersOk returns a tuple with the MaxConcurrentUsers field value
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetMaxConcurrentUsersOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxConcurrentUsers, true
}

// SetMaxConcurrentUsers sets field value
func (o *TenantPackage) SetMaxConcurrentUsers(v float64) {
	o.MaxConcurrentUsers = v
}

// GetMaxTenantUsers returns the MaxTenantUsers field value
func (o *TenantPackage) GetMaxTenantUsers() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.MaxTenantUsers
}

// GetMaxTenantUsersOk returns a tuple with the MaxTenantUsers field value
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetMaxTenantUsersOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxTenantUsers, true
}

// SetMaxTenantUsers sets field value
func (o *TenantPackage) SetMaxTenantUsers(v float64) {
	o.MaxTenantUsers = v
}

// GetMaxSSOUsers returns the MaxSSOUsers field value
func (o *TenantPackage) GetMaxSSOUsers() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.MaxSSOUsers
}

// GetMaxSSOUsersOk returns a tuple with the MaxSSOUsers field value
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetMaxSSOUsersOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxSSOUsers, true
}

// SetMaxSSOUsers sets field value
func (o *TenantPackage) SetMaxSSOUsers(v float64) {
	o.MaxSSOUsers = v
}

// GetMaxModerators returns the MaxModerators field value
func (o *TenantPackage) GetMaxModerators() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.MaxModerators
}

// GetMaxModeratorsOk returns a tuple with the MaxModerators field value
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetMaxModeratorsOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxModerators, true
}

// SetMaxModerators sets field value
func (o *TenantPackage) SetMaxModerators(v float64) {
	o.MaxModerators = v
}

// GetMaxDomains returns the MaxDomains field value
func (o *TenantPackage) GetMaxDomains() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.MaxDomains
}

// GetMaxDomainsOk returns a tuple with the MaxDomains field value
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetMaxDomainsOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxDomains, true
}

// SetMaxDomains sets field value
func (o *TenantPackage) SetMaxDomains(v float64) {
	o.MaxDomains = v
}

// GetMaxWhiteLabeledTenants returns the MaxWhiteLabeledTenants field value
func (o *TenantPackage) GetMaxWhiteLabeledTenants() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.MaxWhiteLabeledTenants
}

// GetMaxWhiteLabeledTenantsOk returns a tuple with the MaxWhiteLabeledTenants field value
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetMaxWhiteLabeledTenantsOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxWhiteLabeledTenants, true
}

// SetMaxWhiteLabeledTenants sets field value
func (o *TenantPackage) SetMaxWhiteLabeledTenants(v float64) {
	o.MaxWhiteLabeledTenants = v
}

// GetMaxMonthlyEventLogRequests returns the MaxMonthlyEventLogRequests field value
func (o *TenantPackage) GetMaxMonthlyEventLogRequests() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.MaxMonthlyEventLogRequests
}

// GetMaxMonthlyEventLogRequestsOk returns a tuple with the MaxMonthlyEventLogRequests field value
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetMaxMonthlyEventLogRequestsOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxMonthlyEventLogRequests, true
}

// SetMaxMonthlyEventLogRequests sets field value
func (o *TenantPackage) SetMaxMonthlyEventLogRequests(v float64) {
	o.MaxMonthlyEventLogRequests = v
}

// GetHasWhiteLabeling returns the HasWhiteLabeling field value
func (o *TenantPackage) GetHasWhiteLabeling() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasWhiteLabeling
}

// GetHasWhiteLabelingOk returns a tuple with the HasWhiteLabeling field value
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetHasWhiteLabelingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasWhiteLabeling, true
}

// SetHasWhiteLabeling sets field value
func (o *TenantPackage) SetHasWhiteLabeling(v bool) {
	o.HasWhiteLabeling = v
}

// GetHasDebranding returns the HasDebranding field value
func (o *TenantPackage) GetHasDebranding() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasDebranding
}

// GetHasDebrandingOk returns a tuple with the HasDebranding field value
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetHasDebrandingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasDebranding, true
}

// SetHasDebranding sets field value
func (o *TenantPackage) SetHasDebranding(v bool) {
	o.HasDebranding = v
}

// GetHasLLMSpamDetection returns the HasLLMSpamDetection field value
func (o *TenantPackage) GetHasLLMSpamDetection() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasLLMSpamDetection
}

// GetHasLLMSpamDetectionOk returns a tuple with the HasLLMSpamDetection field value
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetHasLLMSpamDetectionOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasLLMSpamDetection, true
}

// SetHasLLMSpamDetection sets field value
func (o *TenantPackage) SetHasLLMSpamDetection(v bool) {
	o.HasLLMSpamDetection = v
}

// GetForWhoText returns the ForWhoText field value
func (o *TenantPackage) GetForWhoText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ForWhoText
}

// GetForWhoTextOk returns a tuple with the ForWhoText field value
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetForWhoTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ForWhoText, true
}

// SetForWhoText sets field value
func (o *TenantPackage) SetForWhoText(v string) {
	o.ForWhoText = v
}

// GetFeatureTaglines returns the FeatureTaglines field value
func (o *TenantPackage) GetFeatureTaglines() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.FeatureTaglines
}

// GetFeatureTaglinesOk returns a tuple with the FeatureTaglines field value
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFeatureTaglinesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FeatureTaglines, true
}

// SetFeatureTaglines sets field value
func (o *TenantPackage) SetFeatureTaglines(v []string) {
	o.FeatureTaglines = v
}

// GetHasAuditing returns the HasAuditing field value
func (o *TenantPackage) GetHasAuditing() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasAuditing
}

// GetHasAuditingOk returns a tuple with the HasAuditing field value
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetHasAuditingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasAuditing, true
}

// SetHasAuditing sets field value
func (o *TenantPackage) SetHasAuditing(v bool) {
	o.HasAuditing = v
}

// GetHasFlexPricing returns the HasFlexPricing field value
func (o *TenantPackage) GetHasFlexPricing() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasFlexPricing
}

// GetHasFlexPricingOk returns a tuple with the HasFlexPricing field value
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetHasFlexPricingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasFlexPricing, true
}

// SetHasFlexPricing sets field value
func (o *TenantPackage) SetHasFlexPricing(v bool) {
	o.HasFlexPricing = v
}

// GetEnableSAML returns the EnableSAML field value if set, zero value otherwise.
func (o *TenantPackage) GetEnableSAML() bool {
	if o == nil || IsNil(o.EnableSAML) {
		var ret bool
		return ret
	}
	return *o.EnableSAML
}

// GetEnableSAMLOk returns a tuple with the EnableSAML field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetEnableSAMLOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableSAML) {
		return nil, false
	}
	return o.EnableSAML, true
}

// HasEnableSAML returns a boolean if a field has been set.
func (o *TenantPackage) HasEnableSAML() bool {
	if o != nil && !IsNil(o.EnableSAML) {
		return true
	}

	return false
}

// SetEnableSAML gets a reference to the given bool and assigns it to the EnableSAML field.
func (o *TenantPackage) SetEnableSAML(v bool) {
	o.EnableSAML = &v
}

// GetFlexPageLoadCostCents returns the FlexPageLoadCostCents field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexPageLoadCostCents() float64 {
	if o == nil || IsNil(o.FlexPageLoadCostCents) {
		var ret float64
		return ret
	}
	return *o.FlexPageLoadCostCents
}

// GetFlexPageLoadCostCentsOk returns a tuple with the FlexPageLoadCostCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexPageLoadCostCentsOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexPageLoadCostCents) {
		return nil, false
	}
	return o.FlexPageLoadCostCents, true
}

// HasFlexPageLoadCostCents returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexPageLoadCostCents() bool {
	if o != nil && !IsNil(o.FlexPageLoadCostCents) {
		return true
	}

	return false
}

// SetFlexPageLoadCostCents gets a reference to the given float64 and assigns it to the FlexPageLoadCostCents field.
func (o *TenantPackage) SetFlexPageLoadCostCents(v float64) {
	o.FlexPageLoadCostCents = &v
}

// GetFlexPageLoadUnit returns the FlexPageLoadUnit field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexPageLoadUnit() float64 {
	if o == nil || IsNil(o.FlexPageLoadUnit) {
		var ret float64
		return ret
	}
	return *o.FlexPageLoadUnit
}

// GetFlexPageLoadUnitOk returns a tuple with the FlexPageLoadUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexPageLoadUnitOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexPageLoadUnit) {
		return nil, false
	}
	return o.FlexPageLoadUnit, true
}

// HasFlexPageLoadUnit returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexPageLoadUnit() bool {
	if o != nil && !IsNil(o.FlexPageLoadUnit) {
		return true
	}

	return false
}

// SetFlexPageLoadUnit gets a reference to the given float64 and assigns it to the FlexPageLoadUnit field.
func (o *TenantPackage) SetFlexPageLoadUnit(v float64) {
	o.FlexPageLoadUnit = &v
}

// GetFlexCommentCostCents returns the FlexCommentCostCents field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexCommentCostCents() float64 {
	if o == nil || IsNil(o.FlexCommentCostCents) {
		var ret float64
		return ret
	}
	return *o.FlexCommentCostCents
}

// GetFlexCommentCostCentsOk returns a tuple with the FlexCommentCostCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexCommentCostCentsOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexCommentCostCents) {
		return nil, false
	}
	return o.FlexCommentCostCents, true
}

// HasFlexCommentCostCents returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexCommentCostCents() bool {
	if o != nil && !IsNil(o.FlexCommentCostCents) {
		return true
	}

	return false
}

// SetFlexCommentCostCents gets a reference to the given float64 and assigns it to the FlexCommentCostCents field.
func (o *TenantPackage) SetFlexCommentCostCents(v float64) {
	o.FlexCommentCostCents = &v
}

// GetFlexCommentUnit returns the FlexCommentUnit field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexCommentUnit() float64 {
	if o == nil || IsNil(o.FlexCommentUnit) {
		var ret float64
		return ret
	}
	return *o.FlexCommentUnit
}

// GetFlexCommentUnitOk returns a tuple with the FlexCommentUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexCommentUnitOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexCommentUnit) {
		return nil, false
	}
	return o.FlexCommentUnit, true
}

// HasFlexCommentUnit returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexCommentUnit() bool {
	if o != nil && !IsNil(o.FlexCommentUnit) {
		return true
	}

	return false
}

// SetFlexCommentUnit gets a reference to the given float64 and assigns it to the FlexCommentUnit field.
func (o *TenantPackage) SetFlexCommentUnit(v float64) {
	o.FlexCommentUnit = &v
}

// GetFlexSSOUserCostCents returns the FlexSSOUserCostCents field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexSSOUserCostCents() float64 {
	if o == nil || IsNil(o.FlexSSOUserCostCents) {
		var ret float64
		return ret
	}
	return *o.FlexSSOUserCostCents
}

// GetFlexSSOUserCostCentsOk returns a tuple with the FlexSSOUserCostCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexSSOUserCostCentsOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexSSOUserCostCents) {
		return nil, false
	}
	return o.FlexSSOUserCostCents, true
}

// HasFlexSSOUserCostCents returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexSSOUserCostCents() bool {
	if o != nil && !IsNil(o.FlexSSOUserCostCents) {
		return true
	}

	return false
}

// SetFlexSSOUserCostCents gets a reference to the given float64 and assigns it to the FlexSSOUserCostCents field.
func (o *TenantPackage) SetFlexSSOUserCostCents(v float64) {
	o.FlexSSOUserCostCents = &v
}

// GetFlexSSOUserUnit returns the FlexSSOUserUnit field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexSSOUserUnit() float64 {
	if o == nil || IsNil(o.FlexSSOUserUnit) {
		var ret float64
		return ret
	}
	return *o.FlexSSOUserUnit
}

// GetFlexSSOUserUnitOk returns a tuple with the FlexSSOUserUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexSSOUserUnitOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexSSOUserUnit) {
		return nil, false
	}
	return o.FlexSSOUserUnit, true
}

// HasFlexSSOUserUnit returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexSSOUserUnit() bool {
	if o != nil && !IsNil(o.FlexSSOUserUnit) {
		return true
	}

	return false
}

// SetFlexSSOUserUnit gets a reference to the given float64 and assigns it to the FlexSSOUserUnit field.
func (o *TenantPackage) SetFlexSSOUserUnit(v float64) {
	o.FlexSSOUserUnit = &v
}

// GetFlexAPICreditCostCents returns the FlexAPICreditCostCents field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexAPICreditCostCents() float64 {
	if o == nil || IsNil(o.FlexAPICreditCostCents) {
		var ret float64
		return ret
	}
	return *o.FlexAPICreditCostCents
}

// GetFlexAPICreditCostCentsOk returns a tuple with the FlexAPICreditCostCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexAPICreditCostCentsOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexAPICreditCostCents) {
		return nil, false
	}
	return o.FlexAPICreditCostCents, true
}

// HasFlexAPICreditCostCents returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexAPICreditCostCents() bool {
	if o != nil && !IsNil(o.FlexAPICreditCostCents) {
		return true
	}

	return false
}

// SetFlexAPICreditCostCents gets a reference to the given float64 and assigns it to the FlexAPICreditCostCents field.
func (o *TenantPackage) SetFlexAPICreditCostCents(v float64) {
	o.FlexAPICreditCostCents = &v
}

// GetFlexAPICreditUnit returns the FlexAPICreditUnit field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexAPICreditUnit() float64 {
	if o == nil || IsNil(o.FlexAPICreditUnit) {
		var ret float64
		return ret
	}
	return *o.FlexAPICreditUnit
}

// GetFlexAPICreditUnitOk returns a tuple with the FlexAPICreditUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexAPICreditUnitOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexAPICreditUnit) {
		return nil, false
	}
	return o.FlexAPICreditUnit, true
}

// HasFlexAPICreditUnit returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexAPICreditUnit() bool {
	if o != nil && !IsNil(o.FlexAPICreditUnit) {
		return true
	}

	return false
}

// SetFlexAPICreditUnit gets a reference to the given float64 and assigns it to the FlexAPICreditUnit field.
func (o *TenantPackage) SetFlexAPICreditUnit(v float64) {
	o.FlexAPICreditUnit = &v
}

// GetFlexSmallWidgetsCreditCostCents returns the FlexSmallWidgetsCreditCostCents field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexSmallWidgetsCreditCostCents() float64 {
	if o == nil || IsNil(o.FlexSmallWidgetsCreditCostCents) {
		var ret float64
		return ret
	}
	return *o.FlexSmallWidgetsCreditCostCents
}

// GetFlexSmallWidgetsCreditCostCentsOk returns a tuple with the FlexSmallWidgetsCreditCostCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexSmallWidgetsCreditCostCentsOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexSmallWidgetsCreditCostCents) {
		return nil, false
	}
	return o.FlexSmallWidgetsCreditCostCents, true
}

// HasFlexSmallWidgetsCreditCostCents returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexSmallWidgetsCreditCostCents() bool {
	if o != nil && !IsNil(o.FlexSmallWidgetsCreditCostCents) {
		return true
	}

	return false
}

// SetFlexSmallWidgetsCreditCostCents gets a reference to the given float64 and assigns it to the FlexSmallWidgetsCreditCostCents field.
func (o *TenantPackage) SetFlexSmallWidgetsCreditCostCents(v float64) {
	o.FlexSmallWidgetsCreditCostCents = &v
}

// GetFlexSmallWidgetsCreditUnit returns the FlexSmallWidgetsCreditUnit field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexSmallWidgetsCreditUnit() float64 {
	if o == nil || IsNil(o.FlexSmallWidgetsCreditUnit) {
		var ret float64
		return ret
	}
	return *o.FlexSmallWidgetsCreditUnit
}

// GetFlexSmallWidgetsCreditUnitOk returns a tuple with the FlexSmallWidgetsCreditUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexSmallWidgetsCreditUnitOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexSmallWidgetsCreditUnit) {
		return nil, false
	}
	return o.FlexSmallWidgetsCreditUnit, true
}

// HasFlexSmallWidgetsCreditUnit returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexSmallWidgetsCreditUnit() bool {
	if o != nil && !IsNil(o.FlexSmallWidgetsCreditUnit) {
		return true
	}

	return false
}

// SetFlexSmallWidgetsCreditUnit gets a reference to the given float64 and assigns it to the FlexSmallWidgetsCreditUnit field.
func (o *TenantPackage) SetFlexSmallWidgetsCreditUnit(v float64) {
	o.FlexSmallWidgetsCreditUnit = &v
}

// GetFlexModeratorCostCents returns the FlexModeratorCostCents field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexModeratorCostCents() float64 {
	if o == nil || IsNil(o.FlexModeratorCostCents) {
		var ret float64
		return ret
	}
	return *o.FlexModeratorCostCents
}

// GetFlexModeratorCostCentsOk returns a tuple with the FlexModeratorCostCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexModeratorCostCentsOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexModeratorCostCents) {
		return nil, false
	}
	return o.FlexModeratorCostCents, true
}

// HasFlexModeratorCostCents returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexModeratorCostCents() bool {
	if o != nil && !IsNil(o.FlexModeratorCostCents) {
		return true
	}

	return false
}

// SetFlexModeratorCostCents gets a reference to the given float64 and assigns it to the FlexModeratorCostCents field.
func (o *TenantPackage) SetFlexModeratorCostCents(v float64) {
	o.FlexModeratorCostCents = &v
}

// GetFlexModeratorUnit returns the FlexModeratorUnit field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexModeratorUnit() float64 {
	if o == nil || IsNil(o.FlexModeratorUnit) {
		var ret float64
		return ret
	}
	return *o.FlexModeratorUnit
}

// GetFlexModeratorUnitOk returns a tuple with the FlexModeratorUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexModeratorUnitOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexModeratorUnit) {
		return nil, false
	}
	return o.FlexModeratorUnit, true
}

// HasFlexModeratorUnit returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexModeratorUnit() bool {
	if o != nil && !IsNil(o.FlexModeratorUnit) {
		return true
	}

	return false
}

// SetFlexModeratorUnit gets a reference to the given float64 and assigns it to the FlexModeratorUnit field.
func (o *TenantPackage) SetFlexModeratorUnit(v float64) {
	o.FlexModeratorUnit = &v
}

// GetFlexAdminCostCents returns the FlexAdminCostCents field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexAdminCostCents() float64 {
	if o == nil || IsNil(o.FlexAdminCostCents) {
		var ret float64
		return ret
	}
	return *o.FlexAdminCostCents
}

// GetFlexAdminCostCentsOk returns a tuple with the FlexAdminCostCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexAdminCostCentsOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexAdminCostCents) {
		return nil, false
	}
	return o.FlexAdminCostCents, true
}

// HasFlexAdminCostCents returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexAdminCostCents() bool {
	if o != nil && !IsNil(o.FlexAdminCostCents) {
		return true
	}

	return false
}

// SetFlexAdminCostCents gets a reference to the given float64 and assigns it to the FlexAdminCostCents field.
func (o *TenantPackage) SetFlexAdminCostCents(v float64) {
	o.FlexAdminCostCents = &v
}

// GetFlexAdminUnit returns the FlexAdminUnit field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexAdminUnit() float64 {
	if o == nil || IsNil(o.FlexAdminUnit) {
		var ret float64
		return ret
	}
	return *o.FlexAdminUnit
}

// GetFlexAdminUnitOk returns a tuple with the FlexAdminUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexAdminUnitOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexAdminUnit) {
		return nil, false
	}
	return o.FlexAdminUnit, true
}

// HasFlexAdminUnit returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexAdminUnit() bool {
	if o != nil && !IsNil(o.FlexAdminUnit) {
		return true
	}

	return false
}

// SetFlexAdminUnit gets a reference to the given float64 and assigns it to the FlexAdminUnit field.
func (o *TenantPackage) SetFlexAdminUnit(v float64) {
	o.FlexAdminUnit = &v
}

// GetFlexDomainCostCents returns the FlexDomainCostCents field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexDomainCostCents() float64 {
	if o == nil || IsNil(o.FlexDomainCostCents) {
		var ret float64
		return ret
	}
	return *o.FlexDomainCostCents
}

// GetFlexDomainCostCentsOk returns a tuple with the FlexDomainCostCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexDomainCostCentsOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexDomainCostCents) {
		return nil, false
	}
	return o.FlexDomainCostCents, true
}

// HasFlexDomainCostCents returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexDomainCostCents() bool {
	if o != nil && !IsNil(o.FlexDomainCostCents) {
		return true
	}

	return false
}

// SetFlexDomainCostCents gets a reference to the given float64 and assigns it to the FlexDomainCostCents field.
func (o *TenantPackage) SetFlexDomainCostCents(v float64) {
	o.FlexDomainCostCents = &v
}

// GetFlexDomainUnit returns the FlexDomainUnit field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexDomainUnit() float64 {
	if o == nil || IsNil(o.FlexDomainUnit) {
		var ret float64
		return ret
	}
	return *o.FlexDomainUnit
}

// GetFlexDomainUnitOk returns a tuple with the FlexDomainUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexDomainUnitOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexDomainUnit) {
		return nil, false
	}
	return o.FlexDomainUnit, true
}

// HasFlexDomainUnit returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexDomainUnit() bool {
	if o != nil && !IsNil(o.FlexDomainUnit) {
		return true
	}

	return false
}

// SetFlexDomainUnit gets a reference to the given float64 and assigns it to the FlexDomainUnit field.
func (o *TenantPackage) SetFlexDomainUnit(v float64) {
	o.FlexDomainUnit = &v
}

// GetFlexChatGPTCostCents returns the FlexChatGPTCostCents field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexChatGPTCostCents() float64 {
	if o == nil || IsNil(o.FlexChatGPTCostCents) {
		var ret float64
		return ret
	}
	return *o.FlexChatGPTCostCents
}

// GetFlexChatGPTCostCentsOk returns a tuple with the FlexChatGPTCostCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexChatGPTCostCentsOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexChatGPTCostCents) {
		return nil, false
	}
	return o.FlexChatGPTCostCents, true
}

// HasFlexChatGPTCostCents returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexChatGPTCostCents() bool {
	if o != nil && !IsNil(o.FlexChatGPTCostCents) {
		return true
	}

	return false
}

// SetFlexChatGPTCostCents gets a reference to the given float64 and assigns it to the FlexChatGPTCostCents field.
func (o *TenantPackage) SetFlexChatGPTCostCents(v float64) {
	o.FlexChatGPTCostCents = &v
}

// GetFlexChatGPTUnit returns the FlexChatGPTUnit field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexChatGPTUnit() float64 {
	if o == nil || IsNil(o.FlexChatGPTUnit) {
		var ret float64
		return ret
	}
	return *o.FlexChatGPTUnit
}

// GetFlexChatGPTUnitOk returns a tuple with the FlexChatGPTUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexChatGPTUnitOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexChatGPTUnit) {
		return nil, false
	}
	return o.FlexChatGPTUnit, true
}

// HasFlexChatGPTUnit returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexChatGPTUnit() bool {
	if o != nil && !IsNil(o.FlexChatGPTUnit) {
		return true
	}

	return false
}

// SetFlexChatGPTUnit gets a reference to the given float64 and assigns it to the FlexChatGPTUnit field.
func (o *TenantPackage) SetFlexChatGPTUnit(v float64) {
	o.FlexChatGPTUnit = &v
}

// GetFlexMinimumCostCents returns the FlexMinimumCostCents field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexMinimumCostCents() float64 {
	if o == nil || IsNil(o.FlexMinimumCostCents) {
		var ret float64
		return ret
	}
	return *o.FlexMinimumCostCents
}

// GetFlexMinimumCostCentsOk returns a tuple with the FlexMinimumCostCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexMinimumCostCentsOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexMinimumCostCents) {
		return nil, false
	}
	return o.FlexMinimumCostCents, true
}

// HasFlexMinimumCostCents returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexMinimumCostCents() bool {
	if o != nil && !IsNil(o.FlexMinimumCostCents) {
		return true
	}

	return false
}

// SetFlexMinimumCostCents gets a reference to the given float64 and assigns it to the FlexMinimumCostCents field.
func (o *TenantPackage) SetFlexMinimumCostCents(v float64) {
	o.FlexMinimumCostCents = &v
}

// GetFlexManagedTenantCostCents returns the FlexManagedTenantCostCents field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexManagedTenantCostCents() float64 {
	if o == nil || IsNil(o.FlexManagedTenantCostCents) {
		var ret float64
		return ret
	}
	return *o.FlexManagedTenantCostCents
}

// GetFlexManagedTenantCostCentsOk returns a tuple with the FlexManagedTenantCostCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexManagedTenantCostCentsOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexManagedTenantCostCents) {
		return nil, false
	}
	return o.FlexManagedTenantCostCents, true
}

// HasFlexManagedTenantCostCents returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexManagedTenantCostCents() bool {
	if o != nil && !IsNil(o.FlexManagedTenantCostCents) {
		return true
	}

	return false
}

// SetFlexManagedTenantCostCents gets a reference to the given float64 and assigns it to the FlexManagedTenantCostCents field.
func (o *TenantPackage) SetFlexManagedTenantCostCents(v float64) {
	o.FlexManagedTenantCostCents = &v
}

// GetFlexSSOAdminCostCents returns the FlexSSOAdminCostCents field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexSSOAdminCostCents() float64 {
	if o == nil || IsNil(o.FlexSSOAdminCostCents) {
		var ret float64
		return ret
	}
	return *o.FlexSSOAdminCostCents
}

// GetFlexSSOAdminCostCentsOk returns a tuple with the FlexSSOAdminCostCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexSSOAdminCostCentsOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexSSOAdminCostCents) {
		return nil, false
	}
	return o.FlexSSOAdminCostCents, true
}

// HasFlexSSOAdminCostCents returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexSSOAdminCostCents() bool {
	if o != nil && !IsNil(o.FlexSSOAdminCostCents) {
		return true
	}

	return false
}

// SetFlexSSOAdminCostCents gets a reference to the given float64 and assigns it to the FlexSSOAdminCostCents field.
func (o *TenantPackage) SetFlexSSOAdminCostCents(v float64) {
	o.FlexSSOAdminCostCents = &v
}

// GetFlexSSOAdminUnit returns the FlexSSOAdminUnit field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexSSOAdminUnit() float64 {
	if o == nil || IsNil(o.FlexSSOAdminUnit) {
		var ret float64
		return ret
	}
	return *o.FlexSSOAdminUnit
}

// GetFlexSSOAdminUnitOk returns a tuple with the FlexSSOAdminUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexSSOAdminUnitOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexSSOAdminUnit) {
		return nil, false
	}
	return o.FlexSSOAdminUnit, true
}

// HasFlexSSOAdminUnit returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexSSOAdminUnit() bool {
	if o != nil && !IsNil(o.FlexSSOAdminUnit) {
		return true
	}

	return false
}

// SetFlexSSOAdminUnit gets a reference to the given float64 and assigns it to the FlexSSOAdminUnit field.
func (o *TenantPackage) SetFlexSSOAdminUnit(v float64) {
	o.FlexSSOAdminUnit = &v
}

// GetFlexSSOModeratorCostCents returns the FlexSSOModeratorCostCents field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexSSOModeratorCostCents() float64 {
	if o == nil || IsNil(o.FlexSSOModeratorCostCents) {
		var ret float64
		return ret
	}
	return *o.FlexSSOModeratorCostCents
}

// GetFlexSSOModeratorCostCentsOk returns a tuple with the FlexSSOModeratorCostCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexSSOModeratorCostCentsOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexSSOModeratorCostCents) {
		return nil, false
	}
	return o.FlexSSOModeratorCostCents, true
}

// HasFlexSSOModeratorCostCents returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexSSOModeratorCostCents() bool {
	if o != nil && !IsNil(o.FlexSSOModeratorCostCents) {
		return true
	}

	return false
}

// SetFlexSSOModeratorCostCents gets a reference to the given float64 and assigns it to the FlexSSOModeratorCostCents field.
func (o *TenantPackage) SetFlexSSOModeratorCostCents(v float64) {
	o.FlexSSOModeratorCostCents = &v
}

// GetFlexSSOModeratorUnit returns the FlexSSOModeratorUnit field value if set, zero value otherwise.
func (o *TenantPackage) GetFlexSSOModeratorUnit() float64 {
	if o == nil || IsNil(o.FlexSSOModeratorUnit) {
		var ret float64
		return ret
	}
	return *o.FlexSSOModeratorUnit
}

// GetFlexSSOModeratorUnitOk returns a tuple with the FlexSSOModeratorUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetFlexSSOModeratorUnitOk() (*float64, bool) {
	if o == nil || IsNil(o.FlexSSOModeratorUnit) {
		return nil, false
	}
	return o.FlexSSOModeratorUnit, true
}

// HasFlexSSOModeratorUnit returns a boolean if a field has been set.
func (o *TenantPackage) HasFlexSSOModeratorUnit() bool {
	if o != nil && !IsNil(o.FlexSSOModeratorUnit) {
		return true
	}

	return false
}

// SetFlexSSOModeratorUnit gets a reference to the given float64 and assigns it to the FlexSSOModeratorUnit field.
func (o *TenantPackage) SetFlexSSOModeratorUnit(v float64) {
	o.FlexSSOModeratorUnit = &v
}

// GetIsSSOBillingMonthlyActiveUsers returns the IsSSOBillingMonthlyActiveUsers field value if set, zero value otherwise.
func (o *TenantPackage) GetIsSSOBillingMonthlyActiveUsers() bool {
	if o == nil || IsNil(o.IsSSOBillingMonthlyActiveUsers) {
		var ret bool
		return ret
	}
	return *o.IsSSOBillingMonthlyActiveUsers
}

// GetIsSSOBillingMonthlyActiveUsersOk returns a tuple with the IsSSOBillingMonthlyActiveUsers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPackage) GetIsSSOBillingMonthlyActiveUsersOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSSOBillingMonthlyActiveUsers) {
		return nil, false
	}
	return o.IsSSOBillingMonthlyActiveUsers, true
}

// HasIsSSOBillingMonthlyActiveUsers returns a boolean if a field has been set.
func (o *TenantPackage) HasIsSSOBillingMonthlyActiveUsers() bool {
	if o != nil && !IsNil(o.IsSSOBillingMonthlyActiveUsers) {
		return true
	}

	return false
}

// SetIsSSOBillingMonthlyActiveUsers gets a reference to the given bool and assigns it to the IsSSOBillingMonthlyActiveUsers field.
func (o *TenantPackage) SetIsSSOBillingMonthlyActiveUsers(v bool) {
	o.IsSSOBillingMonthlyActiveUsers = &v
}

func (o TenantPackage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantPackage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["_id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["tenantId"] = o.TenantId
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["monthlyCostUSD"] = o.MonthlyCostUSD.Get()
	toSerialize["yearlyCostUSD"] = o.YearlyCostUSD.Get()
	toSerialize["monthlyStripePlanId"] = o.MonthlyStripePlanId.Get()
	toSerialize["yearlyStripePlanId"] = o.YearlyStripePlanId.Get()
	toSerialize["maxMonthlyPageLoads"] = o.MaxMonthlyPageLoads
	toSerialize["maxMonthlyAPICredits"] = o.MaxMonthlyAPICredits
	toSerialize["maxMonthlySmallWidgetsCredits"] = o.MaxMonthlySmallWidgetsCredits
	toSerialize["maxMonthlyComments"] = o.MaxMonthlyComments
	toSerialize["maxConcurrentUsers"] = o.MaxConcurrentUsers
	toSerialize["maxTenantUsers"] = o.MaxTenantUsers
	toSerialize["maxSSOUsers"] = o.MaxSSOUsers
	toSerialize["maxModerators"] = o.MaxModerators
	toSerialize["maxDomains"] = o.MaxDomains
	toSerialize["maxWhiteLabeledTenants"] = o.MaxWhiteLabeledTenants
	toSerialize["maxMonthlyEventLogRequests"] = o.MaxMonthlyEventLogRequests
	toSerialize["hasWhiteLabeling"] = o.HasWhiteLabeling
	toSerialize["hasDebranding"] = o.HasDebranding
	toSerialize["hasLLMSpamDetection"] = o.HasLLMSpamDetection
	toSerialize["forWhoText"] = o.ForWhoText
	toSerialize["featureTaglines"] = o.FeatureTaglines
	toSerialize["hasAuditing"] = o.HasAuditing
	toSerialize["hasFlexPricing"] = o.HasFlexPricing
	if !IsNil(o.EnableSAML) {
		toSerialize["enableSAML"] = o.EnableSAML
	}
	if !IsNil(o.FlexPageLoadCostCents) {
		toSerialize["flexPageLoadCostCents"] = o.FlexPageLoadCostCents
	}
	if !IsNil(o.FlexPageLoadUnit) {
		toSerialize["flexPageLoadUnit"] = o.FlexPageLoadUnit
	}
	if !IsNil(o.FlexCommentCostCents) {
		toSerialize["flexCommentCostCents"] = o.FlexCommentCostCents
	}
	if !IsNil(o.FlexCommentUnit) {
		toSerialize["flexCommentUnit"] = o.FlexCommentUnit
	}
	if !IsNil(o.FlexSSOUserCostCents) {
		toSerialize["flexSSOUserCostCents"] = o.FlexSSOUserCostCents
	}
	if !IsNil(o.FlexSSOUserUnit) {
		toSerialize["flexSSOUserUnit"] = o.FlexSSOUserUnit
	}
	if !IsNil(o.FlexAPICreditCostCents) {
		toSerialize["flexAPICreditCostCents"] = o.FlexAPICreditCostCents
	}
	if !IsNil(o.FlexAPICreditUnit) {
		toSerialize["flexAPICreditUnit"] = o.FlexAPICreditUnit
	}
	if !IsNil(o.FlexSmallWidgetsCreditCostCents) {
		toSerialize["flexSmallWidgetsCreditCostCents"] = o.FlexSmallWidgetsCreditCostCents
	}
	if !IsNil(o.FlexSmallWidgetsCreditUnit) {
		toSerialize["flexSmallWidgetsCreditUnit"] = o.FlexSmallWidgetsCreditUnit
	}
	if !IsNil(o.FlexModeratorCostCents) {
		toSerialize["flexModeratorCostCents"] = o.FlexModeratorCostCents
	}
	if !IsNil(o.FlexModeratorUnit) {
		toSerialize["flexModeratorUnit"] = o.FlexModeratorUnit
	}
	if !IsNil(o.FlexAdminCostCents) {
		toSerialize["flexAdminCostCents"] = o.FlexAdminCostCents
	}
	if !IsNil(o.FlexAdminUnit) {
		toSerialize["flexAdminUnit"] = o.FlexAdminUnit
	}
	if !IsNil(o.FlexDomainCostCents) {
		toSerialize["flexDomainCostCents"] = o.FlexDomainCostCents
	}
	if !IsNil(o.FlexDomainUnit) {
		toSerialize["flexDomainUnit"] = o.FlexDomainUnit
	}
	if !IsNil(o.FlexChatGPTCostCents) {
		toSerialize["flexChatGPTCostCents"] = o.FlexChatGPTCostCents
	}
	if !IsNil(o.FlexChatGPTUnit) {
		toSerialize["flexChatGPTUnit"] = o.FlexChatGPTUnit
	}
	if !IsNil(o.FlexMinimumCostCents) {
		toSerialize["flexMinimumCostCents"] = o.FlexMinimumCostCents
	}
	if !IsNil(o.FlexManagedTenantCostCents) {
		toSerialize["flexManagedTenantCostCents"] = o.FlexManagedTenantCostCents
	}
	if !IsNil(o.FlexSSOAdminCostCents) {
		toSerialize["flexSSOAdminCostCents"] = o.FlexSSOAdminCostCents
	}
	if !IsNil(o.FlexSSOAdminUnit) {
		toSerialize["flexSSOAdminUnit"] = o.FlexSSOAdminUnit
	}
	if !IsNil(o.FlexSSOModeratorCostCents) {
		toSerialize["flexSSOModeratorCostCents"] = o.FlexSSOModeratorCostCents
	}
	if !IsNil(o.FlexSSOModeratorUnit) {
		toSerialize["flexSSOModeratorUnit"] = o.FlexSSOModeratorUnit
	}
	if !IsNil(o.IsSSOBillingMonthlyActiveUsers) {
		toSerialize["isSSOBillingMonthlyActiveUsers"] = o.IsSSOBillingMonthlyActiveUsers
	}
	return toSerialize, nil
}

func (o *TenantPackage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"_id",
		"name",
		"tenantId",
		"createdAt",
		"monthlyCostUSD",
		"yearlyCostUSD",
		"monthlyStripePlanId",
		"yearlyStripePlanId",
		"maxMonthlyPageLoads",
		"maxMonthlyAPICredits",
		"maxMonthlySmallWidgetsCredits",
		"maxMonthlyComments",
		"maxConcurrentUsers",
		"maxTenantUsers",
		"maxSSOUsers",
		"maxModerators",
		"maxDomains",
		"maxWhiteLabeledTenants",
		"maxMonthlyEventLogRequests",
		"hasWhiteLabeling",
		"hasDebranding",
		"hasLLMSpamDetection",
		"forWhoText",
		"featureTaglines",
		"hasAuditing",
		"hasFlexPricing",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTenantPackage := _TenantPackage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTenantPackage)

	if err != nil {
		return err
	}

	*o = TenantPackage(varTenantPackage)

	return err
}

type NullableTenantPackage struct {
	value *TenantPackage
	isSet bool
}

func (v NullableTenantPackage) Get() *TenantPackage {
	return v.value
}

func (v *NullableTenantPackage) Set(val *TenantPackage) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantPackage) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantPackage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantPackage(val *TenantPackage) *NullableTenantPackage {
	return &NullableTenantPackage{value: val, isSet: true}
}

func (v NullableTenantPackage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantPackage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


