/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VoteDeleteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VoteDeleteResponse{}

// VoteDeleteResponse struct for VoteDeleteResponse
type VoteDeleteResponse struct {
	Status APIStatus `json:"status"`
	WasPendingVote *bool `json:"wasPendingVote,omitempty"`
}

type _VoteDeleteResponse VoteDeleteResponse

// NewVoteDeleteResponse instantiates a new VoteDeleteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVoteDeleteResponse(status APIStatus) *VoteDeleteResponse {
	this := VoteDeleteResponse{}
	this.Status = status
	return &this
}

// NewVoteDeleteResponseWithDefaults instantiates a new VoteDeleteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVoteDeleteResponseWithDefaults() *VoteDeleteResponse {
	this := VoteDeleteResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *VoteDeleteResponse) GetStatus() APIStatus {
	if o == nil {
		var ret APIStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *VoteDeleteResponse) GetStatusOk() (*APIStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *VoteDeleteResponse) SetStatus(v APIStatus) {
	o.Status = v
}

// GetWasPendingVote returns the WasPendingVote field value if set, zero value otherwise.
func (o *VoteDeleteResponse) GetWasPendingVote() bool {
	if o == nil || IsNil(o.WasPendingVote) {
		var ret bool
		return ret
	}
	return *o.WasPendingVote
}

// GetWasPendingVoteOk returns a tuple with the WasPendingVote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoteDeleteResponse) GetWasPendingVoteOk() (*bool, bool) {
	if o == nil || IsNil(o.WasPendingVote) {
		return nil, false
	}
	return o.WasPendingVote, true
}

// HasWasPendingVote returns a boolean if a field has been set.
func (o *VoteDeleteResponse) HasWasPendingVote() bool {
	if o != nil && !IsNil(o.WasPendingVote) {
		return true
	}

	return false
}

// SetWasPendingVote gets a reference to the given bool and assigns it to the WasPendingVote field.
func (o *VoteDeleteResponse) SetWasPendingVote(v bool) {
	o.WasPendingVote = &v
}

func (o VoteDeleteResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VoteDeleteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	if !IsNil(o.WasPendingVote) {
		toSerialize["wasPendingVote"] = o.WasPendingVote
	}
	return toSerialize, nil
}

func (o *VoteDeleteResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVoteDeleteResponse := _VoteDeleteResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVoteDeleteResponse)

	if err != nil {
		return err
	}

	*o = VoteDeleteResponse(varVoteDeleteResponse)

	return err
}

type NullableVoteDeleteResponse struct {
	value *VoteDeleteResponse
	isSet bool
}

func (v NullableVoteDeleteResponse) Get() *VoteDeleteResponse {
	return v.value
}

func (v *NullableVoteDeleteResponse) Set(val *VoteDeleteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVoteDeleteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVoteDeleteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVoteDeleteResponse(val *VoteDeleteResponse) *NullableVoteDeleteResponse {
	return &NullableVoteDeleteResponse{value: val, isSet: true}
}

func (v NullableVoteDeleteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVoteDeleteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


