/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// SSOSecurityLevel the model 'SSOSecurityLevel'
type SSOSecurityLevel float32

// List of SSOSecurityLevel
const (
	SSOSECURITYLEVEL__0 SSOSecurityLevel = 0
	SSOSECURITYLEVEL__1 SSOSecurityLevel = 1
)

// All allowed values of SSOSecurityLevel enum
var AllowedSSOSecurityLevelEnumValues = []SSOSecurityLevel{
	0,
	1,
}

func (v *SSOSecurityLevel) UnmarshalJSON(src []byte) error {
	var value float32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SSOSecurityLevel(value)
	for _, existing := range AllowedSSOSecurityLevelEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SSOSecurityLevel", value)
}

// NewSSOSecurityLevelFromValue returns a pointer to a valid SSOSecurityLevel
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSSOSecurityLevelFromValue(v float32) (*SSOSecurityLevel, error) {
	ev := SSOSecurityLevel(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SSOSecurityLevel: valid values are %v", v, AllowedSSOSecurityLevelEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SSOSecurityLevel) IsValid() bool {
	for _, existing := range AllowedSSOSecurityLevelEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SSOSecurityLevel value
func (v SSOSecurityLevel) Ptr() *SSOSecurityLevel {
	return &v
}

type NullableSSOSecurityLevel struct {
	value *SSOSecurityLevel
	isSet bool
}

func (v NullableSSOSecurityLevel) Get() *SSOSecurityLevel {
	return v.value
}

func (v *NullableSSOSecurityLevel) Set(val *SSOSecurityLevel) {
	v.value = val
	v.isSet = true
}

func (v NullableSSOSecurityLevel) IsSet() bool {
	return v.isSet
}

func (v *NullableSSOSecurityLevel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSSOSecurityLevel(val *SSOSecurityLevel) *NullableSSOSecurityLevel {
	return &NullableSSOSecurityLevel{value: val, isSet: true}
}

func (v NullableSSOSecurityLevel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSSOSecurityLevel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

