/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// DeleteCommentResponse struct for DeleteCommentResponse
type DeleteCommentResponse struct {
	APIError *APIError
	DeleteCommentResult *DeleteCommentResult
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *DeleteCommentResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal JSON data into DeleteCommentResult
	err = json.Unmarshal(data, &dst.DeleteCommentResult);
	if err == nil {
		jsonDeleteCommentResult, _ := json.Marshal(dst.DeleteCommentResult)
		if string(jsonDeleteCommentResult) == "{}" { // empty struct
			dst.DeleteCommentResult = nil
		} else {
			return nil // data stored in dst.DeleteCommentResult, return on the first match
		}
	} else {
		dst.DeleteCommentResult = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(DeleteCommentResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src DeleteCommentResponse) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.DeleteCommentResult != nil {
		return json.Marshal(&src.DeleteCommentResult)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableDeleteCommentResponse struct {
	value *DeleteCommentResponse
	isSet bool
}

func (v NullableDeleteCommentResponse) Get() *DeleteCommentResponse {
	return v.value
}

func (v *NullableDeleteCommentResponse) Set(val *DeleteCommentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteCommentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteCommentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteCommentResponse(val *DeleteCommentResponse) *NullableDeleteCommentResponse {
	return &NullableDeleteCommentResponse{value: val, isSet: true}
}

func (v NullableDeleteCommentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteCommentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


