/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PatchSSOUserAPIResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchSSOUserAPIResponse{}

// PatchSSOUserAPIResponse struct for PatchSSOUserAPIResponse
type PatchSSOUserAPIResponse struct {
	Reason *string `json:"reason,omitempty"`
	Code *string `json:"code,omitempty"`
	User *APISSOUser `json:"user,omitempty"`
	Status string `json:"status"`
}

type _PatchSSOUserAPIResponse PatchSSOUserAPIResponse

// NewPatchSSOUserAPIResponse instantiates a new PatchSSOUserAPIResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchSSOUserAPIResponse(status string) *PatchSSOUserAPIResponse {
	this := PatchSSOUserAPIResponse{}
	this.Status = status
	return &this
}

// NewPatchSSOUserAPIResponseWithDefaults instantiates a new PatchSSOUserAPIResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchSSOUserAPIResponseWithDefaults() *PatchSSOUserAPIResponse {
	this := PatchSSOUserAPIResponse{}
	return &this
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *PatchSSOUserAPIResponse) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchSSOUserAPIResponse) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *PatchSSOUserAPIResponse) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *PatchSSOUserAPIResponse) SetReason(v string) {
	o.Reason = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *PatchSSOUserAPIResponse) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchSSOUserAPIResponse) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *PatchSSOUserAPIResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *PatchSSOUserAPIResponse) SetCode(v string) {
	o.Code = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *PatchSSOUserAPIResponse) GetUser() APISSOUser {
	if o == nil || IsNil(o.User) {
		var ret APISSOUser
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchSSOUserAPIResponse) GetUserOk() (*APISSOUser, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *PatchSSOUserAPIResponse) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given APISSOUser and assigns it to the User field.
func (o *PatchSSOUserAPIResponse) SetUser(v APISSOUser) {
	o.User = &v
}

// GetStatus returns the Status field value
func (o *PatchSSOUserAPIResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PatchSSOUserAPIResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PatchSSOUserAPIResponse) SetStatus(v string) {
	o.Status = v
}

func (o PatchSSOUserAPIResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchSSOUserAPIResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *PatchSSOUserAPIResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPatchSSOUserAPIResponse := _PatchSSOUserAPIResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPatchSSOUserAPIResponse)

	if err != nil {
		return err
	}

	*o = PatchSSOUserAPIResponse(varPatchSSOUserAPIResponse)

	return err
}

type NullablePatchSSOUserAPIResponse struct {
	value *PatchSSOUserAPIResponse
	isSet bool
}

func (v NullablePatchSSOUserAPIResponse) Get() *PatchSSOUserAPIResponse {
	return v.value
}

func (v *NullablePatchSSOUserAPIResponse) Set(val *PatchSSOUserAPIResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchSSOUserAPIResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchSSOUserAPIResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchSSOUserAPIResponse(val *PatchSSOUserAPIResponse) *NullablePatchSSOUserAPIResponse {
	return &NullablePatchSSOUserAPIResponse{value: val, isSet: true}
}

func (v NullablePatchSSOUserAPIResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchSSOUserAPIResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


