/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetPublicFeedPostsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPublicFeedPostsResponse{}

// GetPublicFeedPostsResponse struct for GetPublicFeedPostsResponse
type GetPublicFeedPostsResponse struct {
	Status APIStatus `json:"status"`
	FeedPosts []FeedPost `json:"feedPosts"`
	User NullableUserSessionInfo `json:"user,omitempty"`
}

type _GetPublicFeedPostsResponse GetPublicFeedPostsResponse

// NewGetPublicFeedPostsResponse instantiates a new GetPublicFeedPostsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPublicFeedPostsResponse(status APIStatus, feedPosts []FeedPost) *GetPublicFeedPostsResponse {
	this := GetPublicFeedPostsResponse{}
	this.Status = status
	this.FeedPosts = feedPosts
	return &this
}

// NewGetPublicFeedPostsResponseWithDefaults instantiates a new GetPublicFeedPostsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPublicFeedPostsResponseWithDefaults() *GetPublicFeedPostsResponse {
	this := GetPublicFeedPostsResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *GetPublicFeedPostsResponse) GetStatus() APIStatus {
	if o == nil {
		var ret APIStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetPublicFeedPostsResponse) GetStatusOk() (*APIStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetPublicFeedPostsResponse) SetStatus(v APIStatus) {
	o.Status = v
}

// GetFeedPosts returns the FeedPosts field value
func (o *GetPublicFeedPostsResponse) GetFeedPosts() []FeedPost {
	if o == nil {
		var ret []FeedPost
		return ret
	}

	return o.FeedPosts
}

// GetFeedPostsOk returns a tuple with the FeedPosts field value
// and a boolean to check if the value has been set.
func (o *GetPublicFeedPostsResponse) GetFeedPostsOk() ([]FeedPost, bool) {
	if o == nil {
		return nil, false
	}
	return o.FeedPosts, true
}

// SetFeedPosts sets field value
func (o *GetPublicFeedPostsResponse) SetFeedPosts(v []FeedPost) {
	o.FeedPosts = v
}

// GetUser returns the User field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetPublicFeedPostsResponse) GetUser() UserSessionInfo {
	if o == nil || IsNil(o.User.Get()) {
		var ret UserSessionInfo
		return ret
	}
	return *o.User.Get()
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetPublicFeedPostsResponse) GetUserOk() (*UserSessionInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.User.Get(), o.User.IsSet()
}

// HasUser returns a boolean if a field has been set.
func (o *GetPublicFeedPostsResponse) HasUser() bool {
	if o != nil && o.User.IsSet() {
		return true
	}

	return false
}

// SetUser gets a reference to the given NullableUserSessionInfo and assigns it to the User field.
func (o *GetPublicFeedPostsResponse) SetUser(v UserSessionInfo) {
	o.User.Set(&v)
}
// SetUserNil sets the value for User to be an explicit nil
func (o *GetPublicFeedPostsResponse) SetUserNil() {
	o.User.Set(nil)
}

// UnsetUser ensures that no value is present for User, not even an explicit nil
func (o *GetPublicFeedPostsResponse) UnsetUser() {
	o.User.Unset()
}

func (o GetPublicFeedPostsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPublicFeedPostsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["feedPosts"] = o.FeedPosts
	if o.User.IsSet() {
		toSerialize["user"] = o.User.Get()
	}
	return toSerialize, nil
}

func (o *GetPublicFeedPostsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"feedPosts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetPublicFeedPostsResponse := _GetPublicFeedPostsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetPublicFeedPostsResponse)

	if err != nil {
		return err
	}

	*o = GetPublicFeedPostsResponse(varGetPublicFeedPostsResponse)

	return err
}

type NullableGetPublicFeedPostsResponse struct {
	value *GetPublicFeedPostsResponse
	isSet bool
}

func (v NullableGetPublicFeedPostsResponse) Get() *GetPublicFeedPostsResponse {
	return v.value
}

func (v *NullableGetPublicFeedPostsResponse) Set(val *GetPublicFeedPostsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPublicFeedPostsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPublicFeedPostsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPublicFeedPostsResponse(val *GetPublicFeedPostsResponse) *NullableGetPublicFeedPostsResponse {
	return &NullableGetPublicFeedPostsResponse{value: val, isSet: true}
}

func (v NullableGetPublicFeedPostsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPublicFeedPostsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


