/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// GetPreBanSummaryResponse struct for GetPreBanSummaryResponse
type GetPreBanSummaryResponse struct {
	APIError *APIError
	PreBanSummary *PreBanSummary
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetPreBanSummaryResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal JSON data into PreBanSummary
	err = json.Unmarshal(data, &dst.PreBanSummary);
	if err == nil {
		jsonPreBanSummary, _ := json.Marshal(dst.PreBanSummary)
		if string(jsonPreBanSummary) == "{}" { // empty struct
			dst.PreBanSummary = nil
		} else {
			return nil // data stored in dst.PreBanSummary, return on the first match
		}
	} else {
		dst.PreBanSummary = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetPreBanSummaryResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetPreBanSummaryResponse) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.PreBanSummary != nil {
		return json.Marshal(&src.PreBanSummary)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableGetPreBanSummaryResponse struct {
	value *GetPreBanSummaryResponse
	isSet bool
}

func (v NullableGetPreBanSummaryResponse) Get() *GetPreBanSummaryResponse {
	return v.value
}

func (v *NullableGetPreBanSummaryResponse) Set(val *GetPreBanSummaryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPreBanSummaryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPreBanSummaryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPreBanSummaryResponse(val *GetPreBanSummaryResponse) *NullableGetPreBanSummaryResponse {
	return &NullableGetPreBanSummaryResponse{value: val, isSet: true}
}

func (v NullableGetPreBanSummaryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPreBanSummaryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


