/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// GetFeedPostsStatsResponse struct for GetFeedPostsStatsResponse
type GetFeedPostsStatsResponse struct {
	APIError *APIError
	FeedPostsStatsResponse *FeedPostsStatsResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetFeedPostsStatsResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal JSON data into FeedPostsStatsResponse
	err = json.Unmarshal(data, &dst.FeedPostsStatsResponse);
	if err == nil {
		jsonFeedPostsStatsResponse, _ := json.Marshal(dst.FeedPostsStatsResponse)
		if string(jsonFeedPostsStatsResponse) == "{}" { // empty struct
			dst.FeedPostsStatsResponse = nil
		} else {
			return nil // data stored in dst.FeedPostsStatsResponse, return on the first match
		}
	} else {
		dst.FeedPostsStatsResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetFeedPostsStatsResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetFeedPostsStatsResponse) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.FeedPostsStatsResponse != nil {
		return json.Marshal(&src.FeedPostsStatsResponse)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableGetFeedPostsStatsResponse struct {
	value *GetFeedPostsStatsResponse
	isSet bool
}

func (v NullableGetFeedPostsStatsResponse) Get() *GetFeedPostsStatsResponse {
	return v.value
}

func (v *NullableGetFeedPostsStatsResponse) Set(val *GetFeedPostsStatsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFeedPostsStatsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFeedPostsStatsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFeedPostsStatsResponse(val *GetFeedPostsStatsResponse) *NullableGetFeedPostsStatsResponse {
	return &NullableGetFeedPostsStatsResponse{value: val, isSet: true}
}

func (v NullableGetFeedPostsStatsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFeedPostsStatsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


