/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// GetFeedPostsResponse1 struct for GetFeedPostsResponse1
type GetFeedPostsResponse1 struct {
	APIError *APIError
	GetFeedPostsResponse *GetFeedPostsResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetFeedPostsResponse1) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal JSON data into GetFeedPostsResponse
	err = json.Unmarshal(data, &dst.GetFeedPostsResponse);
	if err == nil {
		jsonGetFeedPostsResponse, _ := json.Marshal(dst.GetFeedPostsResponse)
		if string(jsonGetFeedPostsResponse) == "{}" { // empty struct
			dst.GetFeedPostsResponse = nil
		} else {
			return nil // data stored in dst.GetFeedPostsResponse, return on the first match
		}
	} else {
		dst.GetFeedPostsResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetFeedPostsResponse1)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetFeedPostsResponse1) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.GetFeedPostsResponse != nil {
		return json.Marshal(&src.GetFeedPostsResponse)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableGetFeedPostsResponse1 struct {
	value *GetFeedPostsResponse1
	isSet bool
}

func (v NullableGetFeedPostsResponse1) Get() *GetFeedPostsResponse1 {
	return v.value
}

func (v *NullableGetFeedPostsResponse1) Set(val *GetFeedPostsResponse1) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFeedPostsResponse1) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFeedPostsResponse1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFeedPostsResponse1(val *GetFeedPostsResponse1) *NullableGetFeedPostsResponse1 {
	return &NullableGetFeedPostsResponse1{value: val, isSet: true}
}

func (v NullableGetFeedPostsResponse1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFeedPostsResponse1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


