/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// GetCommentsPublicResponse struct for GetCommentsPublicResponse
type GetCommentsPublicResponse struct {
	APIError *APIError
	GetCommentsResponseWithPresencePublicComment *GetCommentsResponseWithPresencePublicComment
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetCommentsPublicResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal JSON data into GetCommentsResponseWithPresencePublicComment
	err = json.Unmarshal(data, &dst.GetCommentsResponseWithPresencePublicComment);
	if err == nil {
		jsonGetCommentsResponseWithPresencePublicComment, _ := json.Marshal(dst.GetCommentsResponseWithPresencePublicComment)
		if string(jsonGetCommentsResponseWithPresencePublicComment) == "{}" { // empty struct
			dst.GetCommentsResponseWithPresencePublicComment = nil
		} else {
			return nil // data stored in dst.GetCommentsResponseWithPresencePublicComment, return on the first match
		}
	} else {
		dst.GetCommentsResponseWithPresencePublicComment = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetCommentsPublicResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetCommentsPublicResponse) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.GetCommentsResponseWithPresencePublicComment != nil {
		return json.Marshal(&src.GetCommentsResponseWithPresencePublicComment)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableGetCommentsPublicResponse struct {
	value *GetCommentsPublicResponse
	isSet bool
}

func (v NullableGetCommentsPublicResponse) Get() *GetCommentsPublicResponse {
	return v.value
}

func (v *NullableGetCommentsPublicResponse) Set(val *GetCommentsPublicResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCommentsPublicResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCommentsPublicResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCommentsPublicResponse(val *GetCommentsPublicResponse) *NullableGetCommentsPublicResponse {
	return &NullableGetCommentsPublicResponse{value: val, isSet: true}
}

func (v NullableGetCommentsPublicResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCommentsPublicResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


