/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// CommentQuestionsRequired the model 'CommentQuestionsRequired'
type CommentQuestionsRequired float32

// List of CommentQuestionsRequired
const (
	COMMENTQUESTIONSREQUIRED__0 CommentQuestionsRequired = 0
	COMMENTQUESTIONSREQUIRED__1 CommentQuestionsRequired = 1
)

// All allowed values of CommentQuestionsRequired enum
var AllowedCommentQuestionsRequiredEnumValues = []CommentQuestionsRequired{
	0,
	1,
}

func (v *CommentQuestionsRequired) UnmarshalJSON(src []byte) error {
	var value float32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CommentQuestionsRequired(value)
	for _, existing := range AllowedCommentQuestionsRequiredEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CommentQuestionsRequired", value)
}

// NewCommentQuestionsRequiredFromValue returns a pointer to a valid CommentQuestionsRequired
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCommentQuestionsRequiredFromValue(v float32) (*CommentQuestionsRequired, error) {
	ev := CommentQuestionsRequired(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CommentQuestionsRequired: valid values are %v", v, AllowedCommentQuestionsRequiredEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CommentQuestionsRequired) IsValid() bool {
	for _, existing := range AllowedCommentQuestionsRequiredEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CommentQuestionsRequired value
func (v CommentQuestionsRequired) Ptr() *CommentQuestionsRequired {
	return &v
}

type NullableCommentQuestionsRequired struct {
	value *CommentQuestionsRequired
	isSet bool
}

func (v NullableCommentQuestionsRequired) Get() *CommentQuestionsRequired {
	return v.value
}

func (v *NullableCommentQuestionsRequired) Set(val *CommentQuestionsRequired) {
	v.value = val
	v.isSet = true
}

func (v NullableCommentQuestionsRequired) IsSet() bool {
	return v.isSet
}

func (v *NullableCommentQuestionsRequired) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommentQuestionsRequired(val *CommentQuestionsRequired) *NullableCommentQuestionsRequired {
	return &NullableCommentQuestionsRequired{value: val, isSet: true}
}

func (v NullableCommentQuestionsRequired) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommentQuestionsRequired) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

