/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CommentUserMentionInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommentUserMentionInfo{}

// CommentUserMentionInfo struct for CommentUserMentionInfo
type CommentUserMentionInfo struct {
	Id string `json:"id"`
	Tag string `json:"tag"`
	RawTag *string `json:"rawTag,omitempty"`
	Type *string `json:"type,omitempty"`
	Sent *bool `json:"sent,omitempty"`
}

type _CommentUserMentionInfo CommentUserMentionInfo

// NewCommentUserMentionInfo instantiates a new CommentUserMentionInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommentUserMentionInfo(id string, tag string) *CommentUserMentionInfo {
	this := CommentUserMentionInfo{}
	this.Id = id
	this.Tag = tag
	return &this
}

// NewCommentUserMentionInfoWithDefaults instantiates a new CommentUserMentionInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommentUserMentionInfoWithDefaults() *CommentUserMentionInfo {
	this := CommentUserMentionInfo{}
	return &this
}

// GetId returns the Id field value
func (o *CommentUserMentionInfo) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CommentUserMentionInfo) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CommentUserMentionInfo) SetId(v string) {
	o.Id = v
}

// GetTag returns the Tag field value
func (o *CommentUserMentionInfo) GetTag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tag
}

// GetTagOk returns a tuple with the Tag field value
// and a boolean to check if the value has been set.
func (o *CommentUserMentionInfo) GetTagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tag, true
}

// SetTag sets field value
func (o *CommentUserMentionInfo) SetTag(v string) {
	o.Tag = v
}

// GetRawTag returns the RawTag field value if set, zero value otherwise.
func (o *CommentUserMentionInfo) GetRawTag() string {
	if o == nil || IsNil(o.RawTag) {
		var ret string
		return ret
	}
	return *o.RawTag
}

// GetRawTagOk returns a tuple with the RawTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentUserMentionInfo) GetRawTagOk() (*string, bool) {
	if o == nil || IsNil(o.RawTag) {
		return nil, false
	}
	return o.RawTag, true
}

// HasRawTag returns a boolean if a field has been set.
func (o *CommentUserMentionInfo) HasRawTag() bool {
	if o != nil && !IsNil(o.RawTag) {
		return true
	}

	return false
}

// SetRawTag gets a reference to the given string and assigns it to the RawTag field.
func (o *CommentUserMentionInfo) SetRawTag(v string) {
	o.RawTag = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CommentUserMentionInfo) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentUserMentionInfo) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CommentUserMentionInfo) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CommentUserMentionInfo) SetType(v string) {
	o.Type = &v
}

// GetSent returns the Sent field value if set, zero value otherwise.
func (o *CommentUserMentionInfo) GetSent() bool {
	if o == nil || IsNil(o.Sent) {
		var ret bool
		return ret
	}
	return *o.Sent
}

// GetSentOk returns a tuple with the Sent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommentUserMentionInfo) GetSentOk() (*bool, bool) {
	if o == nil || IsNil(o.Sent) {
		return nil, false
	}
	return o.Sent, true
}

// HasSent returns a boolean if a field has been set.
func (o *CommentUserMentionInfo) HasSent() bool {
	if o != nil && !IsNil(o.Sent) {
		return true
	}

	return false
}

// SetSent gets a reference to the given bool and assigns it to the Sent field.
func (o *CommentUserMentionInfo) SetSent(v bool) {
	o.Sent = &v
}

func (o CommentUserMentionInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommentUserMentionInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["tag"] = o.Tag
	if !IsNil(o.RawTag) {
		toSerialize["rawTag"] = o.RawTag
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Sent) {
		toSerialize["sent"] = o.Sent
	}
	return toSerialize, nil
}

func (o *CommentUserMentionInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"tag",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommentUserMentionInfo := _CommentUserMentionInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCommentUserMentionInfo)

	if err != nil {
		return err
	}

	*o = CommentUserMentionInfo(varCommentUserMentionInfo)

	return err
}

type NullableCommentUserMentionInfo struct {
	value *CommentUserMentionInfo
	isSet bool
}

func (v NullableCommentUserMentionInfo) Get() *CommentUserMentionInfo {
	return v.value
}

func (v *NullableCommentUserMentionInfo) Set(val *CommentUserMentionInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableCommentUserMentionInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableCommentUserMentionInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommentUserMentionInfo(val *CommentUserMentionInfo) *NullableCommentUserMentionInfo {
	return &NullableCommentUserMentionInfo{value: val, isSet: true}
}

func (v NullableCommentUserMentionInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommentUserMentionInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


