/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// BlockFromCommentPublicResponse struct for BlockFromCommentPublicResponse
type BlockFromCommentPublicResponse struct {
	APIError *APIError
	BlockSuccess *BlockSuccess
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *BlockFromCommentPublicResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal JSON data into BlockSuccess
	err = json.Unmarshal(data, &dst.BlockSuccess);
	if err == nil {
		jsonBlockSuccess, _ := json.Marshal(dst.BlockSuccess)
		if string(jsonBlockSuccess) == "{}" { // empty struct
			dst.BlockSuccess = nil
		} else {
			return nil // data stored in dst.BlockSuccess, return on the first match
		}
	} else {
		dst.BlockSuccess = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(BlockFromCommentPublicResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BlockFromCommentPublicResponse) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.BlockSuccess != nil {
		return json.Marshal(&src.BlockSuccess)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableBlockFromCommentPublicResponse struct {
	value *BlockFromCommentPublicResponse
	isSet bool
}

func (v NullableBlockFromCommentPublicResponse) Get() *BlockFromCommentPublicResponse {
	return v.value
}

func (v *NullableBlockFromCommentPublicResponse) Set(val *BlockFromCommentPublicResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBlockFromCommentPublicResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBlockFromCommentPublicResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlockFromCommentPublicResponse(val *BlockFromCommentPublicResponse) *NullableBlockFromCommentPublicResponse {
	return &NullableBlockFromCommentPublicResponse{value: val, isSet: true}
}

func (v NullableBlockFromCommentPublicResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlockFromCommentPublicResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


