/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// UpdateUserNotificationCommentSubscriptionStatusResponse struct for UpdateUserNotificationCommentSubscriptionStatusResponse
type UpdateUserNotificationCommentSubscriptionStatusResponse struct {
	IgnoredResponse *IgnoredResponse
	UserNotificationWriteResponse *UserNotificationWriteResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *UpdateUserNotificationCommentSubscriptionStatusResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into IgnoredResponse
	err = json.Unmarshal(data, &dst.IgnoredResponse);
	if err == nil {
		jsonIgnoredResponse, _ := json.Marshal(dst.IgnoredResponse)
		if string(jsonIgnoredResponse) == "{}" { // empty struct
			dst.IgnoredResponse = nil
		} else {
			return nil // data stored in dst.IgnoredResponse, return on the first match
		}
	} else {
		dst.IgnoredResponse = nil
	}

	// try to unmarshal JSON data into UserNotificationWriteResponse
	err = json.Unmarshal(data, &dst.UserNotificationWriteResponse);
	if err == nil {
		jsonUserNotificationWriteResponse, _ := json.Marshal(dst.UserNotificationWriteResponse)
		if string(jsonUserNotificationWriteResponse) == "{}" { // empty struct
			dst.UserNotificationWriteResponse = nil
		} else {
			return nil // data stored in dst.UserNotificationWriteResponse, return on the first match
		}
	} else {
		dst.UserNotificationWriteResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(UpdateUserNotificationCommentSubscriptionStatusResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src UpdateUserNotificationCommentSubscriptionStatusResponse) MarshalJSON() ([]byte, error) {
	if src.IgnoredResponse != nil {
		return json.Marshal(&src.IgnoredResponse)
	}

	if src.UserNotificationWriteResponse != nil {
		return json.Marshal(&src.UserNotificationWriteResponse)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableUpdateUserNotificationCommentSubscriptionStatusResponse struct {
	value *UpdateUserNotificationCommentSubscriptionStatusResponse
	isSet bool
}

func (v NullableUpdateUserNotificationCommentSubscriptionStatusResponse) Get() *UpdateUserNotificationCommentSubscriptionStatusResponse {
	return v.value
}

func (v *NullableUpdateUserNotificationCommentSubscriptionStatusResponse) Set(val *UpdateUserNotificationCommentSubscriptionStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateUserNotificationCommentSubscriptionStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateUserNotificationCommentSubscriptionStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateUserNotificationCommentSubscriptionStatusResponse(val *UpdateUserNotificationCommentSubscriptionStatusResponse) *NullableUpdateUserNotificationCommentSubscriptionStatusResponse {
	return &NullableUpdateUserNotificationCommentSubscriptionStatusResponse{value: val, isSet: true}
}

func (v NullableUpdateUserNotificationCommentSubscriptionStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateUserNotificationCommentSubscriptionStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


