/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetModeratorsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetModeratorsResponse{}

// GetModeratorsResponse struct for GetModeratorsResponse
type GetModeratorsResponse struct {
	Status APIStatus `json:"status"`
	Moderators []Moderator `json:"moderators"`
}

type _GetModeratorsResponse GetModeratorsResponse

// NewGetModeratorsResponse instantiates a new GetModeratorsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetModeratorsResponse(status APIStatus, moderators []Moderator) *GetModeratorsResponse {
	this := GetModeratorsResponse{}
	this.Status = status
	this.Moderators = moderators
	return &this
}

// NewGetModeratorsResponseWithDefaults instantiates a new GetModeratorsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetModeratorsResponseWithDefaults() *GetModeratorsResponse {
	this := GetModeratorsResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *GetModeratorsResponse) GetStatus() APIStatus {
	if o == nil {
		var ret APIStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetModeratorsResponse) GetStatusOk() (*APIStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetModeratorsResponse) SetStatus(v APIStatus) {
	o.Status = v
}

// GetModerators returns the Moderators field value
func (o *GetModeratorsResponse) GetModerators() []Moderator {
	if o == nil {
		var ret []Moderator
		return ret
	}

	return o.Moderators
}

// GetModeratorsOk returns a tuple with the Moderators field value
// and a boolean to check if the value has been set.
func (o *GetModeratorsResponse) GetModeratorsOk() ([]Moderator, bool) {
	if o == nil {
		return nil, false
	}
	return o.Moderators, true
}

// SetModerators sets field value
func (o *GetModeratorsResponse) SetModerators(v []Moderator) {
	o.Moderators = v
}

func (o GetModeratorsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetModeratorsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["moderators"] = o.Moderators
	return toSerialize, nil
}

func (o *GetModeratorsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"moderators",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetModeratorsResponse := _GetModeratorsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetModeratorsResponse)

	if err != nil {
		return err
	}

	*o = GetModeratorsResponse(varGetModeratorsResponse)

	return err
}

type NullableGetModeratorsResponse struct {
	value *GetModeratorsResponse
	isSet bool
}

func (v NullableGetModeratorsResponse) Get() *GetModeratorsResponse {
	return v.value
}

func (v *NullableGetModeratorsResponse) Set(val *GetModeratorsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetModeratorsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetModeratorsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetModeratorsResponse(val *GetModeratorsResponse) *NullableGetModeratorsResponse {
	return &NullableGetModeratorsResponse{value: val, isSet: true}
}

func (v NullableGetModeratorsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetModeratorsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


