/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// GetGifsTrendingResponse struct for GetGifsTrendingResponse
type GetGifsTrendingResponse struct {
	GifSearchInternalError *GifSearchInternalError
	GifSearchResponse *GifSearchResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetGifsTrendingResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into GifSearchInternalError
	err = json.Unmarshal(data, &dst.GifSearchInternalError);
	if err == nil {
		jsonGifSearchInternalError, _ := json.Marshal(dst.GifSearchInternalError)
		if string(jsonGifSearchInternalError) == "{}" { // empty struct
			dst.GifSearchInternalError = nil
		} else {
			return nil // data stored in dst.GifSearchInternalError, return on the first match
		}
	} else {
		dst.GifSearchInternalError = nil
	}

	// try to unmarshal JSON data into GifSearchResponse
	err = json.Unmarshal(data, &dst.GifSearchResponse);
	if err == nil {
		jsonGifSearchResponse, _ := json.Marshal(dst.GifSearchResponse)
		if string(jsonGifSearchResponse) == "{}" { // empty struct
			dst.GifSearchResponse = nil
		} else {
			return nil // data stored in dst.GifSearchResponse, return on the first match
		}
	} else {
		dst.GifSearchResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetGifsTrendingResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetGifsTrendingResponse) MarshalJSON() ([]byte, error) {
	if src.GifSearchInternalError != nil {
		return json.Marshal(&src.GifSearchInternalError)
	}

	if src.GifSearchResponse != nil {
		return json.Marshal(&src.GifSearchResponse)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableGetGifsTrendingResponse struct {
	value *GetGifsTrendingResponse
	isSet bool
}

func (v NullableGetGifsTrendingResponse) Get() *GetGifsTrendingResponse {
	return v.value
}

func (v *NullableGetGifsTrendingResponse) Set(val *GetGifsTrendingResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetGifsTrendingResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetGifsTrendingResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetGifsTrendingResponse(val *GetGifsTrendingResponse) *NullableGetGifsTrendingResponse {
	return &NullableGetGifsTrendingResponse{value: val, isSet: true}
}

func (v NullableGetGifsTrendingResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetGifsTrendingResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


