/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// GetTenantUsersResponse1 struct for GetTenantUsersResponse1
type GetTenantUsersResponse1 struct {
	APIError *APIError
	GetTenantUsersResponse *GetTenantUsersResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetTenantUsersResponse1) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal JSON data into GetTenantUsersResponse
	err = json.Unmarshal(data, &dst.GetTenantUsersResponse);
	if err == nil {
		jsonGetTenantUsersResponse, _ := json.Marshal(dst.GetTenantUsersResponse)
		if string(jsonGetTenantUsersResponse) == "{}" { // empty struct
			dst.GetTenantUsersResponse = nil
		} else {
			return nil // data stored in dst.GetTenantUsersResponse, return on the first match
		}
	} else {
		dst.GetTenantUsersResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetTenantUsersResponse1)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetTenantUsersResponse1) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.GetTenantUsersResponse != nil {
		return json.Marshal(&src.GetTenantUsersResponse)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableGetTenantUsersResponse1 struct {
	value *GetTenantUsersResponse1
	isSet bool
}

func (v NullableGetTenantUsersResponse1) Get() *GetTenantUsersResponse1 {
	return v.value
}

func (v *NullableGetTenantUsersResponse1) Set(val *GetTenantUsersResponse1) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTenantUsersResponse1) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTenantUsersResponse1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTenantUsersResponse1(val *GetTenantUsersResponse1) *NullableGetTenantUsersResponse1 {
	return &NullableGetTenantUsersResponse1{value: val, isSet: true}
}

func (v NullableGetTenantUsersResponse1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTenantUsersResponse1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


