/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// CreateQuestionConfig200Response struct for CreateQuestionConfig200Response
type CreateQuestionConfig200Response struct {
	APIError *APIError
	CreateQuestionConfigResponse *CreateQuestionConfigResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *CreateQuestionConfig200Response) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal JSON data into CreateQuestionConfigResponse
	err = json.Unmarshal(data, &dst.CreateQuestionConfigResponse);
	if err == nil {
		jsonCreateQuestionConfigResponse, _ := json.Marshal(dst.CreateQuestionConfigResponse)
		if string(jsonCreateQuestionConfigResponse) == "{}" { // empty struct
			dst.CreateQuestionConfigResponse = nil
		} else {
			return nil // data stored in dst.CreateQuestionConfigResponse, return on the first match
		}
	} else {
		dst.CreateQuestionConfigResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(CreateQuestionConfig200Response)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CreateQuestionConfig200Response) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.CreateQuestionConfigResponse != nil {
		return json.Marshal(&src.CreateQuestionConfigResponse)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableCreateQuestionConfig200Response struct {
	value *CreateQuestionConfig200Response
	isSet bool
}

func (v NullableCreateQuestionConfig200Response) Get() *CreateQuestionConfig200Response {
	return v.value
}

func (v *NullableCreateQuestionConfig200Response) Set(val *CreateQuestionConfig200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateQuestionConfig200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateQuestionConfig200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateQuestionConfig200Response(val *CreateQuestionConfig200Response) *NullableCreateQuestionConfig200Response {
	return &NullableCreateQuestionConfig200Response{value: val, isSet: true}
}

func (v NullableCreateQuestionConfig200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateQuestionConfig200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


