/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// SaveComment200Response struct for SaveComment200Response
type SaveComment200Response struct {
	APIError *APIError
	SaveCommentResponse *SaveCommentResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *SaveComment200Response) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal JSON data into SaveCommentResponse
	err = json.Unmarshal(data, &dst.SaveCommentResponse);
	if err == nil {
		jsonSaveCommentResponse, _ := json.Marshal(dst.SaveCommentResponse)
		if string(jsonSaveCommentResponse) == "{}" { // empty struct
			dst.SaveCommentResponse = nil
		} else {
			return nil // data stored in dst.SaveCommentResponse, return on the first match
		}
	} else {
		dst.SaveCommentResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(SaveComment200Response)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src SaveComment200Response) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.SaveCommentResponse != nil {
		return json.Marshal(&src.SaveCommentResponse)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableSaveComment200Response struct {
	value *SaveComment200Response
	isSet bool
}

func (v NullableSaveComment200Response) Get() *SaveComment200Response {
	return v.value
}

func (v *NullableSaveComment200Response) Set(val *SaveComment200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSaveComment200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSaveComment200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSaveComment200Response(val *SaveComment200Response) *NullableSaveComment200Response {
	return &NullableSaveComment200Response{value: val, isSet: true}
}

func (v NullableSaveComment200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSaveComment200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


