/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// GetVotes200Response struct for GetVotes200Response
type GetVotes200Response struct {
	APIError *APIError
	GetVotesResponse *GetVotesResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetVotes200Response) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal JSON data into GetVotesResponse
	err = json.Unmarshal(data, &dst.GetVotesResponse);
	if err == nil {
		jsonGetVotesResponse, _ := json.Marshal(dst.GetVotesResponse)
		if string(jsonGetVotesResponse) == "{}" { // empty struct
			dst.GetVotesResponse = nil
		} else {
			return nil // data stored in dst.GetVotesResponse, return on the first match
		}
	} else {
		dst.GetVotesResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetVotes200Response)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetVotes200Response) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.GetVotesResponse != nil {
		return json.Marshal(&src.GetVotesResponse)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableGetVotes200Response struct {
	value *GetVotes200Response
	isSet bool
}

func (v NullableGetVotes200Response) Get() *GetVotes200Response {
	return v.value
}

func (v *NullableGetVotes200Response) Set(val *GetVotes200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVotes200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVotes200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVotes200Response(val *GetVotes200Response) *NullableGetVotes200Response {
	return &NullableGetVotes200Response{value: val, isSet: true}
}

func (v NullableGetVotes200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVotes200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


