/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AggregationRequestSort type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AggregationRequestSort{}

// AggregationRequestSort struct for AggregationRequestSort
type AggregationRequestSort struct {
	Dir string `json:"dir"`
	Field string `json:"field"`
}

type _AggregationRequestSort AggregationRequestSort

// NewAggregationRequestSort instantiates a new AggregationRequestSort object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAggregationRequestSort(dir string, field string) *AggregationRequestSort {
	this := AggregationRequestSort{}
	this.Dir = dir
	this.Field = field
	return &this
}

// NewAggregationRequestSortWithDefaults instantiates a new AggregationRequestSort object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAggregationRequestSortWithDefaults() *AggregationRequestSort {
	this := AggregationRequestSort{}
	return &this
}

// GetDir returns the Dir field value
func (o *AggregationRequestSort) GetDir() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Dir
}

// GetDirOk returns a tuple with the Dir field value
// and a boolean to check if the value has been set.
func (o *AggregationRequestSort) GetDirOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dir, true
}

// SetDir sets field value
func (o *AggregationRequestSort) SetDir(v string) {
	o.Dir = v
}

// GetField returns the Field field value
func (o *AggregationRequestSort) GetField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *AggregationRequestSort) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Field, true
}

// SetField sets field value
func (o *AggregationRequestSort) SetField(v string) {
	o.Field = v
}

func (o AggregationRequestSort) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AggregationRequestSort) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dir"] = o.Dir
	toSerialize["field"] = o.Field
	return toSerialize, nil
}

func (o *AggregationRequestSort) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dir",
		"field",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAggregationRequestSort := _AggregationRequestSort{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAggregationRequestSort)

	if err != nil {
		return err
	}

	*o = AggregationRequestSort(varAggregationRequestSort)

	return err
}

type NullableAggregationRequestSort struct {
	value *AggregationRequestSort
	isSet bool
}

func (v NullableAggregationRequestSort) Get() *AggregationRequestSort {
	return v.value
}

func (v *NullableAggregationRequestSort) Set(val *AggregationRequestSort) {
	v.value = val
	v.isSet = true
}

func (v NullableAggregationRequestSort) IsSet() bool {
	return v.isSet
}

func (v *NullableAggregationRequestSort) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAggregationRequestSort(val *AggregationRequestSort) *NullableAggregationRequestSort {
	return &NullableAggregationRequestSort{value: val, isSet: true}
}

func (v NullableAggregationRequestSort) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAggregationRequestSort) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


