/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// DeleteCommentPublic200Response struct for DeleteCommentPublic200Response
type DeleteCommentPublic200Response struct {
	APIError *APIError
	PublicAPIDeleteCommentResponse *PublicAPIDeleteCommentResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *DeleteCommentPublic200Response) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal JSON data into PublicAPIDeleteCommentResponse
	err = json.Unmarshal(data, &dst.PublicAPIDeleteCommentResponse);
	if err == nil {
		jsonPublicAPIDeleteCommentResponse, _ := json.Marshal(dst.PublicAPIDeleteCommentResponse)
		if string(jsonPublicAPIDeleteCommentResponse) == "{}" { // empty struct
			dst.PublicAPIDeleteCommentResponse = nil
		} else {
			return nil // data stored in dst.PublicAPIDeleteCommentResponse, return on the first match
		}
	} else {
		dst.PublicAPIDeleteCommentResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(DeleteCommentPublic200Response)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src DeleteCommentPublic200Response) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.PublicAPIDeleteCommentResponse != nil {
		return json.Marshal(&src.PublicAPIDeleteCommentResponse)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableDeleteCommentPublic200Response struct {
	value *DeleteCommentPublic200Response
	isSet bool
}

func (v NullableDeleteCommentPublic200Response) Get() *DeleteCommentPublic200Response {
	return v.value
}

func (v *NullableDeleteCommentPublic200Response) Set(val *DeleteCommentPublic200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteCommentPublic200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteCommentPublic200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteCommentPublic200Response(val *DeleteCommentPublic200Response) *NullableDeleteCommentPublic200Response {
	return &NullableDeleteCommentPublic200Response{value: val, isSet: true}
}

func (v NullableDeleteCommentPublic200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteCommentPublic200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


