/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// GetOfflineUsersResponse struct for GetOfflineUsersResponse
type GetOfflineUsersResponse struct {
	APIError *APIError
	PageUsersOfflineResponse *PageUsersOfflineResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetOfflineUsersResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal JSON data into PageUsersOfflineResponse
	err = json.Unmarshal(data, &dst.PageUsersOfflineResponse);
	if err == nil {
		jsonPageUsersOfflineResponse, _ := json.Marshal(dst.PageUsersOfflineResponse)
		if string(jsonPageUsersOfflineResponse) == "{}" { // empty struct
			dst.PageUsersOfflineResponse = nil
		} else {
			return nil // data stored in dst.PageUsersOfflineResponse, return on the first match
		}
	} else {
		dst.PageUsersOfflineResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetOfflineUsersResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetOfflineUsersResponse) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.PageUsersOfflineResponse != nil {
		return json.Marshal(&src.PageUsersOfflineResponse)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableGetOfflineUsersResponse struct {
	value *GetOfflineUsersResponse
	isSet bool
}

func (v NullableGetOfflineUsersResponse) Get() *GetOfflineUsersResponse {
	return v.value
}

func (v *NullableGetOfflineUsersResponse) Set(val *GetOfflineUsersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOfflineUsersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOfflineUsersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOfflineUsersResponse(val *GetOfflineUsersResponse) *NullableGetOfflineUsersResponse {
	return &NullableGetOfflineUsersResponse{value: val, isSet: true}
}

func (v NullableGetOfflineUsersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOfflineUsersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


