/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// GetModeratorResponse1 struct for GetModeratorResponse1
type GetModeratorResponse1 struct {
	APIError *APIError
	GetModeratorResponse *GetModeratorResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetModeratorResponse1) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal JSON data into GetModeratorResponse
	err = json.Unmarshal(data, &dst.GetModeratorResponse);
	if err == nil {
		jsonGetModeratorResponse, _ := json.Marshal(dst.GetModeratorResponse)
		if string(jsonGetModeratorResponse) == "{}" { // empty struct
			dst.GetModeratorResponse = nil
		} else {
			return nil // data stored in dst.GetModeratorResponse, return on the first match
		}
	} else {
		dst.GetModeratorResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetModeratorResponse1)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetModeratorResponse1) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.GetModeratorResponse != nil {
		return json.Marshal(&src.GetModeratorResponse)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableGetModeratorResponse1 struct {
	value *GetModeratorResponse1
	isSet bool
}

func (v NullableGetModeratorResponse1) Get() *GetModeratorResponse1 {
	return v.value
}

func (v *NullableGetModeratorResponse1) Set(val *GetModeratorResponse1) {
	v.value = val
	v.isSet = true
}

func (v NullableGetModeratorResponse1) IsSet() bool {
	return v.isSet
}

func (v *NullableGetModeratorResponse1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetModeratorResponse1(val *GetModeratorResponse1) *NullableGetModeratorResponse1 {
	return &NullableGetModeratorResponse1{value: val, isSet: true}
}

func (v NullableGetModeratorResponse1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetModeratorResponse1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


