/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// FlagCommentPublic200Response struct for FlagCommentPublic200Response
type FlagCommentPublic200Response struct {
	APIEmptyResponse *APIEmptyResponse
	APIError *APIError
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *FlagCommentPublic200Response) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIEmptyResponse
	err = json.Unmarshal(data, &dst.APIEmptyResponse);
	if err == nil {
		jsonAPIEmptyResponse, _ := json.Marshal(dst.APIEmptyResponse)
		if string(jsonAPIEmptyResponse) == "{}" { // empty struct
			dst.APIEmptyResponse = nil
		} else {
			return nil // data stored in dst.APIEmptyResponse, return on the first match
		}
	} else {
		dst.APIEmptyResponse = nil
	}

	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(FlagCommentPublic200Response)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src FlagCommentPublic200Response) MarshalJSON() ([]byte, error) {
	if src.APIEmptyResponse != nil {
		return json.Marshal(&src.APIEmptyResponse)
	}

	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableFlagCommentPublic200Response struct {
	value *FlagCommentPublic200Response
	isSet bool
}

func (v NullableFlagCommentPublic200Response) Get() *FlagCommentPublic200Response {
	return v.value
}

func (v *NullableFlagCommentPublic200Response) Set(val *FlagCommentPublic200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFlagCommentPublic200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFlagCommentPublic200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlagCommentPublic200Response(val *FlagCommentPublic200Response) *NullableFlagCommentPublic200Response {
	return &NullableFlagCommentPublic200Response{value: val, isSet: true}
}

func (v NullableFlagCommentPublic200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlagCommentPublic200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


