/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// DeleteEmailTemplateResponse struct for DeleteEmailTemplateResponse
type DeleteEmailTemplateResponse struct {
	APIEmptyResponse *APIEmptyResponse
	APIError *APIError
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *DeleteEmailTemplateResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIEmptyResponse
	err = json.Unmarshal(data, &dst.APIEmptyResponse);
	if err == nil {
		jsonAPIEmptyResponse, _ := json.Marshal(dst.APIEmptyResponse)
		if string(jsonAPIEmptyResponse) == "{}" { // empty struct
			dst.APIEmptyResponse = nil
		} else {
			return nil // data stored in dst.APIEmptyResponse, return on the first match
		}
	} else {
		dst.APIEmptyResponse = nil
	}

	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(DeleteEmailTemplateResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src DeleteEmailTemplateResponse) MarshalJSON() ([]byte, error) {
	if src.APIEmptyResponse != nil {
		return json.Marshal(&src.APIEmptyResponse)
	}

	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableDeleteEmailTemplateResponse struct {
	value *DeleteEmailTemplateResponse
	isSet bool
}

func (v NullableDeleteEmailTemplateResponse) Get() *DeleteEmailTemplateResponse {
	return v.value
}

func (v *NullableDeleteEmailTemplateResponse) Set(val *DeleteEmailTemplateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteEmailTemplateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteEmailTemplateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteEmailTemplateResponse(val *DeleteEmailTemplateResponse) *NullableDeleteEmailTemplateResponse {
	return &NullableDeleteEmailTemplateResponse{value: val, isSet: true}
}

func (v NullableDeleteEmailTemplateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteEmailTemplateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


