/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GifSearchResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GifSearchResponse{}

// GifSearchResponse struct for GifSearchResponse
type GifSearchResponse struct {
	Images [][]GifSearchResponseImagesInnerInner `json:"images"`
	Status APIStatus `json:"status"`
}

type _GifSearchResponse GifSearchResponse

// NewGifSearchResponse instantiates a new GifSearchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGifSearchResponse(images [][]GifSearchResponseImagesInnerInner, status APIStatus) *GifSearchResponse {
	this := GifSearchResponse{}
	this.Images = images
	this.Status = status
	return &this
}

// NewGifSearchResponseWithDefaults instantiates a new GifSearchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGifSearchResponseWithDefaults() *GifSearchResponse {
	this := GifSearchResponse{}
	return &this
}

// GetImages returns the Images field value
func (o *GifSearchResponse) GetImages() [][]GifSearchResponseImagesInnerInner {
	if o == nil {
		var ret [][]GifSearchResponseImagesInnerInner
		return ret
	}

	return o.Images
}

// GetImagesOk returns a tuple with the Images field value
// and a boolean to check if the value has been set.
func (o *GifSearchResponse) GetImagesOk() ([][]GifSearchResponseImagesInnerInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Images, true
}

// SetImages sets field value
func (o *GifSearchResponse) SetImages(v [][]GifSearchResponseImagesInnerInner) {
	o.Images = v
}

// GetStatus returns the Status field value
func (o *GifSearchResponse) GetStatus() APIStatus {
	if o == nil {
		var ret APIStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GifSearchResponse) GetStatusOk() (*APIStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GifSearchResponse) SetStatus(v APIStatus) {
	o.Status = v
}

func (o GifSearchResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GifSearchResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["images"] = o.Images
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *GifSearchResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"images",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGifSearchResponse := _GifSearchResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGifSearchResponse)

	if err != nil {
		return err
	}

	*o = GifSearchResponse(varGifSearchResponse)

	return err
}

type NullableGifSearchResponse struct {
	value *GifSearchResponse
	isSet bool
}

func (v NullableGifSearchResponse) Get() *GifSearchResponse {
	return v.value
}

func (v *NullableGifSearchResponse) Set(val *GifSearchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGifSearchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGifSearchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGifSearchResponse(val *GifSearchResponse) *NullableGifSearchResponse {
	return &NullableGifSearchResponse{value: val, isSet: true}
}

func (v NullableGifSearchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGifSearchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


