/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// SearchUsersResponse1 struct for SearchUsersResponse1
type SearchUsersResponse1 struct {
	APIError *APIError
	SearchUsersResult *SearchUsersResult
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *SearchUsersResponse1) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal JSON data into SearchUsersResult
	err = json.Unmarshal(data, &dst.SearchUsersResult);
	if err == nil {
		jsonSearchUsersResult, _ := json.Marshal(dst.SearchUsersResult)
		if string(jsonSearchUsersResult) == "{}" { // empty struct
			dst.SearchUsersResult = nil
		} else {
			return nil // data stored in dst.SearchUsersResult, return on the first match
		}
	} else {
		dst.SearchUsersResult = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(SearchUsersResponse1)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src SearchUsersResponse1) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.SearchUsersResult != nil {
		return json.Marshal(&src.SearchUsersResult)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableSearchUsersResponse1 struct {
	value *SearchUsersResponse1
	isSet bool
}

func (v NullableSearchUsersResponse1) Get() *SearchUsersResponse1 {
	return v.value
}

func (v *NullableSearchUsersResponse1) Set(val *SearchUsersResponse1) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchUsersResponse1) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchUsersResponse1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchUsersResponse1(val *SearchUsersResponse1) *NullableSearchUsersResponse1 {
	return &NullableSearchUsersResponse1{value: val, isSet: true}
}

func (v NullableSearchUsersResponse1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchUsersResponse1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


