/*
fastcomments

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)


// GetTicketsResponse1 struct for GetTicketsResponse1
type GetTicketsResponse1 struct {
	APIError *APIError
	GetTicketsResponse *GetTicketsResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetTicketsResponse1) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into APIError
	err = json.Unmarshal(data, &dst.APIError);
	if err == nil {
		jsonAPIError, _ := json.Marshal(dst.APIError)
		if string(jsonAPIError) == "{}" { // empty struct
			dst.APIError = nil
		} else {
			return nil // data stored in dst.APIError, return on the first match
		}
	} else {
		dst.APIError = nil
	}

	// try to unmarshal JSON data into GetTicketsResponse
	err = json.Unmarshal(data, &dst.GetTicketsResponse);
	if err == nil {
		jsonGetTicketsResponse, _ := json.Marshal(dst.GetTicketsResponse)
		if string(jsonGetTicketsResponse) == "{}" { // empty struct
			dst.GetTicketsResponse = nil
		} else {
			return nil // data stored in dst.GetTicketsResponse, return on the first match
		}
	} else {
		dst.GetTicketsResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetTicketsResponse1)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetTicketsResponse1) MarshalJSON() ([]byte, error) {
	if src.APIError != nil {
		return json.Marshal(&src.APIError)
	}

	if src.GetTicketsResponse != nil {
		return json.Marshal(&src.GetTicketsResponse)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableGetTicketsResponse1 struct {
	value *GetTicketsResponse1
	isSet bool
}

func (v NullableGetTicketsResponse1) Get() *GetTicketsResponse1 {
	return v.value
}

func (v *NullableGetTicketsResponse1) Set(val *GetTicketsResponse1) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTicketsResponse1) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTicketsResponse1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTicketsResponse1(val *GetTicketsResponse1) *NullableGetTicketsResponse1 {
	return &NullableGetTicketsResponse1{value: val, isSet: true}
}

func (v NullableGetTicketsResponse1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTicketsResponse1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


