/*
fastcomments

Testing PublicAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/fastcomments/fastcomments-go/client"
)

func Test_client_PublicAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PublicAPIService BlockFromCommentPublic", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var commentId string

		resp, httpRes, err := apiClient.PublicAPI.BlockFromCommentPublic(context.Background(), commentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService CheckedCommentsForBlocked", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PublicAPI.CheckedCommentsForBlocked(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService CreateCommentPublic", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string

		resp, httpRes, err := apiClient.PublicAPI.CreateCommentPublic(context.Background(), tenantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService CreateFeedPostPublic", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string

		resp, httpRes, err := apiClient.PublicAPI.CreateFeedPostPublic(context.Background(), tenantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService DeleteCommentPublic", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var commentId string

		resp, httpRes, err := apiClient.PublicAPI.DeleteCommentPublic(context.Background(), tenantId, commentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService DeleteCommentVote", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var commentId string
		var voteId string

		resp, httpRes, err := apiClient.PublicAPI.DeleteCommentVote(context.Background(), tenantId, commentId, voteId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService DeleteFeedPostPublic", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var postId string

		resp, httpRes, err := apiClient.PublicAPI.DeleteFeedPostPublic(context.Background(), tenantId, postId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService FlagCommentPublic", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var commentId string

		resp, httpRes, err := apiClient.PublicAPI.FlagCommentPublic(context.Background(), commentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService GetCommentText", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var commentId string

		resp, httpRes, err := apiClient.PublicAPI.GetCommentText(context.Background(), tenantId, commentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService GetCommentVoteUserNames", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var commentId string

		resp, httpRes, err := apiClient.PublicAPI.GetCommentVoteUserNames(context.Background(), tenantId, commentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService GetCommentsPublic", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string

		resp, httpRes, err := apiClient.PublicAPI.GetCommentsPublic(context.Background(), tenantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService GetEventLog", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string

		resp, httpRes, err := apiClient.PublicAPI.GetEventLog(context.Background(), tenantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService GetFeedPostsPublic", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string

		resp, httpRes, err := apiClient.PublicAPI.GetFeedPostsPublic(context.Background(), tenantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService GetFeedPostsStats", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string

		resp, httpRes, err := apiClient.PublicAPI.GetFeedPostsStats(context.Background(), tenantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService GetGlobalEventLog", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string

		resp, httpRes, err := apiClient.PublicAPI.GetGlobalEventLog(context.Background(), tenantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService GetUserNotificationCount", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PublicAPI.GetUserNotificationCount(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService GetUserNotifications", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PublicAPI.GetUserNotifications(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService GetUserPresenceStatuses", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PublicAPI.GetUserPresenceStatuses(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService GetUserReactsPublic", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string

		resp, httpRes, err := apiClient.PublicAPI.GetUserReactsPublic(context.Background(), tenantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService LockComment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var commentId string

		resp, httpRes, err := apiClient.PublicAPI.LockComment(context.Background(), tenantId, commentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService PinComment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var commentId string

		resp, httpRes, err := apiClient.PublicAPI.PinComment(context.Background(), tenantId, commentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService ReactFeedPostPublic", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var postId string

		resp, httpRes, err := apiClient.PublicAPI.ReactFeedPostPublic(context.Background(), tenantId, postId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService ResetUserNotificationCount", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PublicAPI.ResetUserNotificationCount(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService ResetUserNotifications", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PublicAPI.ResetUserNotifications(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService SearchUsers", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string

		resp, httpRes, err := apiClient.PublicAPI.SearchUsers(context.Background(), tenantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService SetCommentText", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var commentId string

		resp, httpRes, err := apiClient.PublicAPI.SetCommentText(context.Background(), tenantId, commentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService UnBlockCommentPublic", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var commentId string

		resp, httpRes, err := apiClient.PublicAPI.UnBlockCommentPublic(context.Background(), commentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService UnLockComment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var commentId string

		resp, httpRes, err := apiClient.PublicAPI.UnLockComment(context.Background(), tenantId, commentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService UnPinComment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var commentId string

		resp, httpRes, err := apiClient.PublicAPI.UnPinComment(context.Background(), tenantId, commentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService UpdateFeedPostPublic", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var postId string

		resp, httpRes, err := apiClient.PublicAPI.UpdateFeedPostPublic(context.Background(), tenantId, postId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService UpdateUserNotificationCommentSubscriptionStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var notificationId string
		var optedInOrOut string

		resp, httpRes, err := apiClient.PublicAPI.UpdateUserNotificationCommentSubscriptionStatus(context.Background(), notificationId, optedInOrOut).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService UpdateUserNotificationPageSubscriptionStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var subscribedOrUnsubscribed string

		resp, httpRes, err := apiClient.PublicAPI.UpdateUserNotificationPageSubscriptionStatus(context.Background(), subscribedOrUnsubscribed).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService UpdateUserNotificationStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var notificationId string
		var newStatus string

		resp, httpRes, err := apiClient.PublicAPI.UpdateUserNotificationStatus(context.Background(), notificationId, newStatus).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService UploadImage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string

		resp, httpRes, err := apiClient.PublicAPI.UploadImage(context.Background(), tenantId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicAPIService VoteComment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var commentId string

		resp, httpRes, err := apiClient.PublicAPI.VoteComment(context.Background(), tenantId, commentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
